### ISSUE TITLE
false positive? www.mywot.com

### ISSUE THREAD

**Issue by pradorocchi** [StevenBlack/hosts#1022]
Hi, 
As far as I know WoT (Web of Trust) is a site reputation index, based on user's submitted ratings and votes.

I'm not 100% firming this is a false positive, but to my knowledge it is.

is there any reason for this domain [www.mywot.com] inclusion on StevenBlack main host file?

(it is on line 58 and 59 of https://github.com/StevenBlack/hosts/blob/master/data/StevenBlack/hosts )

**Comment by StevenBlack** [comment]
Hi Rafael @pradorocchi, this domain comes from [my ad-hoc list of domains](https://github.com/StevenBlack/hosts/blob/master/data/StevenBlack/hosts).

It was added three years ago by Tomasz @FadeMind in [this commit)(https://github.com/StevenBlack/hosts/commit/721c4033d58698b366bf1debeb4bc6ceb07d14fa) which has this commit message:

>  block mywot domain
>  
>  Web Of Trust developers selling collected data: 
>  http://thehackernews.com/2016/11/web-of-trust-addon.html
>  http://www.ghacks.net/2016/11/01/browsing-history-sold/

Therefore, unless I see evidence otherwise, blocking mywot and its related domains is legitimate.
