### ISSUE TITLE
Please add this into Porn Blocklists

### ISSUE THREAD

**Issue by LittleCordines** [StevenBlack/hosts#1048]
Hello. Currently I am using your porn blocklist hostfile. [This list](https://raw.githubusercontent.com/LittleCordines/pfsense-hosts-file/master/PornBlocklists) I made which is not blocked yet. If you don't mind to add it to your list. Thanks

**Comment by StevenBlack** [comment]
Note to self: the actual repo URL is https://github.com/LittleCordines/pfsense-hosts-file/.

**Comment by LittleCordines** [comment]
sorry. i am new to github. how to merge..

**Comment by StevenBlack** [comment]
@LittleCordines I'm sorry if I was unclear.

Here's the thing.

I can't accept your repo as a source of hosts because you don't have a history of list curation.  

Your list is very new.  If you actively maintain your list, adding and removing domains, over several months, then we will consider it.

We're committed to only use well-curated lists, here.

Sensible?

**Comment by LittleCordines** [comment]
clearly understood
