### ISSUE TITLE
Two hosts files

### ISSUE THREAD

**Issue by infinitytec** [StevenBlack/hosts#1061]
I have a hosts file that may be of interest:
[Ads and trackers I have found around.](https://github.com/infinitytec/blocklists/blob/master/ads-and-trackers.txt)

**Comment by StevenBlack** [comment]
Hi @infinitytec – thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

I can't accept these new hosts because there is no established history of curation.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
