### ISSUE TITLE
KADhosts blocks spyware.neocities.org as "fake news"

### ISSUE THREAD

**Issue by The-Compiler** [StevenBlack/hosts#1094]
The KADhosts list currently blocks https://spyware.neocities.org/ as "fake news". I opened https://github.com/PolishFiltersTeam/KADhosts/issues/26 and was told:

> It's blocked, because author of this page is not familiar with the subject and writes nonsense or maybe it's controlled fake news.
> They're extrapolating a lot of points and making up theories.

I'd argue this alone isn't enough justification to block something as "fake news", but even if it was: The default list is supposed to block adware/malware, which this clearly is not.

Maybe the KADhosts list should be moved to the fakenews extension? Maybe the main list should only include its ["without controversies"](https://github.com/PolishFiltersTeam/KADhosts/blob/master/KADhosts_without_controversies.txt) variant?

**Comment by funilrys** [comment]
Here a side note for you Steve @StevenBlack

I made a translation (thanks to the translator) of relevant comments so that you may get an overview:

> Filtry chroniace przed przekretami takimi jak subskrypcje SMS

Filters to protect against scams such as SMS subscriptions

> Podejrzane i/lub strony polaczone z innymi oszustwami

Suspicious and / or websites linked to other scams

> Nieprawdziwe, wprowadzajace w blad informacje lub podobne.

False, misleading or similar information.

> Przekierowuja do innych stron z przekretami

Redirects to other pages with scams

> Szybko wygaszajace

Fast quenching

> Przekrety

scams

> Uzupelnienie hosts do promocji pseudonauki / fake newsow

Supplement hosts to promote pseudoscience / fake news

-----------------------------

Also, the links in the `update.json` file are wrong as the repository was moved elsewhere :wink:

Cheers!

**Comment by StevenBlack** [comment]
Thanks for this, Florian @The-Compiler.  And thanks Nissar @funilrys for the additional information.

Tomasz @FadeMind can you clarify?  Thanks!

**Comment by StevenBlack** [comment]
Resolved by #1095.  Closing.
