### ISSUE TITLE
Problem With WhatsApp

### ISSUE THREAD

**Issue by maruashok** [StevenBlack/hosts#1118]
Please remove *whatsapp.com relates hosts from default block list (Unified hosts = (adware + malware)), because it causes problem with download and upload media.

**Comment by StevenBlack** [comment]
Hi Ashok @maruashok  – thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

The domain `downloads-whatsapp.com` comes to us via  malwaredomainlist.com whom you can contact [here](https://www.malwaredomainlist.com/contact.php), and also via @fademind who curates the `add.Risk` source.

The domain `www.downloads-whatsapp.com` comes to us via  @fademind who curates the `add.Risk` source.

User @sinfonietta curates our social media extension files.  I presume the social media extension is out of scope for this request since you mention only the default hosts list specifucally.

Therefore, please make your case with  [malwaredomainlist.com](https://www.malwaredomainlist.com/contact.php) and with user @fademind.  Both are very good, long-time curators, and we trust them to do what's right.

Closing.
