### ISSUE TITLE
NO UPDATES ???

### ISSUE THREAD

**Issue by Kees1958** [StevenBlack/hosts#1137]
Peter Low's list has been updated recently (28 januari) and Steven's host file is not updated. What is happening, Steven are you ill or on holiday? Why no updates, hope all is well!

Changed type of 18 januari to 28 januari, apologize for the mistake

**Comment by ScriptTiger** [comment]
> Peter Low's list has been updated recently (18 januari) and Steven's host file is not updated. What is happening, Steven are you ill or on holiday? Why no updates, hope all is well!

https://github.com/StevenBlack/hosts/commit/3ec743468a83c472dd18543b95be208de5380437 and https://github.com/StevenBlack/hosts/commit/d9c9d7b983b0b4c601d6d5c1950b3b4e09260fcf were both committed on Jan 25, 2020 (officially Jan 24 for Steven's time zone) as per the commit log (https://github.com/StevenBlack/hosts/commits/master), well after January 18. In fact, as you can see from the commit log, there have been four updated releases pushed since then.

If you are using Microsoft Windows, I would highly recommend checking out this project to keep your hosts up to date for you if you are having trouble tracking the updates, as seems to be the case:
https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate

**Comment by Kees1958** [comment]
@ScriptTiger 

Sorry, Peter's Low was updated yesterday 28 of Januari (sorry for the type). Yesterday's updates are not included in Steven's List (as mentioned by your references which show last update was five days ago)

**Comment by ScriptTiger** [comment]
> Sorry, Peter's Low was updated yesterday 28 of Januari (sorry for the type). Yesterday's updates are not included in Steven's List (as mentioned by your references which show last update was five days ago)

Steven hosts the pre-generated hosts lists as a courtesy and can hardly be expected to run daily updates on a volunteer basis. The primary focus of this repository is focused on the Python script. If you have requirements for daily updates, I would recommend keeping a local copy of the Python script and generating your own local daily updates.

**Comment by Kees1958** [comment]
OK, thanks I thought it was an automated process, since it mentioned Python scripts. I will use https://energized.pro/ SPARK list lite instead then, thanks for the clarification

**Comment by ScriptTiger** [comment]
No worries. You can direct your issues for that project here:
https://github.com/EnergizedProtection/block/issues

**Comment by Kees1958** [comment]
Thx for the updates
