### ISSUE TITLE
Why aren't other known sources just merged here ?

### ISSUE THREAD

**Issue by moodule** [StevenBlack/hosts#1151]
Hello, I just got started with DNS filtering with the Pi-Hole and I love what you're doing here ! :+1:

Looking around I found a lot of other sources, like:
- [CHEF-KOCH](https://github.com/chef-KOCH/NSABlocklist/) and such
- [hmirror](https://github.com/hectorm/hmirror/tree/master/data)

So I wondered why they're not listed here?
Is it a lack of curation / references?
Because the lists are not categorized?
Or did I just miss them?

If not, should I submit PRs?

**Comment by StevenBlack** [comment]
Hi David @moodule, thank you for your question.

This list amalgamates lists from sources that have demonstrated ongoing active curation.  We're not really interested in lists that carry hundreds of thousands of domains because, by definition, curation can't properly happen at that scale.

This is also a balance between Type I and Type II errors.  I can tall you that, at our present scale, that starts to become difficult.

Wide applicability is also important — once a hosts file becomes large, performance on mobile devices and some routers begins to degrade noticeably.

So it's all about balancing conflicting priorities.

That said, if you have a suggestion for a list we don't have,  please raise it!  The link to `CHEF-KOCH`, above, returns nothing at present...

**Comment by ScriptTiger** [comment]
@CHEF-KOCH also frequents this repo and gives his advice from time to time. So far I believe he has already advised us on domains that should be included or not, so I don't think we need to pull them again from his lists.

For a list to be added to this project as a source, there is a thorough review that must be conducted for things such as you mentioned, curation, reputability, documentation, etc. If problems arise with a particular domain that is being sourced by a particular list in question, the curator should be easily contacted for documentation on that domain as to the reason it's included and any particular known side-effects of it being blocked, etc. Due to all of these factors, it's usually preferred if the curator can personally make a certain commitment to our community first before being integrated.

**Comment by StevenBlack** [comment]
Thanks @ScriptTiger — that too 😄

**Comment by ScriptTiger** [comment]
Sorry for the double-tap. I opened this issue before you replied but got interrupted in the middle of typing it, then after I submitted it I realized you already hit it. Your answers can always stand on their own :P

**Comment by moodule** [comment]
Ok, thank you for taking the time to answer my n00by question!!

[CHEF-KOCH](https://github.com/CHEF-KOCH) has several hosts lists, by topic (NSA spying etc).

Indeed it looks time consuming, I'm grateful and this comment was in no way a critic.

I was just surprised, since this repository is so well known why wouldn't other common sources just submit here??
That was me being lazy ^^

**Comment by llacb47** [comment]
CHEF-KOCH has stolen lists in the past, I would not blindly include their lists in this project without further consideration. https://github.com/ghacksuserjs/ghacks-user.js/issues/323

**Comment by moodule** [comment]
oh wow that was really not where I was going either!!!
i came from the [pi-hole recommandations](https://discourse.pi-hole.net/t/update-the-best-blocking-lists-for-the-pi-hole-alternative-dns-servers-2019/13620) and took it as reference without proper research...

**Comment by StevenBlack** [comment]
OK, well, I think I'll close this now. 🙄
