### ISSUE TITLE
Important website - remove from blacklist

### ISSUE THREAD

**Issue by vvcares** [StevenBlack/hosts#1175]
Hi,
mobile.pipe.aria.microsoft.com - this url can be remove from the blacklist of GAMBLING. This seems not to be a blacklisted domain & occupying max blacklisted records on the network,

I did my whitelist, but better if this not to be blacklisted on your list.

**Comment by StevenBlack** [comment]
Hi @vvcares the domain `mobile.pipe.aria.microsoft.com` comes to us via AdAway.  It's in all our lists.

@jawz101 can you look at this one, as well?  Thanks.

**Comment by jawz101** [comment]
Well, I agree that it's not be a gambling-related DNS entry.  And this has been discussed [before](https://github.com/StevenBlack/hosts/issues/970)

I'd have to have good reason to remove it.  Just because it hits a lot isn't a reason.  Not receiving emails or draining a phone's battery due to repeated requests are good reasons.  I can say that the Outlook mobile app for Android aggressively tries to look that DNS entry up.

**Comment by StevenBlack** [comment]
@jawz101 Sorry if I wasn't clear.  The  domain `mobile.pipe.aria.microsoft.com` is in all our lists.  Which means it is in our base list.  OP was probably only looking in the gambling list.

I agree with you; this domain stays blocked.

Closing.
