### ISSUE TITLE
http://winhelp2002.mvps.org/ certificate broken

### ISSUE THREAD

**Issue by XhmikosR** [StevenBlack/hosts#1183]
So, apparently the SSL certificate for https://winhelp2002.mvps.org/ has expired. I'm not sure if this is just a one time thing, but if it's not automated, we might as well switch back to the http link.

If anyone is in touch with them, please let them know in case they are not aware, that they need to automate this, otherwise it's moot since Let's Encrypt's certificates expire every 90 days :/

**Comment by funilrys** [comment]
It's probably automated. It's just that their client did not recognize that it needs to renew some of their certificates.

It's all probably because of [2020.02.29 CAA Rechecking Bug](https://community.letsencrypt.org/t/revoking-certain-certificates-on-march-4/114864).

Can you contact them about this Steve @StevenBlack ?

**Comment by StevenBlack** [comment]
I just adjusted the link to vanilla `http` and when they get sorted, we'll switch it back.

Some of you feel like automating certificates on Windows is a thing 😄 — maybe it is, I just know that if there's a clusterfk on Windows, that may be it.

Closing.

**Comment by superlex** [comment]
@StevenBlack 
Hello,
now it seems fixed :)

**Comment by XhmikosR** [comment]
TBH I wanted to wait until at least 90 days pass to make sure autorenewal works fine...
