### ISSUE TITLE
OneSignal

### ISSUE THREAD

**Issue by slvxstar** [StevenBlack/hosts#1184]
Exact match for **onesignal.com** found in:
   https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

OneSignal - Push Notifications Delivered
powering mobile push, web push, email, and in-app messages

It is advisable to remove it from the block sheet

**Comment by StevenBlack** [comment]
Hi @slvxstar the `onesignal.com` is flagged by no fewer than five of our curated sources.

Think about it.  Five.

This isn't going to change.

Closing.

**Comment by goetzc** [comment]
@StevenBlack it's currently on 3 [lists](https://github.com/StevenBlack/hosts/search?q=onesignal.com&unscoped_q=onesignal.com), looks like they are removing it.

Some blocking lists like EasyList filter do have a whitelist<sup>[1]</sup>, and there is one for onesignal.com. uBlock team does also maintain an 'unbreak' list<sup>[2]</sup>.

This is because of Push notifications. If your compilation list is used on a router or directly on a mobile device, all push notifications that many mobile apps use (there are a lot, [one example](https://onesignal.com/case-studies)) will simply not work. Other push notifications services might be broken, don't know about them.

Please consider using the available whitelists from the upstream providers to curate the final list, so we can continue having push notifications by default.

[1] https://github.com/easylist/easylist/commit/e04c519e07898ffd1311ea0b5a5cd40930893372
[2] https://github.com/uBlockOrigin/uAssets/blob/afb462cb3e04945a30c61b39ec50ba326f83083e/filters/unbreak.txt#L2566

**Comment by StevenBlack** [comment]
@goetzc that's not how this works.

We let upstream curators decide.  We trust our curators.  If we think there is a problem, we advise them, and we let them decide.
