### ISSUE TITLE
Why is "graph.instagram.com" blocked?

### ISSUE THREAD

**Issue by gajicm93** [StevenBlack/hosts#1206]
Why is this domain blocked?

It's a legit Instagram public API used by developers all around the world. I just lost half an hour trying to figure out why this domain was not working for me until I remembered it might be blocked by hosts..

**Comment by StevenBlack** [comment]
Hi Marko @gajicm93.  The `graph.instagram.com` comes to us via yoyo.org.  Can you please submit this to pgl@yoyo.org?

Interesting that `graph.instagram.com` was added two years ago, so we've had it listed for awhile.  In your discourse with yoyo, I'd be interested to know why it's blocked.  Perhaps the Social Media extension would be a better place for that.  See what they say.

**Comment by pgl** [comment]
Hi Guys. `graph.instagram.com` was added on Sat, 27 Jan 2018 15:39:08 as @StevenBlack pointed out.

It was added because my understanding of the domain is that it's used for tracking user behaviour. If this is incorrect, please let me know and I'll remove it from my list.

If it is used for tracking, but also breaking legitimate sites, then this is a weaker reason for removal but worth considering. Comments are welcome.

**Comment by MitchellCash** [comment]
@pgl out of curiosity, was there a reason why `graph.instagram.com` made the list, but `graph.facebook.com` did not? As both are Facebook owned properties, I imagine they have similar use cases.

According to the Facebook documentation (https://developers.facebook.com/docs/graph-api/overview/) on the Graph API that exists on these domains explains:

> The Graph API is the primary way to get data into and out of the Facebook platform. It's an HTTP-based API that apps can use to programmatically query data, post new stories, manage ads, upload photos, and perform a wide variety of other tasks.

This doesn't include being an obvious tracking domain, but it also doesn't exclude it either.

**Comment by pgl** [comment]
So, OK, it seems like this domain is used for developers really and not as a general tracking domain. I've removed it. Apologies for any inconvenience caused!

@MitchellCash `graph.facebook.com` didn't get added because I wasn't aware of it - I don't really use Facebook myself and it was never reported.

@StevenBlack Just FYI, but if you ever want to "whitelist" something with my list, you can use the `skip[]=` query string parameter which will exclude entries when viewing the list:

 * https://pgl.yoyo.org/as/formats.php#skip

It's not proper whitelisting of course, but it has roughly the same effect.

**Comment by StevenBlack** [comment]
Thanks everybody.  And thanks for all you do Peter @pgl.

Closing.

**Comment by llacb47** [comment]
The endpoint `graph.instagram.com/logging_client_events` is used for tracking. Facebook has cleverly made two things true at once: the domain is used for their API and for tracking.

![image](https://user-images.githubusercontent.com/16567977/80287261-9ce09300-86fe-11ea-8fd4-80f9afce1fca.png)

**Comment by SidKali** [comment]
graph.facebook.com if blacklisted then Market place on facebook app will not load content. so that one thing I found about it

**Comment by nightznero** [comment]
I have whitelisted `graph.facebook.com ` bcs if its blocked u cant even refresh a facebook app,but even if i have blocked `graph.instagram.com ` Instagram app normally works,reshes etc. For me its weird that fb only uses fb graph but ig uses both of graphs. I m not any of specialist but if ig works with blocked ig graph its a different usage of it...even if "Meta" says something different at their pages. Lil sus
