### ISSUE TITLE
Please include Advertisement/Tracking

### ISSUE THREAD

**Issue by ghost** [StevenBlack/hosts#121]
http://hosts-file.net/?s=Download

Individual Classifications
ATS
EMD
EXP
FSA
HFS

BTW, keep up a good work guys.

**Comment by Laicure** [comment]
I think those are purposely not included. See this [reason](https://github.com/StevenBlack/hosts#goals-of-this-unified-hosts-file). (Though I _customly_ include some of those sources to for own use.)

Current Count as of posting this response:
ATS - 47,708
EMD - 117,357
EXP - 17,212
FSA - 71,754
HFS - 560

Those will make the curation activity _longer_.
- Tried it with my smartphone; cannot longer connect to WIFI.
- Tried it with my Windows PC; needs to disable DNS else it messes up with the parsing thing of my internet connection.
Though I even want those included, it's on our own to include/make those sources to our **custom** _[data](https://github.com/StevenBlack/hosts/tree/master/data)_ source.

**Comment by espress0** [comment]
Well, I use your raw hosts file( https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts )
which is a combination of 'adware' and 'malware' lists.

> Unified hosts = (adware + malware)

EMD = This file contains malware sites
EXP = This file contains exploit sites

I think these two are 'malware' list.

> curation activity longer.
You can use "AcrylicDNS" with hosts.
I'm using it for caching DNS request, and it's really doing a good job.

> my smartphone; cannot longer connect to WIFI.
...Is your phone rooted and you simply add a tons of hosts data to Android?
If I were you, I set up a local server(AcrylicDNS), and let android use it(Wifi -> Settings -> DNS).

> it messes up with the parsing thing of my internet connection.
I don't know what the "parsing thing" is.

---

I wrote a php script to do:
1. Fetch additional hosts files.
2. Split into array, and merge it. Make it unique(no duplicate).
3. Optimize as possible(because I use AcrylicDNS; 0.0.0.0 a.com\n0.0.0.0 b.com ==> 0.0.0.0 a.com b.com)
4. Save to text file.

**Comment by Laicure** [comment]
oh that [link](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts) is from @StevenBlack's repo, not mine ;)

/hmm haven't tried Acrylic DNS on my Windows PC.
And for my Smartphone, it's an _Interop-Unlocked_ Windows Phone (Lumia), sorry I forgot to include the phone OS above. (I am using my [own](https://github.com/Laicure/HostsX) generated hosts file with additional sources from [hosts-file](http://www.hosts-file.net).)

- Current PC Hosts file: 74k+ Entries, 2MB+
- Current Smartphone Hosts file: 57k+ Entries, ~1.9MB

The _parsing thing_ I am pointing to (apologies for being vague there) is the re-caching of the DNS entries whenever I _update+flushdns_ my PC hosts file.

/hmm going back to your topic, are you suggesting to include ATS, EMD, EXP, FSA, and HFS on the repo [sources data](https://github.com/StevenBlack/hosts/tree/master/data) by default?

**Comment by 5t4r3e2w1q** [comment]
> are you suggesting to include ATS, EMD, EXP, FSA, and HFS on the repo sources data by default?

Yes. At least, EMD and EXP.

**Comment by reddit-is-fun** [comment]
Default host files block a lot of advertising and tracking domains.

**Comment by StevenBlack** [comment]
My beef with `hosts-file.net` is it doesn't have a very high curation rate.

On aggregate it has 300k+ domains listed.  At that level, compared to other actively curated sources here, I'd expect dozens of adds/removals per day.  That's just not the case, and it hasn't been the case for awhile.

I don't want a big bloated hosts file containing domains that may have been questionable several years ago.  I'd rather have a tight hosts file with domains that are questionable now, or recently.

More to the point, slow curation also means slow-reacting to new threats, and that's not good either.

People can include any facet of `hosts-file.net` as they please.  We're just not going to do that by default purely because of bloat which brings up so many other issues, especially for those who are stuck on Windows OS, or don't know anything but Windows OS.  Those people have 99 other problems :-)

So closing.

**Comment by reddit-is-fun** [comment]
@StevenBlack `hosts-file.net` causes a lot of issues, Malwarebytes wants to block all torrent sites for example. Thank you for understanding.
