### ISSUE TITLE
Remove Rollbar from blockers list

### ISSUE THREAD

**Issue by letaniaferreira** [StevenBlack/hosts#1281]
Hello,

I am reaching out to ask that you to please remove rollbar.com from your blocked list since it's a legit developer tool and not a malicious or advertising tool.

**Comment by gustavodiel** [comment]
I second this, Rollbar.com is a error tracking service, not a spam tool.

**Comment by izn** [comment]
I'm opening a PR to remove *.rollbar.com from blacklist.

**Comment by StevenBlack** [comment]
Hello Letania @letaniaferreira, Thaynã @izn, and Gustavo @gustavodiel.

Here is our [prior discussion about Rollbar](https://github.com/StevenBlack/hosts/issues/1096), which explains why Rollbar is presently blocked.  This was not an easy call.  Rollbar is an edge case and this is where we've drawn the line.

That said, I'm open to be convinced otherwise.  In particular, is there a Rollbar privacy policy, or an ethical facet that we may have missed?

It's helpful to consider, this hosts list is for people who just don't want to be tracked, ad-bombed,  phished, or everything else.

**Comment by izn** [comment]
Thanks for your quick reply, @StevenBlack.

I think we should start a discussion about the Rollbar's Privacy Policy: https://docs.rollbar.com/docs/privacy-policy

Although, particularly, the biggest problem I see is in the [hblock repository)(https://github.com/hectorm/hblock) which uses your repository as a source - since this application is pre-installed on some Linux distributions (such as ArcoLinux), Rollbar's website and API are blocked "by default". I'm not sure if we should update **hblock** or remove from your blacklist. I'm open to suggestions.

**Comment by gustavodiel** [comment]
My suggestion would be to open `rollbar.com` and/or `www.rollbar.com` and leave `api.rollbar.com`, as I am almost certain that every tracking is made via the `api` domain.
This leaves us with a good balance between accessing the service and stopping the tracking. WDYT?

**Comment by izn** [comment]
If we're sure that Rollbar's tracking is made only through `api.rollbar.com`, I agree with @gustavodiel. :grimacing:

**Comment by StevenBlack** [comment]
Thaynã @izn if you make this change to [the PR](https://github.com/StevenBlack/hosts/pulls) then I'll merge it.

**Comment by izn** [comment]
I will update the PR now, removing only the `api.rollbar.com` entry.

**Comment by izn** [comment]
[Done](https://github.com/StevenBlack/hosts/pull/1283/commits/fcf74d2903da2edad8761266b625de8e167c21d9).
