### ISSUE TITLE
[Info] NetGuard(paid app) using your FREE hosts file.

### ISSUE THREAD

**Issue by verycrypt** [StevenBlack/hosts#130]
Just for the heads up; do you know that your HOSTS file was used in
github.com / M66B / NetGuard
which is a PAID APP?

http://netguard.me/hosts

Just for the info from @M66B.

**Comment by M66B** [comment]
Most of NetGuard features are completely free and NetGuard is also 100% open source. Ad blocking is a free feature. The use of the hosts file is properly attributed in the opening post of the XDA NetGuard thread. The only place where ad blocking is 'advertised' is on XDA, since ad blocking applications are not allowed in the Play store.

Moreover, the hosts file URL is configurable, so everybody can freely choose which hosts file to use. The configure hosts file URL is just a default for the convenience of the users.

If something needs to be changed, just let me know and I will take care of it.

**Comment by StevenBlack** [comment]
Thanks @verycrypt.  @M66B no worries all-good, keep up the good fight!

**Comment by matkoniecz** [comment]
@ghost

Note that https://github.com/StevenBlack/hosts/blob/master/license.txt explicitly grants permission to 

> and/or sell copies of the Software

So it does not matter whatever it is used in paid program.

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

is the only requirement.
