### ISSUE TITLE
Renaming blacklist/whitelist

### ISSUE THREAD

**Issue by toastal** [StevenBlack/hosts#1317]
From the code of conduct

> Using welcoming and inclusive language

In the light of recent current events, many projects are moving to more inclusive language. Since it's dubious to keep a name that could be problematic when alternatives exist--especially when a name has the opportunity to be more clear--it's probably a good idea if this project joins the ranks. 

It seems most projects from Chromium, to Drupal, to Rails, to et.al. have chosen `whitelist → allowlist` and `blacklist → blocklist`.

**Comment by StevenBlack** [comment]
Hi @toastal, thank you for this.

This would be a breaking change affecting a lot of things.  We could only do something like this in the context of a major version release.  In other words, this would not be a patch, or a minor change.

At minimum we would need to enumerate all the plausible issues in userland, and provide automated means to deal with this including supporting both, for a time, with deprecation notices.

This won't happen unless it becomes a priority.  And it certainly won't happen soon.

**Comment by funilrys** [comment]
If I can add something. I'm not personally offended by the terms `blacklist`, `whitelist` and `master`.
And technically speaking, those terms are already present everywhere. It's like the recent discussion about changing the `master` branch name to something else because of the "recent current events". Most of us can probably do the difference between a technical word and a non-inclusive language.

If we really want to change that, let's start with the TV series `The Blacklist`, the whole list of RFC regarding the DNS specification, the policies of each countries in the world and let's not forget the Linux Kernel!

I do understand that Android / Google Chrome, Drupal, Rails [etc.] renamed those words. But the context and the way those changes can be applied and deployed are way easier than what we do here.

I do understand the "why" and I know it's not a bad idea at all as it makes it more inclusive. But changing a whole bunch of technical words is not going to change the world regarding the "recent current events". If we would want to, we will need to contact all list maintainers in the world and that's impossible.

I do understand the why those discussions are starting only now. But it's kinda hypocrite as those discussions could have started years ago when the RFCs were written or when those denominations where chosen in the technical fields. 

I'm sure that most of us can do the difference. 
My opinion.

----------------------
Let's talk about the change itself.

This change is hard to apply as this project is not a program itself. We are here talking about an incalculable scale. Changing the name of the `whitelist` file alone will cause some drastic change across the globe. This list is used by so many infrastructures, machines, systems that such change can become really painful.
Let's take the example of the recent discussion about renaming the name of the `master` branch to something else. That will break a lot of things for a repository of this size and reputation as everybody is writing his own script or infrastructure based on what we have here. It's not that easy to deploy such change.

That will probably apply to the modification of the terms.

**Comment by aelisya** [comment]
and if we think like this does we have to rename our css too from color : black to color : #000000 ?, no you can't just ask for changing our variable name, and list name in the technical code.

And even inclusive language is a pain in the ass for the dyslexic people, so changing name on some very used place, why not if it your fun.
But Certainly not everywhere !

**Comment by theodoreb** [comment]
Would it be a problem to make the name of the generated files configurable ? I'm not seeing a lot of code involved in the blacklist/whitelist filenames. Similar to what was done in git for the default branch name. that would help with deprecating the default filenames and software that do rely on keeping those outdated names can still configure this script to output the name they expect.

**Comment by aelisya** [comment]
@theodoreb Political matter have no place in technical development and list code, you can't just ask to redo all code just because the actual political problem.
Whitelist and Blacklist is used in thousand of software who turn on server, and the time to rename all of that code will cost too much money to be done.
So yes black live matters and all of that BUT political problem have no place in Technical World

**Comment by theodoreb** [comment]
I'm talking about adding feature to the software here.

**Comment by mabod** [comment]
I am surprised about some statements here. This is about a language that implies that white is good and black is bad. There is no doubt that this language is not inclusive. And this is not about changing the world or changing the history, historical documents as such. This is about changing the future. Using different words from now on. Stop using blacklist as a word. Start using blocklist from now on. I do not understand how somebody could be against that approach. 

And a statement like " So yes black live matters and all of that BUT political problem have no place in Technical World" is completely off topic.

**Comment by StevenBlack** [comment]
I'm going to close lock this because we've had enough input on this.  We aren't changing it.
