### ISSUE TITLE
Another robux phishing scam

### ISSUE THREAD

**Issue by CyanoTex** [StevenBlack/hosts#1322]
What: This website falls into the umbrella category of “Scams and Phish”, but more specifically, both “Roblox scams” and “Scams targeting children”.
How: On Roblox Discord servers, warnings were being issued about this.
[Here's a warning posted on the Databrawl Discord advising people to secure their accounts.](https://i.imgur.com/fkk73Ai.png)
[Example of a compromised individual's account.](https://i.imgur.com/QlqgM4s.png)
Where: This scam lives at `https://rbx.best/`.

**Comment by StevenBlack** [comment]
@CyanoTex this doesn't seem actionable.

**Comment by CyanoTex** [comment]
> @CyanoTex this doesn't seem actionable.  

Understandable. At least I tried to save some unfortunate young souls from being phished. ☹️

**Comment by StevenBlack** [comment]
Maybe one of our curators will list this?

@hawkeye116477 you list `rbxfree.com` and `www.rbxfree.com` in [KADhosts](https://github.com/PolishFiltersTeam/KADhosts).  Is `rbx.best` related?

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/KADhosts/commit/8740ba8409e1fd4726f5f430c5b0a91810d1adbb#diff-92d3b2a6b099788b883d18eb574d874bR878
https://github.com/PolishFiltersTeam/KADhosts/commit/8740ba8409e1fd4726f5f430c5b0a91810d1adbb#diff-92d3b2a6b099788b883d18eb574d874bL573

We are probably `rbxfree.com` on the list because of the popularity of the` Roblox` game, because now the site has no polonization.

---

Oher story is that young people mostly learn English as a second language, less frequently learn German; probably part as a third learn Spanish language (`rbxfree.com`).

**Comment by StevenBlack** [comment]
Thanks Krystian @krystian3w.

Closing.
