### ISSUE TITLE
Amazon App Unable to connect

### ISSUE THREAD

**Issue by dfrost16** [StevenBlack/hosts#1362]
### Device
Redmi Note 5 pro 
Os: Android 10
App-version Adway 5.0.5 (root based)
![Screenshot_20200801-082850~2](https://user-images.githubusercontent.com/24663673/89093031-5ae97c00-d3d4-11ea-8c43-07bafc2a31f9.jpg)

However this issue seems to be solved by installing adway self signed certificate.

**Comment by StevenBlack** [comment]
Thanks for this Mehboob @dfrost16.

Is anyone else seeing this?

**Comment by dfrost16** [comment]
> Thanks for this Mehboob @dfrost16.
> 
> Is anyone else seeing this?

Ah I would like to add one more thing. The website works just fine it's just the app that refuse to connect unless I install the self signed adway cert

**Comment by StevenBlack** [comment]
ah.  This sounds like an AdAway issue.  AdAway issues are located [here](https://github.com/AdAway/adaway.github.io/issues).

Closing.

**Comment by jpope777** [comment]
I was using the master hosts file in my bind9 configuration to block ads from my whole home network (LAN and wifi connections). I had to stop due to getting this same error when trying to access anything in the Amazon app when connected to the wifi. If I would disconnect the wifi, the Amazon app would load normally. Does not affect accessing Amazon via web browser while on wifi.

**Comment by StevenBlack** [comment]
Thanks for this @jpope777.  I'm pretty sure the issue is AdAway's.  [Issues are here](https://github.com/AdAway/adaway.github.io/issues).
