### ISSUE TITLE
Remove device-api.urbanairship.com

### ISSUE THREAD

**Issue by cnordvik** [StevenBlack/hosts#1378]
from https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts

device-api.urbanairship.com is used to register push registrations for receiving notifications in some of the most popular livescores apps on Android and this breaks score alerts on them. Hope you can remove it as most other ad blockers have removed urbanairship.com from their blacklist due to this issue.

**Comment by StevenBlack** [comment]
Thanks Christer @cnordvik the `device-api.urbanairship.com` domain comes to us via AdAway.

@jawz101 can you please have a look, and comment?  Thanks, as always.

**Comment by jawz101** [comment]
I'd have to hear from end users because this is a developer's sentiment.  I could say the same thing about Localytics, Pushwoosh, OneSignal, Kumulos, Braze, Leanplum, and several other engagement/notification services.  There are many ways to push a notification but these products are advertised with analytics in mind and driving service engagement to continually use a product.

_"You just passed our store.  Here's a coupon."

"You haven't opened are app in a while.  Why don't you click me for some points?"_

I'd have to hear from other people.  That subdomain is like in the top 10,000 DNS requests in the world for OpenDNS Unbrella and that typically indicates it's heavily tied with analytics.  I see hits to that domain from apps that are not sports or weather ticker-type apps- rather it's analytics.

**Comment by cnordvik** [comment]
We also use OneSignal on another platform 😁. Airship and OneSignal are used by a lot of the top 100 apps, and I think a lot of them use it for push notifications only and don't rely on the analytics part. 

> "You just passed our store. Here's a coupon."
I would argue that disabling push notifications for an app is very easy these days (long press the notification and disable them) so I don't see this as a big problem for most users that they get push alerts for an app they have installed? 

These SDKs do track the users on the same level as Google does with Firebase so for a user very concerned about privacy it makes sense to block them, but it's just frustrating on our end getting all these support requests with no push working and we have to ask them if they got AdAway and guide them through whitelisting the push registration domain.

**Comment by StevenBlack** [comment]
> I think a lot of them use it for push notifications only and don't rely on the analytics part.

Christer @cnordvik I understand, and maybe so, but we serve people who don't want to be tracked in any way.  It's really that simple.

Closing.

**Comment by GitHugz** [comment]
> I'd have to hear from end users because this is a developer's sentiment. 

As an end user with an app function with this domain blocked: I have seen this domain in my query list, but have had no loss of function as suggested. Notably, push functions perfectly when I tested it **without** whitelisting this domain. 

Thank you, @jawz101 & @StevenBlack for handling this pretense with wisdom and integrity.
