### ISSUE TITLE
Add ip6-localhost

### ISSUE THREAD

**Issue by yagop** [StevenBlack/hosts#139]
Add ip6-localhost to hosts file

In Ubuntu:

```
127.0.0.1   localhost
# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

In Android:

```
127.0.0.1       localhost
::1             ip6-localhost
```

**Comment by StevenBlack** [comment]
@yagop do you know... how are these used, in practice?  I'm not finding any compelling cases.

Not saying no :-) just curious how this makes the hosts file better.

**Comment by yagop** [comment]
To be honest I don't know where its used in practice. I've seen it sometimes used for testing loopback IPv6 sockets.

Other distributions uses it too: http://superuser.com/a/1005792

**Comment by RnbWd** [comment]
[pi-hole](https://github.com/pi-hole/pi-hole) had ipv6 blocking and uses this repo as the main blocklist - and openwrt's [ablock package](https://github.com/openwrt/packages/tree/master/net/adblock/files) for routers also is ipv6 (and is nice for mobile / protecting everyone in the house. However, both libraries use dnsmasq to implement this, so it's not technically the same thing and I don't even know if ipv6 would be worth putting into a hostfile?

**Comment by smazga** [comment]
To be consistent with 0.0.0.0, shouldn't the ipv6 address be the [unspecified address](https://en.wikipedia.org/wiki/IPv6_address#Unspecified_address)?

Like:
:: googleads.g.doubleclick.net

The company here just added an ipv6 gateway, so suddenly we all have a dual-stack and the stuff started leaking through to my browser. Once I added some '::' entries those domains went away.

**Comment by StevenBlack** [comment]
So, to clarify, are you suggesting that the hosts file should additionally have a new line for ipv6?

Like:
    0.0.0.0 googleads.g.doubleclick.net
    :: googleads.g.doubleclick.net

If so, I can do that 😄

**Comment by smazga** [comment]
Yup. I tried this on a double-stack network and an ipv4 only network. It seems to work just like you think it would.

**Comment by Gitoffthelawn** [comment]
@smazga How does this relate to how AdAway handles IPv6?

What AdAway does is, for each host, creates:
`127.0.0.1 *host*`
and
`::1 *host*`

**Comment by smazga** [comment]
It's the same response as [this](https://github.com/StevenBlack/hosts#we-recommend-using-0000-instead-of-127001)

::1 is ipv6 localhost
:: is unspecified, so it doesn't conflict with a local web server

**Comment by Gitoffthelawn** [comment]
@smazga Thanks.  Have you performed any speed comparisons between `::1` and `::`?

**Comment by PromoFaux** [comment]
For what it's worth, using this list (or any others) with pi-hole, and enabling ipv6 support will automatically add in the additional lines for each domain. That said, we also strip out the IP address and replace it with the IP address of the device hosting pi-hole for the purposes of serving the block page...

**Comment by ginoledesma** [comment]
I noticed that in macOS 10.13.2 (and probably older versions, too), that if you have both IPv6 and IPv4 networking setup, apps may prefer using the IPv6 address first before falling back to IPv4.

I noticed this when I saw ads starting to pop back up despite being in the /etc/hosts file. For example:

```bash
$ dscacheutil -q host -a name banners.mellowads.com  
name: banners.mellowads.com
ipv6_address: 2400:cb00:2048:1::6811:a30c
ipv6_address: 2400:cb00:2048:1::6811:a50c
ipv6_address: 2400:cb00:2048:1::6811:a20c
ipv6_address: 2400:cb00:2048:1::6811:a60c
ipv6_address: 2400:cb00:2048:1::6811:a40c

name: banners.mellowads.com
ip_address: 0.0.0.0
```

The /etc/hosts IPv4 override for banners.mellowads.com is present, but since DNS was responding with IPv6 addresses as well, most userland apps will try to connect using the IPv6 address:

```
$ curl -s -o /dev/null -v -I http://banners.mellowads.com/ads/9F3207A7F46A.png 
*   Trying 2400:cb00:2048:1::6811:a30c...
* TCP_NODELAY set
* Connected to banners.mellowads.com (2400:cb00:2048:1::6811:a30c) port 80 (#0)
> HEAD /ads/9F3207A7F46A.png HTTP/1.1
> Host: banners.mellowads.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 05 Dec 2017 20:26:07 GMT
< Content-Type: image/png
< Content-Length: 25020
< Connection: keep-alive
< Set-Cookie: __cfduid=d7a8e040656feca616e58c1e8328987541512505567; expires=Wed, 05-Dec-18 20:26:07 GMT; path=/; domain=.mellowads.com; HttpOnly
< Cache-Control: public, max-age=2678400
< Cf-Bgj: imgq:100
< Cf-Polished: pngoptimizer, origSize=26558
< Etag: "4a5fcfc1df32d31:0"
< Last-Modified: Thu, 21 Sep 2017 13:44:33 GMT
< CF-Cache-Status: HIT
< Expires: Fri, 05 Jan 2018 20:26:07 GMT
< Accept-Ranges: bytes
< Server: cloudflare-nginx
< CF-RAY: 3c89bd1420409650-SJC
< 
* Connection #0 to host banners.mellowads.com left intact

```

**Comment by rautamiekka** [comment]
^ An IPv6 version of addresses would at least 2.2x the size of the list if combined with IPv4 ...

**Comment by ScriptTiger** [comment]
The hosts file was designed before DNS existed to manually match domain names to IPs. As the Internet evolved, the hosts file took a back seat and became more useful as an override tool to work with DNS. If your hosts file is configured to be preferred to DNS and has IPv4 and IPv6 networking enabled, the hosts file entries will take priority regardless of IP version. When your system queries a domain name and receives a response, if it has both IPv4 and IPv6 networking enabled, it will go with the first response regardless of IP version. In the case of having the hosts file preferred to DNS, the hosts file will supply that first response for available domain names, and your computer will then resolve to that responded IP address, regardless of version, as long as you have both IPv4 and IPv6 networking enabled. However, some systems are not configured to prefer hosts file entries and some systems don't have both IPv4 and IPv6 networking enabled.

If you are having issues related to this, I would search online about how to configure your individual system to meet the above requirements, preferred hosts file entries and both IPv4 and IPv6 networking enabled. If your system is for some reason not backward compatible with IPv4, try replacing 0.0.0.0 with 0:0:0:0:0:0:0:0. If that doesn't work because your system does not consider it a valid entry, you can also try your known good loopback address of ::1 (which in long form is 0:0:0:0:0:0:0:1). And if that doesn't work, you can also replace it with some other IPv6 address that can act as a "portal" for all blocked domains.

**Comment by ScriptTiger** [comment]
Since this topic seems to be tending, if you're up for a bit of light reading, these articles are pretty good and address some common problems people might have, such as needing to use zone IDs with link-local IPv6 addresses in the hosts file and little known things like that.
https://technet.microsoft.com/en-us/library/bb726995.aspx
https://technet.microsoft.com/en-us/library/bb962069.aspx

**Comment by ScriptTiger** [comment]
@StevenBlack, if this is implemented, it would be an optional feature and not the default, correct? Due to the reasons stated above, the greater majority of people would only need it in one format or the other and not both. And since the greater majority of systems are at least IPv4-capable, if not IPv6 and IPv4 backward compatible, I would be inclined to say IPv4 should still remain the sole default to keep things straightforward and simple for as many people as possible. If IPv6 were to be implemented as default, it would cause unneeded hassle for those applying the data to, say, older network gear not compatible with IPv6. In my experience, such equipment is still highly prevalent in areas where the expense to upgrade remains to be justified due to infrastructures being slow to adopt, especially in developing areas. There are even some larger brands still making network equipment that is IPv4-only, and not just for home use.

**Comment by ginoledesma** [comment]
Keeping the current behavior (generate IPv4 only) and making IPv6 generation optional makes sense.

I wouldn't necessarily say that it's IPv4 and IPv6 are mutually exclusive — many locations might have dual deployments. That's how I ran into this issue — the WiFi access point I connected to handed me out both an IPv4 and IPv6 address, and I wondered why I was seeing ads.

I agree that IPv6 deployment is minimal compared to IPv4, and will probably be the case for some time still, but a lot of places are doing IPv6 rollouts slowly but surely (e.g. conferences offering WiFi).

**Comment by StevenBlack** [comment]
@ScriptTiger @ginoledesma yeah I picture this as another variant to add to the mix.  This triples the number of hosts files generated.

* IPv4
* IPv6
* Both

I'm considering creating a server instance, with a UI and and API in front-end, and generate these for people on-demand, cached as we go, so subsequent requests for the same hosts file dishes it from cache.
