### ISSUE TITLE
myhosts and whitelist ignored by .gitignore

### ISSUE THREAD

**Issue by mattratleph** [StevenBlack/hosts#144]
The `myhosts` and `whitelist` files seem to have been originally created and checked in to the repo, so git doesn't follow the `.gitignore` file for those two files. Should those be removed from the cache and recommitted, with instructions on how to create those files if you need them? As it exists now, the README is somewhat confusing, since it states that those files aren't tracked but they technically still are.

In addition, should the `hosts` file itself be removed from the cache and added to the `.gitignore` file as well? As it exists now, if I were to add entries to the `myhosts` file, they'll end up getting committed to the base `hosts` file once it's created. You could potentially get burned by that and need to purge your fork. I've removed the `hosts` file from my fork to address that, but that now causes merge conflicts every time I pull.

**Comment by StevenBlack** [comment]
@mattratleph I keep meaning to get around to this...

**Comment by Exadra37** [comment]
@mattratleph why not solving this issue?

As it is now I can't update my hosts file from this awesome repo in a cron job, because I have a `myhosts` and `whitelist` personalized.

Removing this files as @mattratleph suggested and then have Python script handling their creation would be a good approach or another approach is providing them as sample files like  `myhosts-example` and `whitelist-example`.

I can do the PR if you want?

Thanks for the time maintaining this repo :)

**Comment by tomhoover** [comment]
@mattratleph, I've been getting around this by using `git pull --rebase --autostash` to pull changes.

**Comment by gfyoung** [comment]
Proposal:

* Rename all of those files to `[filename].example`.
* When running the Python update script, if `[filename]` does not exist in the file directory, copy over `[filename].example` to `[filename]`

Thoughts?

cc @StevenBlack

**Comment by StevenBlack** [comment]
@gfyoung I think this is a good idea.
