### ISSUE TITLE
new tracking domain

### ISSUE THREAD

**Issue by Sego1234** [StevenBlack/hosts#1444]
ads(.)servebom(.)com is the tracking domain
it is flagged as a tracker by [Privacy Badger](https://privacybadger.org/) and Firefox

Appears on [HowToGeek](https://www.howtogeek.com/)

**Comment by lightswitch05** [comment]
According to my [Blocklist tools website](https://blocklist-tools.developerdan.com/entries/search?q=ads.servebom.com), that domain has been included in the unified list since November 15, 2014- through the Winhelp2002 MVPS list. It's also been in Dan Pollock's list since March 2017. As well as the relatively new Tiuxo list since April 2019.

I'd say that domain has pretty solid coverage in this list.

**Comment by Sego1234** [comment]
sorry, i forgot to check
