### ISSUE TITLE
false positive: consent.cookiebot.com / consent.cookiebot.com.edgekey.net

### ISSUE THREAD

**Issue by beerisgood** [StevenBlack/hosts#1472]
From https://github.com/nextdns/metadata/issues/461#issuecomment-734539673:
> Please report this to Steven Black (one of our upstreams) at https://github.com/StevenBlack/hosts.
>
> It seems they are blocking consent.cookiebot.com.edgekey.net but not consent.cookiebot.com, which is weird as consent.cookiebot.com.edgekey.net is only ever a CNAME of consent.cookiebot.com.

See also https://github.com/anudeepND/blacklist/issues/132

**Comment by StevenBlack** [comment]
See #1473   I'm not going to accept one-domain issues anymore.  That doesn't scale, so it doesn't work for me.

Closing.

**Comment by beerisgood** [comment]
This doesn't work from user side and most if not all prefer issues about one domain/ problem so e.g. the search is usable.

Sad to see your move but it's your baby

**Comment by StevenBlack** [comment]
@beerisgood curation matters.

You say in #1473 `the page opened on a streaming page`.    I have no way of verifying this.  You stick this on me, and I'm supposed to block it forever because you say so?  How do I *ever* remove that domain?  This is not an add-only bucket for other people's gripes.

There are people who are set up for this.  Maintaining lists is what they do.  I maintain a list of lists.  When a curator changes their list, I review all their changes, every line, and if their change is questionable, I defer updating this list until that's sorted, or I don't include their latest update in our update.

I'm done chasing all over the internet following random leads.

everything related to `cookiebot` comes to us via AdAway — @jaws101 can you please look at this? — so this isn't even the right place to report this.

I am SO done chasing single-domain gripes, especially unsubstantiated ones.  @beerisgood I hope this makes sense to you.  Please stop polluting the issues here.
