### ISSUE TITLE
cnasolution.com adware, malware, pop up, porn

### ISSUE THREAD

**Issue by Mlocik97** [StevenBlack/hosts#1478]
please add this shit: cnasolution.com to blocklist,...

**Comment by StevenBlack** [comment]
I wend there and saw ads, but no pop-ups, pop-unders, malware, or porn.

Closing.

**Comment by Mlocik97** [comment]
https://www.reddit.com/r/softwaregore/comments/k7502g/how_to_be_fired_from_work_aka_x_mean_open_porn_or/

**Comment by StevenBlack** [comment]
@Mlocik97 I don't understand.  I don't see anything here, possibly because I'm protected.

Look, we don't block sites that run ads.  We block sites that serve the ads.  So if a site is ad-funded, no matter how annoying this may be, we don't block that site.  We block the sites that provide the ads.

Sensible?
