### ISSUE TITLE
blocked site mobile.launchdarkly.com

### ISSUE THREAD

**Issue by kauffman214** [StevenBlack/hosts#1520]
Is there a place where justification for inclusion on the list is posted?

pihole -q mobile.launchdarkly.com
 Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:
   mobile.launchdarkly.com 

Launchdarkly is typically used by legit companies to do configuration of mobile clients like A/B testing.   Have events been witnessed where it is being used for more than configuration and testing? 

I ask because my bank uses this for mobile application updates.  I do realize I can white list it, but my issue is really on, is there the "justification" is recorded?

Thanks.

**Comment by FadeMind** [comment]
Upstream > https://github.com/AdAway/adaway.github.io/issues

**Comment by StevenBlack** [comment]
@jawz101 can you please look?

@kauffman214 so we're clear, there is zero notion of "legit companies" here.  Any domain that tracks users or delivers adware or malware — many so called "legit" companies do this — are blocked here.

**Comment by StevenBlack** [comment]
Thanks @jawz101 that's a good take.

Closing.

**Comment by Spacey67** [comment]
Still an issue, can't believe that was a reasoning to whitelist. I haven't found it interfere with anything

**Comment by mstrater** [comment]
Some more info:
In combination with a bad network diagnostic check within the software, it seems to be breaking Fusion 360, at least anecdotally: https://forums.autodesk.com/t5/fusion-360-support/fusion360-not-launching-and-how-i-got-around-it/m-p/11316210#M155050
For full disclosure, I work for Autodesk.

**Comment by wwwroth** [comment]
Old thread but wanted to leave a note since this not being whitelisted caused me some grief.

If you’re troubleshooting a Miku Pro baby cam and it won’t connect to your app, it turns out it was running an old version of firmware and this DNS block was preventing it from updating automatically. After speaking to someone in their call center they manually pushed the update and my camera is working.

Not sure what other IoT devices use LaunchDarkly in their stack may be affected but it’s definitely a possibility.
