### ISSUE TITLE
Remove spclient.wg.spotify.com

### ISSUE THREAD

**Issue by PillowPhone** [StevenBlack/hosts#153]
Blocking this domain prevents searches and discover in the iOS App, and also breaks SONOS Spotify integration.

**Comment by mrkmg** [comment]
I had to whitelist this as it is still preventing many core functions of the mobile app from working.

**Comment by PillowPhone** [comment]
I did say this over 7 months ago when the issue was closed without comment.

**Comment by gromain** [comment]
Hi,
It comes from the files [here](https://github.com/StevenBlack/hosts/blob/cc05a601c98cbc404c2f0fdeaaf5943e231616cf/data/SpotifyAds/hosts#L9) which source is [there](https://github.com/FadeMind/hosts.extras) .
Maybe you can try to put it up as an issue [here](https://github.com/FadeMind/hosts.extras/issues), since this is were the host block comes from.
See issue #240 for more information regarding this kind of problems.
