### ISSUE TITLE
Amazon app blocked

### ISSUE THREAD

**Issue by Manu99it** [StevenBlack/hosts#1537]
I'm using NextDNS wich bases it's base list even on yours. The Amazon app needs the Amazon domains that start with "fls-" (on the fls- ones I'm more secure (tested someone), on the few other I don't really know):

fls-eu.amazon.ae 
fls-na.amazon.ca 
fls-cn.amazon.cn
aan.amazon.co.jp
fls-fe.amazon.co.jp  
aan.amazon.co.uk 
fls-eu.amazon.co.uk
aan.amazon.com 
aax-us-iad.amazon.com 
fls-cn.amazon.com
fls-eu.amazon.com
fls-fe.amazon.com
fls-na.amazon.com
fls-fe.amazon.com.au 
fls-na.amazon.com.br
fls-na.amazon.com.mx 
fls-eu.amazon.de (issue #1468)
fls-eu.amazon.es 
fls-eu.amazon.fr
fls-eu.amazon.in 
fls-eu.amazon.it 
fls-eu.amazon.nl  
fls-eu.amazon.sa 
fls-eu.amazon.se 
fls-fe.amazon.sg

**Comment by StevenBlack** [comment]
Hi Emanuele @Manu99it thank you very much for posting this.

All these domains come to us Via AdAway.

@jawz101 can you please assess?  Thank you, as always, for your help.

**Comment by jawz101** [comment]
https://github.com/StevenBlack/hosts/issues/1468#issuecomment-735923315

**Comment by Manu99it** [comment]
@StevenBlack @jawz101 thank you for your response. I even read that other thread, so thank you for the clarification on what these trackers do. But, what I don't get, is your position about keeping or removing them: actually I always believed that adblockers need to be useful so one should see the cost-benefit ratio. In that specific case these completely broke an app functionality that, I thought, should be a priority. Anyway I'm done with just whitelisting them, so I'll be ok for whatever option you're going to opt in

**Comment by StevenBlack** [comment]
Ya thanks @jawz101!

Here's my take, Emanuele @Manu99it: Providers make design decisions that best suit them. In this case it seems Amazon has made a value judgment to track its users like this. 

That's fine, as far as it goes.  The people we serve here don't want to be tracked, phished, traded, sold, and they want to be protected from malware.  

Is this a bummer sometimes?  Absolutely.  But we keep our promise here.  This list protects you against many forms of abhorrent behavior by companies on the internet.  Amazon doesn't get a free-pass just because it's Amazon. 

That's how I feel about it.  Many other options exist.  But I just wan to shut that shit down, know what I mean?  Maybe someday Amazon will come to its senses and protect its customers, too.

Closing.

**Comment by dnmTX** [comment]
**AMEN**  😄

**Comment by jawz101** [comment]
@Manu99it 
They don't break the app unless you click on the more sponsored-oriented things inside the Amazon app.. at least from my personal experience.  I use the Amazon app a lot and it's a slight annoyance when I see the sad dog face and if I really care I'll turn my ad blocker off for a sec- but after observing when it poops on me it's definitely tied to the items in search results that some product paid extra to give themselves priority.
