### ISSUE TITLE
Prevent or interfere with the "upgrade" installation of Windows 10?

### ISSUE THREAD

**Issue by Gitoffthelawn** [StevenBlack/hosts#154]
Will this hosts file prevent or interfere with the "upgrade" installation of Windows 10 on systems currently running Windows 7?

**Comment by StevenBlack** [comment]
I don't think so, at least, not yet.

I'm not a Windows user so perhaps others have input on this?

**Comment by Laicure** [comment]
I'll set my inputs though I'm **currently using** Windows 10, non-insider (workstation pc at work; with full admin privileges). I'm planning (not so soon) to test Win7~8.1 on a virtual environment to find out as I am interested in this prevention.
- I am using the [latest hosts](https://github.com/StevenBlack/hosts/blob/master/hosts) file (with @tyzbit 's list)
- No other active network proxies or applications

Build by Build (currently at 10586.494), Windows 10 manages to catch all updates without errors.

_I do not know if my statement above will make sense though_ :icecream:

**Comment by Gitoffthelawn** [comment]
Thanks @Laicure, but I'm not sure if that qualifies for knowing if it interferes with the "upgrade" process from Windows 7 to Windows 10.

@CHEF-KOCH Do you happen to know?  Or anyone else?

**Comment by CHEF-KOCH** [comment]
I not really understand this question because if you do an upgrade via setup.exe it not requires any internet connection, the first internet connection is required to search for updated and to look into the key database (depending which Windows version you use because different Key models). 

The last RTM (redstone) 14393.5 also ignores the hosts totally, because it uses SSL/TLS to ensure everything is secure and encrypted. Blocking the known update server or even directly several other pages will be ignored then. It's not only because MS btw, it's because Hosts generally have the secure connection weakness, that's why I'm using Adguard (of course you need to trust them because they install there own certificate to filter Metro apps and SSL traffic).

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH Thanks for the feedback.

BTW, I thought SSL/TLS normally honors hosts, no?

**Comment by berrythesoftwarecodeprogrammar** [comment]
not sure if you want to prevent it or do the opposite. but here are some resources to prevent the upgrades:
https://fix10.isleaked.com/oldwindows.html
http://ultimateoutsider.com/downloads/
http://dws.wzor.net/

the last program has the option to add these to the hosts file:
```
0.0.0.0 statsfe2.update.microsoft.com.akadns.net
0.0.0.0 fe2.update.microsoft.com.akadns.net
0.0.0.0 s0.2mdn.net
0.0.0.0 survey.watson.microsoft.com
0.0.0.0 view.atdmt.com
0.0.0.0 watson.microsoft.com
0.0.0.0 watson.ppe.telemetry.microsoft.com
0.0.0.0 vortex.data.microsoft.com
0.0.0.0 vortex-win.data.microsoft.com
0.0.0.0 telecommand.telemetry.microsoft.com
0.0.0.0 telecommand.telemetry.microsoft.com.nsatc.net
0.0.0.0 oca.telemetry.microsoft.com
0.0.0.0 sqm.telemetry.microsoft.com
0.0.0.0 sqm.telemetry.microsoft.com.nsatc.net
0.0.0.0 watson.telemetry.microsoft.com
0.0.0.0 watson.telemetry.microsoft.com.nsatc.net
0.0.0.0 redir.metaservices.microsoft.com
0.0.0.0 choice.microsoft.com
0.0.0.0 choice.microsoft.com.nsatc.net
0.0.0.0 wes.df.telemetry.microsoft.com
0.0.0.0 services.wes.df.telemetry.microsoft.com
0.0.0.0 sqm.df.telemetry.microsoft.com
0.0.0.0 telemetry.microsoft.com
0.0.0.0 telemetry.appex.bing.net
0.0.0.0 telemetry.urs.microsoft.com
0.0.0.0 settings-sandbox.data.microsoft.com
0.0.0.0 watson.live.com
0.0.0.0 statsfe2.ws.microsoft.com
0.0.0.0 corpext.msitadfs.glbdns2.microsoft.com
0.0.0.0 compatexchange.cloudapp.net
0.0.0.0 a-0001.a-msedge.net
0.0.0.0 sls.update.microsoft.com.akadns.net
0.0.0.0 diagnostics.support.microsoft.com
0.0.0.0 corp.sts.microsoft.com
0.0.0.0 statsfe1.ws.microsoft.com
0.0.0.0 feedback.windows.com
0.0.0.0 feedback.microsoft-hohm.com
0.0.0.0 feedback.search.microsoft.com
0.0.0.0 rad.msn.com
0.0.0.0 preview.msn.com
0.0.0.0 ad.doubleclick.net
0.0.0.0 ads.msn.com
0.0.0.0 ads1.msads.net
0.0.0.0 ads1.msn.com
0.0.0.0 a.ads1.msn.com
0.0.0.0 a.ads2.msn.com
0.0.0.0 adnexus.net
0.0.0.0 adnxs.com
0.0.0.0 az361816.vo.msecnd.net
0.0.0.0 az512334.vo.msecnd.net
0.0.0.0 ssw.live.com
0.0.0.0 ca.telemetry.microsoft.com
0.0.0.0 i1.services.social.microsoft.com
0.0.0.0 df.telemetry.microsoft.com
0.0.0.0 reports.wes.df.telemetry.microsoft.com
0.0.0.0 cs1.wpc.v0cdn.net
0.0.0.0 vortex-sandbox.data.microsoft.com
0.0.0.0 oca.telemetry.microsoft.com.nsatc.net
0.0.0.0 pre.footprintpredict.com
0.0.0.0 spynet2.microsoft.com
0.0.0.0 spynetalt.microsoft.com
0.0.0.0 fe3.delivery.dsp.mp.microsoft.com.nsatc.net
0.0.0.0 cache.datamart.windows.com
0.0.0.0 db3wns2011111.wns.windows.com
0.0.0.0 settings-win.data.microsoft.com
0.0.0.0 v10.vortex-win.data.microsoft.com
0.0.0.0 win10.ipv6.microsoft.com
0.0.0.0 ca.telemetry.microsoft.com
0.0.0.0 i1.services.social.microsoft.com.nsatc.net
0.0.0.0 msnbot-207-46-194-33.search.msn.com
0.0.0.0 settings.data.microsof.com
0.0.0.0 telecommand.telemetry.microsoft.com.nsatðc.net
```

(be careful with that last host on the list, @StevenBlack's script breaks on it for me because of the special character, but i've confirmed that its a real host.)

**Comment by tyzbit** [comment]
I think the proposal to block Windows 10 upgrades via the hosts file is interesting, but as a Windows user I am opposed.  I think the purpose of this project should be to block tracking, advertising, malware et al but should not make decisions about what software is allowed on a users machine past if it's outright malware.  

Windows 10 (while some may confidently assert is malware) is not malware.  It has tracking and advertising features that I think this project would do well to continue to help users block and disable, but it's a feature-filled, useful operating system that many want the option to upgrade to and run.  Microsoft has made it hard to block the upgrade at times but that, I think, is outside the scope of what we should aim to accomplish.

Additionally, the decision to block Windows 10 upgrades would also be a decision to block the security features that come with Windows 10, making users more vulnerable.

**Comment by CHEF-KOCH** [comment]
> BTW, I thought SSL/TLS normally honors hosts, no?

No you can try yourself with e.g. <code>ssl.google-analytics.com</code>. it will not get blocked, there are also stuff which never get blocked, liek telemetry because the internal firewall or hosts not respect e.g. dnsapi.dll which includes the telemetry thingy (or some of them) which makes blocking telemetry pointless anyway. I wrote about this long time ago but no one want to help me with that, if I would get each new .dll files from every windows update I could provide something but so you have to block this in your router .... (sadly). 

Windows 10 is not malware, inf act there exist most strongest security out of the boy, the problem is the app developer needs to support it (mostly simply compiler flag changes like cf-guard). Another thing there exist a lot of myths, starting with telemetry, there is no telemetry out of the box, the toggles you can do on first installation setup exist since the first day, you simply need one click more to go to the advance setup, that's all. The only telemetry you see then (even after uncheck everything) is the same like in 7, it's coming from the task scheduler which creates an service to send OS information like hardware setup back) after each update and regularly so that MS can pick it up, I never found critical information in this (so telemetry != spying like people always say). On the other side I understand that it should be more transparent because opt-out means (for me opt-out) but I guess it will be changed, especially because EU people complaining about this. But besides this you usually not see any connections to the mentioned hosts entries. The only stuff I can see is that Enterprise <-> Pro/preview get less/more connections (but again highly depending on which settings you use) Cortana is known to collect everything. 

You should also know that no one ever found something on Windows, it's constantly monitored and I only heard stuff without any proof.

**Comment by StevenBlack** [comment]
@tyzbit great comment.  I'm now thinking that Windows Update hosts entries could be an (Extension)[https://github.com/StevenBlack/hosts/tree/master/extensions].

Is that sensible, in your view?

**Comment by StevenBlack** [comment]
@CHEF-KOCH Thanks for that.  I agree with everything you've written here.

If we made this facet an [Extension](https://github.com/StevenBlack/hosts/tree/master/extensions) then those who don't trust MS could chose this build option, or download that amalgamated build.

**Comment by berrythesoftwarecodeprogrammar** [comment]
i think someone would have to first figure out which of the hosts are used for tracking/telemetry/ads/etc and which ones are 'harmless' and only used for windows update. it may not be easy. i havent seen any lists specifically for stopping windows update. only those which both stop windows 10 upgrades and stop what they report as spying

**Comment by tyzbit** [comment]
@StevenBlack With the free Windows 10 upgrade period behind us, it might be too late to be of use, but I think an extension would be the perfect place for something like this.

**Comment by Acecool** [comment]
I had this hosts file installed on my laptop ( which I use to test new builds ) and used the free upgrade in order to calculate the Windows key to use during a fresh install ( but then they allowed Windows 7 key to be used ) and it went flawlessly.

About Windows 10 being the most secure, I'll beg to differ as long as IE is included because of all of the passive / background backdoors it keeps open even when it isn't "open"... I've used countless operating systems and have used Windows 7 x64 Pro as my primary operating system for 8 or so years without ever being infected with a virus of any kind ( I take precautions and in the event something does happen I can easily remove them ). With Windows 10, I left IE on the computer despite normally removing it, and a drive-by download ( an unwanted download which is served randomly by advertisements which also has code to prevent going to the same pc more than once which makes it next to impossible for the website serving the ads to track who sent it - one of the reasons I don't allow 3rd party code to run on any of my sites and any ads must be pre-approved by myself with the limit being an image served by my own site to prevent scripts generating the file, etc... ) or worm-payload ( scanning via ips to see if backdoors are available then delivering an application or something to be installed without the users permission ) infected my pc ( "DNS Unlocker" - green leaf in tray and it alters your dns settings for the network connections and in your browser so it can add ads to any data that is transferred through them ) even though I was using chrome with uMatrix ( blocks 3rd party scripts from running by default - also use blacklists available ), Adblock plus, this hosts file, etc... I revisited the entire history of what I visited, after uninstalling IE, and nothing loaded that shouldn't load so the only thing it leaves me to believe the issue is with IE...

I didn't install anything new; all downloads were from trusted providers and everything I did install I checked again by reinstalling to ensure it didn't piggyback and the files came up clean... IE causes countless issues and haven't had an issue since removing it...

**Comment by Gitoffthelawn** [comment]
I wrote:
> BTW, I thought SSL/TLS normally honors hosts, no?

@CHEF-KOCH wrote:
> Nope, you can try yourself with e.g. `ssl.google-analytics.com`. it will not get blocked...

I performed some testing, and I get the opposite results.

I added `google.com`, `twitter.com`, `facebook.com`, and `advertising.com` to *hosts*, all of which are served via SSL/TLS.  They all get blocked (and I think I will leave them blocked).

Not sure why you are getting a different result.  Can you try again and see what result you get?  Perhaps you were seeing cached pages.

**Comment by CHEF-KOCH** [comment]
It is fixed now since 2 patchdays after I submit a patch to MS which affected their DNS system. Also some nslookup issue are also solved.

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH What is fixed?  What patch was published?  What is the MSKB number?

**Comment by CHEF-KOCH** [comment]
[KB3176937](http://ms-vnext.net/UpdateArchive/) [includes several other KB's aswell] (win 10) 7/8 got same changes (just different KB names).

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH Thanks.  So Windows ignored the ***hosts*** file for HTTPS until the second half of 2016, but now honors ***hosts*** for HTTPS?  Is that correct?
