### ISSUE TITLE
[whitelist]tealium.cbsnews.com - bidbarrel.cbsnews.com

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1543]
this domain are necessary for cbs livestram ->

source ->
https://www.cbsnews.com/live/

Reference ->
https://github.com/nextdns/metadata/issues/574

**Comment by StevenBlack** [comment]
Hi Lorenzo @scafroglia93 the domain `tealium.cbsnews.com` is upstream at yoyo.org.

Can you please submit your case for this to pgl@yoyo.org.  Ping Peter @pgl.

**Comment by pgl** [comment]
Thanks for the ping @StevenBlack.

@scafroglia93, as per my email:

Both of these domains are primarily used for serving ads and tracking users, so I'm afraid I won't be removing them.

If they're breaking sites, then I encourage you to contact the site owners and ask that they don't rely on remote trackings scripts to be loaded in order to function correctly.

Or you can whitelist the domains locally, if you're OK with them tracking you.

**Comment by StevenBlack** [comment]
Thanks Peter @pgl.

Closing.
