### ISSUE TITLE
concierge.analytics.console.aws.a2z.com blocked

### ISSUE THREAD

**Issue by AdrianSimionov** [StevenBlack/hosts#1550]
AWS recently introduced a new Console feature which allows you to search for products and rapidly which from one service to another.

The dynamic search is done against _concierge.analytics.console.aws.a2z.com_ and by blocking the URL the feature of the AWS console breaks.

I had to temporarily add the CNAME to whitelist but it should not be blocked by any means as it blocks a fundamental feature of the AWS Console.

**Comment by dnmTX** [comment]
Ping @jawz101
I'm guessing(more like certain) that NextDNS is involved and the mentioned domain is not listed here but the closest is `analytics.console.aws.a2z.com` so if you don't mind inspect and don't remove if doesn't need to.
The problem is purely downstream and it's about time all those NextDNS users to start addressing that uncontrolled wildcard blocking with the developers there and not here.

**Comment by AdrianSimionov** [comment]
Forgot to mention I am experiencing the issue on Pi-Hole.
