### ISSUE TITLE
magiskmanager.com is blocked

### ISSUE THREAD

**Issue by clavinet** [StevenBlack/hosts#1557]
I don't know why magiskmanager.com would be blocked, it seems like just an info site.
Their download page doesn't even host anything but links to github (under "click here"):

https://magiskmanager.com/downloading-magisk-manager

**Comment by StevenBlack** [comment]
Hi @clavinet this comes from upstream from our `KADhosts` provider.  You can [submit this issue here](https://github.com/PolishFiltersTeam/KADhosts/issues).

Krystian @krystian3w what do you think?

@clavinet please note that whether something "*seems like just an info site*" means nothing.  What are they doing, behind the scenes, and under the hood?  Obviously this is not detectable by just looking at a web page.

**Comment by krystian3w** [comment]
I found this: https://github.com/PolishFiltersTeam/KAD/commit/9dfd9a39dba47e4b0067e7edd50aa236a13eab12

https://github.com/PolishFiltersTeam/KAD/issues/739 - https://www.xda-developers.com/psa-magiskmanager-com-not-official-website-magisk/

So blocked for hard/many adverts on page in the past. I agree to revert blockade.

**Comment by StevenBlack** [comment]
Thanks Krystian @krystian3w.

@clavinet this will be updated in the next release.

Closing.

**Comment by clavinet** [comment]
That XDA article might be outdated (3 years old), it says that magiskmanager.com hosts its own files, but like I said above I couldn't find any self-hosted binaries, only links to official github sites and the twrp.me site.

> So blocked for hard/many adverts on page in the past. I agree to revert blockade.
Is having many ads a reason to block the site itself? Shouldn't it be the job of a browser and/or DNS-based adblocker to filter those?
