### ISSUE TITLE
hpHosts - Updated Daily, Individual Classifications Totaling Over 400K Hosts!!

### ISSUE THREAD

**Issue by kklouzal** [StevenBlack/hosts#159]
https://hosts-file.net/ otherwise known as hpHosts is home to a database of over 400 thousand hosts categorized into 11 different groups most notably of which includes Ad/Tracking Servers, Malware Sites, Fraud/Phishing Sites, etc..

**I strongly urge the maintainer to consider including some, if not all of the following, in this repo:**
Ad/Tracking - https://hosts-file.net/ad_servers.txt
Malware - https://hosts-file.net/emd.txt
Exploits - https://hosts-file.net/exp.txt
Fraud - https://hosts-file.net/fsa.txt
Hijack - https://hosts-file.net/hjk.txt
Phishing - https://hosts-file.net/psh.txt

At the time of this post, this repository has 18,687 unique entries after amalgamating it into the previous 6 lists. That leaves us with a combined total of 419,507 unique entries.

**Comment by StevenBlack** [comment]
Hi @kklouzal thank you for your comment.

Please see [Goals of this unified hosts file](https://github.com/StevenBlack/hosts#goals-of-this-unified-hosts-file).

I decided https://hosts-file.net/  doesn't qualify because its level of curation is very low relative to its size.  At that time, https://hosts-file.net/ had 360k entries.  A huge hosts file creates its own issues on mobile, and on some Windows systems.

 In my view, quality trumps quantity.  

So by default this repo doesn't include https://hosts-file.net/ but it is very easy to add, as you know.

**Comment by aureq** [comment]
To chime in, `https://hosts-file.net/psh.txt` is currently blocking twitter profile images `pbs.twimg.com` and it's categorized as phishing. Not worth using.

**Comment by schlaubstar** [comment]
As HPhosts is not available anymore and the service has been stopped, according to statements from malwarebytes: Has anyone good alternatives ?

**Comment by vinothvkr** [comment]
> 
> 
> As HPhosts is not available anymore and the service has been stopped, according to statements from malwarebytes: Has anyone good alternatives ?

An alternative is needed.

**Comment by MrWaste** [comment]
The lists are still right here :)
https://github.com/MrWaste/Malwarebytes-hpHosts-Full-Lists

**Comment by nijazm** [comment]
Or in web archive, original. Here is last explanation (dates in explanation are not correct for files, because files archived may be newer or older in archive, instead look at url to see date when it was fetched): https://web.archive.org/web/20191231184932/https://hosts-file.net/?s=Download

Each list newest hosts file that exists:
https://web.archive.org/web/20200308144426if_/http://hosts-file.net/ad_servers.txt
https://web.archive.org/web/20191001083500if_/http://hosts-file.net:80/emd.txt
https://web.archive.org/web/20200103151313if_/https://hosts-file.net/fsa.txt
https://web.archive.org/web/20200304014202if_/https://hosts-file.net/grm.txt
https://web.archive.org/web/20190529182231if_/https://hosts-file.net/hfs.txt
https://web.archive.org/web/20190529182230if_/https://hosts-file.net/hjk.txt
https://web.archive.org/web/20200103123932if_/https://hosts-file.net/mmt.txt
https://web.archive.org/web/20190529182229if_/https://hosts-file.net/pha.txt
https://web.archive.org/web/20200103123825if_/https://hosts-file.net/psh.txt
https://web.archive.org/web/20200103123746if_/https://hosts-file.net/pup.txt
https://web.archive.org/web/20190529182228if_/https://hosts-file.net/wrz.txt
