### ISSUE TITLE
this adnetwork is basically on most porn sites

### ISSUE THREAD

**Issue by ghost** [StevenBlack/hosts#1664]
```
0.0.0.0 freshmarketer.com
0.0.0.0 cdn.luckyorange.com
0.0.0.0 w1.luckyorange.com
0.0.0.0 extmaps-api.yandex.net
0.0.0.0 syndication.realsrv.com
0.0.0.0 a.realsrv.com
0.0.0.0 ads.realsrv.com
```
**Luckyorange** - Website analytics, heatmaps (like hotjar)
**realsrv** - many of the porn websites load ads from these domains, *especially* the syndication domain, and these ads thubmnails sometimes displays extreme stuff, etc
**freshmarketer** - Marketing suite - [this website](https://support.freshchat.com/support/solutions/articles/238233-list-of-domains-and-ips-to-allow-to-start-using-freshchat) lists it needs to allow that domain to even function. We need look into that before adding it

**Comment by StevenBlack** [comment]
Thanks for these Nainar @bnainar.

Ping @sinfonietta  will you list these?

**Comment by llacb47** [comment]
If it's an adnetwork, it should go to the ad-hoc list, right?

**Comment by StevenBlack** [comment]
That's a fair point LE @llacb47.  Thanks.

**Comment by StevenBlack** [comment]
Hey Peter @pgl I notice you carry domains related to `realsrv.com` and `yandex.net` already, which are four of the seven domains suggested above by Nainar @bnainar.

Would you carry these domains in your list?

**Comment by bnainar** [comment]
[this website](https://support.freshchat.com/support/solutions/articles/238233-list-of-domains-and-ips-to-allow-to-start-using-freshchat) lists it needs to allow freshmarketer to even function. We need look into that before adding it.

I got luckyorange and freshmarketer domain from here https://d3ward.github.io/toolz/src/adblock.html (@d3ward) and it also lists similar domains, we can refer that

**Comment by pgl** [comment]
@StevenBlack Thanks for the heads up. I've added `luckyorange.com` to my list:

 * https://pgl.yoyo.org/adservers/details.php?hostname=luckyorange.com

From the massive banner on their homepage, seems very clear that they're a tracker.
![image](https://user-images.githubusercontent.com/1181139/119317284-37036980-bc78-11eb-839f-af290e42f5a0.png)

I was contacted by Freshworks last year, they complained because I had the parent domain on my list. I replaced it with `cdn.freshmarketer.com` which they assured me was sufficient to block tracking:

 * https://pgl.yoyo.org/adservers/details.php?hostname=cdn.freshmarketer.com

This was updated Mon Jul 27th 2020 20:55, but I've just reset the timestamp because I added a note.

I don't think they know how GDPR works though:

![image](https://user-images.githubusercontent.com/1181139/119317677-a5e0c280-bc78-11eb-874e-e649adbc3de1.png)

Anyway, just checked their site and saw that some other domains are being contacted, so I've re-added `freshworks.com`:

 * https://pgl.yoyo.org/adservers/details.php?hostname=freshworks.com

**Comment by StevenBlack** [comment]
Thanks Peter @pgl!
