### ISSUE TITLE
Blocking braze breaks an email list sign-up page

### ISSUE THREAD

**Issue by mezz** [StevenBlack/hosts#1684]
I use a pihole to block ads, and it uses this hosts list. 
With the pihole active, I can't seem to use this website to sign up for the email list:
https://transformersheavymetal.com/

The form submission fails, and I see some POST to blaze failed in the console.

I am guessing the blocklist is a bit too strict and breaks this. Thanks for any info.

**Comment by dnmTX** [comment]
@mezz post here the domain(s) from the console log please.

**Comment by mezz** [comment]
My client attempts to POST to 
`https://sdk.iad-06.braze.com/api/v3/data/`

**Comment by dnmTX** [comment]
@jawz101 it's one of yours,you mind  look in to it. Thanks(as allways) 👍

**Comment by jawz101** [comment]
It's all about audience engagement/segmentation... all of the stuff that is tracking.  And shows up often in Android app traffic.  Leaving for now and users can whitelist as necessary.

**Comment by mezz** [comment]
This is a form I willingly submit, I didn't realize this project was so hardline on tracking. I use this as a pihole blacklist. For more fine-grained anti-tracking I disable JavaScript and many other things in my browser, where I have an easier time controlling it manually.

Do you have any recommendations for an ad-blocking list that only blocks ads and invisible trackers? That is what I believe I need at the router DNS level, for my mobile devices, game consoles, and for my family to use conveniently. Thanks.

**Comment by jawz101** [comment]
I understand.  If this was a common problem with many people, I would reconsider, but it's one isolated instance on one website doing one thing so far.  Otherwise, Braze https://www.braze.com/ (formerly Appboy) is [a tracker](https://reports.exodus-privacy.eu.org/en/trackers/17/) (I created this ad signature in Exodus Privacy Project [a few years ago](https://etip.exodus-privacy.eu.org/trackers/a95be555-9324-4fac-b0b8-4d1146d88a52/).

I would say you consented to sign up to a concert site- much like everything you and we do online- and clicked on I agree on the fine print.  But then we choose to block ads and trackers.  The problem I see is that one site tied a sign up screen into a 3rd party marketing product either intentionally or unintentionally to break if blocked.  I consider that rare. Otherwise, that particular/random subdomain makes our devices so chatty on the network that it is the (gasp) 4463rd most looked up DNS lookup out of the top million domain lookups on [Cisco's Top 1 Million](http://s3-us-west-1.amazonaws.com/umbrella-static/index.html) DNS lookups for today.  That's like if you have the ESPN, Disney+, Dashlane password manager, or NBA mobile app, your phone is constantly giving them data to log your behaviors.  Based on its rank, it's checked more often than people watch videos on Facebook, visit target.com, most time servers are checked, antivirus updates are checked.... all sorts of stuff.

I remove a lot and I'd remove this one if the scales tipped the wrong way too much but it doesn't right now.  That's why pi-holehas a whitelist.  I whitelist a few things I want that some blocklists try to block.  And Steven Black's list is very reliable so I personally wouldn't want to make it look bad.  But, this is one of those I think is not worth opening up for the sake of the thousands and millions of times our devices want to try and phone home to them without us aware.

**Comment by mezz** [comment]
I recognize there is a trade off here, but this is not the stance I expected from this list because I thought of it as a safe default for everyone. If possible, I would like to find a similar list that prioritizes convenience. I mainly just want to block ads, and it would be nice to block tracking in cases where it is very unlikely to impact anyone's experience. Please let me know if there is a good place to look. Thanks!

**Comment by jawz101** [comment]
Certainly.
If you notice, StevenBlack is a list of lists.  If you look at the main page
https://github.com/StevenBlack/hosts

Under
"Sources of hosts data unified in this variant"

It Iists each source list individually along with links to each.  If you add each except for the AdAway list it'll omit AdAway's entries and, consequently, this braze one.

Other sources might be found on filterlists.com.  it has just about every list out there but many of them are combo lists and many will have AdAway entries.

If you're looking for original lists, I'd suggest Steven Black's source lists, specifically MVPS, Dan Pollock/someonewhocares, Peter Lowe's (should be on that filter list site, and AdGuard DNS list.

On that filterlist site, any with the pi-hole logo are host file format should work with pi-hole.  There are tons of crappy lists on there- some block everything but the kitchen sink.  The ones I suggested above are the most reliable, effective, and original that I've found.

**Comment by dnmTX** [comment]
> There are tons of crappy lists on there- some block everything but the kitchen sink.

I do like how you described it ☝️  😄

**Comment by jawz101** [comment]
Well some will block facebook, foxnews because they want to call it fake news... you get the idea.  I've added a ton and see what all they block and many are just goofy.

**Comment by dnmTX** [comment]
> It's all about audience engagement/segmentation... all of the stuff that is tracking. And shows up often in Android app traffic. Leaving for now and users can whitelist as necessary.

Steve @StevenBlack this one is `wontfix` and can be closed.
