### ISSUE TITLE
Block: video-akp-cdn-spotify-com.akamaized.net

### ISSUE THREAD

**Issue by specter78** [StevenBlack/hosts#1706]
This domain is used to serve video ads in Spotify app.

**Comment by dnmTX** [comment]
....and at the same time it could be used to deliver the video feed !!!! 
There are spotify blocklist here in GitHub that you can use on your own risk and inconvenience.
Spotify domains have no place here !!!!

**Comment by StevenBlack** [comment]
Hi @specter78 thank you for this.

Spotify is tricky because they have a web client, an iOS client, an Android client, and integrations with Sonos and probably others.  Spotify is a huge cluster.  

In the past when we've onboarded a Spotify domain or Spotify list, we get flooded with complaints that this breaks something somewhere for somebody.  It just never ends.

I'm happy with what we are blocking now from Spotify, and anything above that is just not worth the potential grief.

Closing.
