### ISSUE TITLE
Create another list to block all email services

### ISSUE THREAD

**Issue by aasimenator** [StevenBlack/hosts#1737]
Hi,

Your list is a godsend for us and we have started using most of the list on our pfSense extension. One thing I would like to request is that if it's possible to create and maintain another list for 3rd party email domains. like (Gmail, Outlook, Yahoo) etc so that companies like us who would like to prevent anyone from accessing personal email on the company network be blocked from doing so?

Appreciate it!

**Comment by StevenBlack** [comment]
Thanks @aasimenator this is an interesting idea.

What does everyone think?

**Comment by rautamiekka** [comment]
Why not. It's a dick move on a company's part, no doubt.

**Comment by aasimenator** [comment]
@rautamiekka  lol, well it's not that we don't want people to access these sites on our network. 
We actually want to prevent the company's intellectual property from being leaked or sent out to other people, as you know security is everything, and blocking 3rd party email sites will give us the data protection we need. users can still use company email, and they can still send out files to people outside the network but we already monitor that sort of a thing on a regular basis.

**Comment by dnmTX** [comment]
I bet you installed cameras in the ladies bathroom. Better safe then sorry,right???

**Comment by StevenBlack** [comment]
C'mon guys, wtf??

This is standard ops in many companies.￼

Can we stick to the merits of the proposal, and refrain from being assholes? Thank you.￼￼

**Comment by lightswitch05** [comment]
Interesting idea, I suppose any user of the list would have to whitelist whatever 'their' service is, like `office.com`. 

Then there is the question about email servers, like pop.example.com.... those are pretty much every website, so I'm not sure that would be a reasonable thing to block using a hosts format.

Interesting idea for a list, not one I'd want to take on, but interesting.

**Comment by aasimenator** [comment]
@StevenBlack Maybe this will make your work easier? 

https://gist.github.com/Artistan/9662757

We only want to prevent free sites. paid one or private ones are fine and technically I don't think we can block private ones because that would be too broad of a list to create, manage and maintain, but if we can block all "signup and use mail domains" like Gmail or Yahoo or outlook.com etc. we should be fine. if it's a private server it's very easy to trace them based on the domain. for free ones, anyone can use any random name and we wouldn't be able to trace who created it.

btw to all the haters, we are a Finance Tech company, and even though leaks of our company document on to the internet is not a concern because normal people will not be able to interpret our documents, but leaks of our company documents in our competitor's hands is a big no we, therefore, would like to prevent that at all cost, because its worth millions and would probably kill the company if it leaks.

**Comment by StevenBlack** [comment]
Thanks @aasimenator.

You know this project is extensible, yes?  Just add a folder under `./data`, add an `update.json` file using any already here as models, and run the python script provided.

That way you can achieve your goals without saddling us with maintaining this use case forever.

Please don't misunderstand; it's an interesting idea.  

Why don't you test-drive and refine this in your user space, and report-back in a few months on how it's going?

**Comment by pradorocchi** [comment]
Hi.. 
I think it is valid to mention, to consider.. the new "private relay" service which Apple launched this year for iOS and MacOS, which redirects the exactly e-mail traffic you mentioned, to a VPN service of Apple, to be filtered.

I am not trying to tell to use it.. and even I have not tried yet and I am not interested on using the Apple service hahaah..

The purpose of my message here, is to tell about this Apple Service, which we all must consider when testing the filter you have proposed. Just to make sure to understand some [possible] situation where the Apple device may [or not] bypass the hosts and try to use a DNS service of its own, since the service tunnels all email traffic to their filters..

As I told, I have not used it [the apple service] to tell more about it. But please consider and remember about it when testing the DNS Block list on pfSense using machines and mobile devices inside your company local network. 

Yes, it seems Apple does have such list which may be very similar of your proposal. 
Which gives us 3 certainties:


1) Apple is [trying to/going to] earn money on a very similar filter ideia (currently it gives IP anonymity [as a paid service] but does not block [yet].. 
2) Apple for sure does have such e-mail providers [DNS list that] we are talking about [to make] here, but Apple will never open it.. Lol. 
3) your proposal/idea is interesting and valid, and it goes beyond Apples first step towards that direction.


The ideia/suggestion/conception is a valid path.

**Comment by aasimenator** [comment]
@StevenBlack 
I created the list here: https://github.com/aasimenator/DNSBL_EmailDomains/blob/main/hosts
I've added both in our company pfSense firewall. but while your lists are working fine, mine is not. can you have a quick look at the list and see if I am doing something incorrectly in that file?
![image](https://user-images.githubusercontent.com/49643079/133608413-c57d5fb4-c6ff-4a8f-992b-4d0935bb8e9f.png)

**Comment by StevenBlack** [comment]
@aasimenator Some lines are not valid hosts entries because of the leading dot.  Like these, for example:

https://github.com/aasimenator/DNSBL_EmailDomains/blob/646933305987804a7ac05746b3a7f41f217f1d63/hosts#L21-L23

**Comment by StevenBlack** [comment]
@aasimenator I was thinking an email block list might be 37 lines? Or 375 lines? Not (certainly never) 3,755 lines.

Closer to 37 is an appropriate number, in my mind.

**Comment by StevenBlack** [comment]
We won't be doing this one.  Closing.
