### ISSUE TITLE
Blocker fails when searching on google because of the redirect link

### ISSUE THREAD

**Issue by defa02005** [StevenBlack/hosts#1738]
If you perform a google search for one of the blocked sites, or it shows up there accidentally in one of the searches, the site will still open up, although visually broken because of the subcomponent blocking. 

For example searching a porn site like PornHub by name and then clicking on the first link in google search opens up the site. 

It may be possible to still block the sites by using a redirect prefix or something, but I'm not exactly sure how.

**Comment by StevenBlack** [comment]
Thank you for this @defa02005.

I'm on a Mac with our default hosts file, and I can access Pornhub.

I run the following bash script to download latest hosts with the porn hosts extensions

```
[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
curl "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts" | sudo tee /private/etc/hosts
sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder
```

When I run this, I can't access PornHub anymore.  This is an immediate effect, because I explicitly flush cache in the script.

I then search Pornhub in Google. following your steps.  I can't access Pornhub.

**Therefore** maybe you have `pornhub.com` domains in your DNS or browser caches?

**Comment by defa02005** [comment]
It's strange since I always use incognito on chrome(the extension is enabled in incognito), so I don't think that's possible.

I'm on a corp laptop. I think that is the reason for this behaviour. Closing this bug. Thanks for looking into this, and for the hostlist in general.
