### ISSUE TITLE
Block de-config.sensic.net

### ISSUE THREAD

**Issue by KommX** [StevenBlack/hosts#1755]
On German news site https://www.tagesschau.de/ I have seen connections to the tracker domain `de-config.sensic.net` which should be included in the blocklist.

**Comment by StevenBlack** [comment]
Thank you for this @KommX.

Dan Pollock, one of the curators we follow, already blocks `config.sensic.net`.  You can email him at hosts@someonewhocares.org and ask him to carry `de-config.sensic.net`.

This is the route I recommend because it's good to redirect to curators who are categorical, like watching a particular root domain.

Closing.
