### ISSUE TITLE
consider blocking discord-app.net

### ISSUE THREAD

**Issue by lisbonjoker** [StevenBlack/hosts#1764]
It's a scam website being thrown around pretending to be giving discord nitro with steam only to steal people's Steam and Discord accounts.

**Comment by Github-User-632345** [comment]
Here is more of the exact same scam I have on my list

I don't know how many of these are dead links because I don't visit them (why would I)

0.0.0.0 dlscord.gifts
0.0.0.0 dlscord.gift
0.0.0.0 dlscord.blog
0.0.0.0 dlscord.ru
0.0.0.0 dlscord.com
0.0.0.0 d1scord.ru
0.0.0.0 dlscord.help
0.0.0.0 dlscord.xyz
0.0.0.0 dlscord.zyx
0.0.0.0 dlscord.shop
0.0.0.0 dlscord.org
0.0.0.0 dlscord.wtf
0.0.0.0 discorcl.link
0.0.0.0 dirscod.com
0.0.0.0 dirscodapp.com
0.0.0.0 dirscod-app.com
0.0.0.0 dirscod.net
0.0.0.0 discord-nltro.com
0.0.0.0 dlscord-claim.com
0.0.0.0 discorcl.click
0.0.0.0 discordapp.one
0.0.0.0 discordapps.gift
0.0.0.0 dlscord-app.com
0.0.0.0 discord-app.com
0.0.0.0 discord-airdrop.com
0.0.0.0 dlscord-nitro.link
0.0.0.0 discord-bugs.com
0.0.0.0 discord-controls.com
0.0.0.0 discord-growth.com
0.0.0.0 disord.fun
0.0.0.0 discordnitrogift.ru
0.0.0.0 discrod-app.com
0.0.0.0 discrod-app.ru
0.0.0.0 discrod-app.link
0.0.0.0 discordapp.click
0.0.0.0 discord.gift
0.0.0.0 discord-app.net
0.0.0.0 discord-give.com
0.0.0.0 discordgifts.xyz
0.0.0.0 dlscordgifts.xyz
0.0.0.0 dlscordglfts.xyz
0.0.0.0 discordglfts.xyz
0.0.0.0 steamdiscord.com
0.0.0.0 steamdlscord.com
0.0.0.0 discordsteam.com
0.0.0.0 dlscordsteam.com

**Comment by noobiangodd** [comment]
discord.gift is a legit domain

**Comment by StevenBlack** [comment]
@Github-User-632345 you have `discord.com` in the list ⬆️ there.

**Comment by Github-User-632345** [comment]
That is an L not an i, scammers often change the i to an L to scam with fake links.
