### ISSUE TITLE
Add script to generate dnsmasq.conf?

### ISSUE THREAD

**Issue by SmartBoy84** [StevenBlack/hosts#1787]
I've made a small js script to generate a dnsmasq.conf for me and it's working well.
I've verified that all the entries were able to get through by comparing the final array length to the one specific in the README, though I did have to manually erase a commented block of text (iirc "Apache bad boys").

Make this could be generalized and added to the repo?

``console.log(hostString.split("\n").filter(a => a[0] == "0").map(a => `address=/${a.slice(0, a.indexOf("#")).replaceAll(" ", "").replaceAll("0.0.0.0", "").replaceAll("www.", "")}/0.0.0.0`).join("\n"))``

I then just pipe the output to a file named "dnsmasq.conf" ``node gen.js >> dnsmasq.conf``
Anyways, thanks for this!

**Comment by StevenBlack** [comment]
Thank you for the interesting suggestion @SmartBoy84 but I decline to act on this because DNSMask is a completely different kettle of fish.

More to the point though: run the ⬆️⬆️ script once, great.  Run it a second time, oops.  It's not re-entrant.

Correct me if I'm wrong, and this might be platform dependent: doesn't DNSMask read the local hosts file anyways?  I don't know.  I'm asking.

**Comment by StevenBlack** [comment]
@SmartBoy84 we won't be doing this.  Thank you for the suggestion.
