### ISSUE TITLE
[False Positive] gpm.samsungqbe.com

### ISSUE THREAD

**Issue by ObsessedHacker** [StevenBlack/hosts#1790]
I own two Samsung Smart TVs from 2020.
Whenever I use the Samsung TVs to search for Software Updates, I encounter errors.
I can't remember exactly, but I think it was "HTTP 403".

After some debugging, I found out the cause of the error is that Pi-Hole (Specifically: StevenBlack hosts) is blocking the following link:
gpm.samsungqbe.com

To solve this issue, I added this link to the whitelist.

**Comment by pgl** [comment]
@ObsessedHacker Thanks for the report, and thanks to @StevenBlack for flagging it. It seems that this specific domain may be used for updates rather than just tracking, so I've removed it from my list. It was originally added on November 11th after checking into it. Some pages that mention it:

 * https://www.sandeepsidhu.com/posts/getting-rid-of-ads-on-samsung-smarttv/
 * https://phyks.me/2017/12/stop-networking-dear-samsung-tv.html

It's not on my list anymore though.
