### ISSUE TITLE
Sponsor links on the repo landing page

### ISSUE THREAD

**Issue by StevenBlack** [StevenBlack/hosts#1825]
I've added sponsor links to the landing page. Github allows up to four links to go there.  

I've included the top-two contributors who are sponsorable, Nissar @funilrys and @XhmikosR.

Dan @dnmTX if you make yourself sponsorable in your Github profile, I'll add your name to the roll.  @FadeMind and @gfyoung make yourselves sponsorable and I'll include you too.

I'm thinking of rotating top contributors in the list of four...

**Comment by dnmTX** [comment]
> Dan @dnmTX if you make yourself sponsorable in your Github profile, I'll add your name to the roll.

No need, I'm not here for the money or for anything alike but thanks for thinking of me though 👍 ❤️

**Comment by gfyoung** [comment]
I'm in the same camp as @dnmTX, but I appreciate the offer @StevenBlack 👍

**Comment by XhmikosR** [comment]
Hey, @StevenBlack!

Thanks for the thought, I really appreciate it!

That being said, I don't think I should be included:

1. I contribute to projects I use and find valuable, because I believe in Open Source, not because of money
2. My contributions here are not that important; you do most of the hard work of maintaining this project
