### ISSUE TITLE
[porn] georgian cert blocklist

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1845]
Source -> 
http://blacklists.cert.gov.ge/domains_nsfw.txt

**Comment by StevenBlack** [comment]
Hi Lorenzo @scafroglia93 this is a massive porn list. I've give it quite awhile to download and it's still downloading. Then, my browser crashes.

The introduction [here](https://www.trusted-introducer.org/directory/teams/cert-ge.html) explicitly says:

> This information is provided without guarantee or pro-active maintenance.

We require active curation from all our list curators. I feel that's what makes this list special. It's dynamic and alive. 

Maybe @sinfonietta wants to look at this and consider carrying it?  I decline because maintaining porn lists isn't what we do here.

Closing.
