### ISSUE TITLE
Using hostfile made logins impossible on Windows 10

### ISSUE THREAD

**Issue by Metalhead33** [StevenBlack/hosts#1853]
I attempted to use the [**Unified hosts + fakenews + gambling + porn**](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts) variant on a corporate Windows 10 machine, but the end result was me being stuck on the Welcome screen. Every 10 minutes, I attempted to reboot the computer to see if it would fix it, until I finally logged into Safe Mode, and restored my original - much smaller - hostfile, which fixed the issue, allowing me to finally log in normally.

It seems to me, that something about the big hosts file was causing some major issues, preventing Windows 10 from logging me in. Yes, I use an account that belongs to a corporate domain, but it wasn't on the blocked list. Without network access - that is, in Safe Mode - I could log in without any issues.

I'm not entirely sure about the connection between the hosts file and the login system, and would rather not spend more time or risk investigating this issue on a corporate laptop that officially isn't even my property, but figured I'd leave this issue here as a warning to other people with a Windows device, or people trying to use this on a corporate computer.

Otherwise, the hosts file works perfectly on my personal Linux desktop computer, and my Android phone.

**Comment by StevenBlack** [comment]
Köszönöm for this @Metalhead33.

I'm going to label this with `need broader input` and hopefully a Windows user, or a Microsoft-knowledgeable person, can offer insight.

Microsoft Windows is just crazy 🙃.

**Comment by Lateralus138** [comment]
May I ask exactly what you mean by `stuck`? Do you mean you've tried logging in and it denies you, black/no screen, or no UI?

Please excuse me if I tell you something you already know, but I'm just going to go over some of things I know in order to help.

I have been a Dual booter for 20 years and in Windows 25+ and the only issues I've ever had with messing with the HOSTS file in Windows is it slowing the internet down exponentially, but that's even been curbed over the last couple of years as I've had very little issue. The other main issue is AV/Security software is not friendly with anything messing with the HOSTS file, many AV programs even have settings for HOSTS file tampering.

The main issue used to stem from large HOSTS files, anything over 1MB on slower - medium resourceful machines could stall everything, especially in a browser. There is a hosts compressor script around this repository somewhere (sorry I don't remember where; I actually have a C++ HOSTS compressor tool coming soon) that reduces the file size somewhat, but I'm not thinking that's your case here (or maybe only part of it). If it's a corporate security issue maybe your company has some special measure in place or maybe, if it's an account that is an email that has to access the internet or network to check your credentials it's not able to check those creds and therefore refuses entry, but as asked above I'm not sure exactly what's happening directly after you reboot.

I know I don't work on corporate machines, but I do work on 6 machines in a network all, but one, dual booted and I also maintain two other household's networks that are mostly on Windows 10 (only my misc. laptop is on Win 11) and I have this repositories main HOSTS file on all of those desktops/laptops with no issues.

My guess is something to do with *Tamper Protection*, but I've never had to alter anything in Windows 10 or 11 to allow my HOSTS files to function.

**Comment by StevenBlack** [comment]
Wow thanks for that Ian @Lateralus138!

**Comment by TPS** [comment]
An additional 2¢:

Corporate machines tend to have telemetry enabled, especially as part of their environmental integrity checks, so blocking, e.g. some of,
```
0.0.0.0 browser.pipe.aria.microsoft.com
0.0.0.0 mobile.pipe.aria.microsoft.com
0.0.0.0 v10c.events.data.microsoft.com
0.0.0.0 web.vortex.data.microsoft.com
0.0.0.0 sqm.telemetry.microsoft.com
0.0.0.0 telecommand.telemetry.microsoft.com
0.0.0.0 watson.telemetry.microsoft.com
```

_might_ cause the behavior above, or  even changing the `hosts` file at _all_!

**Comment by m1chaeldg** [comment]
I am not using corporate machine instead I am using my personal PC. Using the base hosts file, my Windows 10 PC and Window 11 laptop hangs. On Windows 10, it will take 3 mins to login but the windows itself is not usable until 10-15 mins mark. On Windows 11, after login apps can be open like chrome and others except there is no internet even after 30 mins. I had to boot at safe mode and remove the hosts file.

**Comment by Lateralus138** [comment]
Sorry I haven't got back here; from what I see it just takes forever for the hosts file to be parsed upon initial Windows boot every 
 time. But your 10-15 mark sounds about right, it takes about that long for the hosts file to be parsed and then everything seems to work fine after for me. But I can login. I just can't access the internet, which is no issue for me as I'm usually making coffee and getting my kids up, but for you I can imagine it's a pain. If you have a smaller hosts lists (I tested around 70k entries seem to increase loading time considerably and have tested a wide range), but the main hosts file here seems to be 100K+ entries. This main file works fine on all my Linux machines, of course. Smaller files will load faster in Windows, sorry to say.

**Comment by dnmTX** [comment]
> is gradually becoming too large for Windows OS

Just a thought,country specific can allways become extension.

**Comment by StevenBlack** [comment]
That's an interesting idea Dan @dnmTX.

**Comment by TPS** [comment]
Since the most recent Windows editions frown heavily upon directly modifying `hosts`,  anything like, e.g., [AdGuard Home](https://adguard.com/en/adguard-home/overview.html) might be the only way to leverage the full scope of the complete `hosts` file(s) here.

**Comment by dnmTX** [comment]
> That's an interesting idea Dan @dnmTX 

👍 

@Lateralus138  i found the issue i mentioned earlier for you to check: #710

**Comment by spdaniel89** [comment]
I've personally come to the conclusion that the problem is not the size of the hosts file but some change Microsoft made. I used the same, albeit large, hosts file for quite some time. At some point I received a windows update that sent my boot time into the 10-15 minutes range. Wish I'd documented it properly so I could be of more help. Also I know I'm comparing apples to oranges, but I have the very same custom hosts on my OnePlus 8 pro and it showed no change in boot time. I feel like if a phone can do it a desktop PC should have no trouble.  I might do some experimentation with some older versions of windows to try and pinpoint the problem and make sure I'm not simply experiencing faulty memory (mine, not the computer.)

**Comment by indy-singh** [comment]
Just had the exact same issue; it completely tanked my install of Windows 10. Had to use Safe Mode with CMD to flick over to a backup HOSTS file. As soon as I did, it was fine.

I was using https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts I suspect that there is a domain that Windows _has_ to contact (e.g. telemetry etc) and it causes some sort of deadlock.

**Comment by TPS** [comment]
@indy-singh What Windows were you trying to install: S, Home, Pro, Enterprise, &c?

**Comment by indy-singh** [comment]
![image](https://user-images.githubusercontent.com/1906778/150124888-0f89db8d-d9b7-4718-8aab-6a7ed8d1d230.png)


```
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19044 N/A Build 19044
```

Not sure why the version matters. I can try on my other machines (Pro), but I suspect it'll be the same.

**Comment by TPS** [comment]
@indy-singh There was a couple of different conjectures in this thread re: whether corporate versions were causing the problem or a specific recent update to Windows.  I'm leaning toward the latter now, but perhaps there's a way to do, e.g., an old-school offline installation that would moot this problem entirely?  Or some sort of option to disable telemetry for installation?  Research is needed.

**Comment by TPS** [comment]
Can https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-setup-command-line-options?view=windows-11#telemetry be used?

**Comment by indy-singh** [comment]
Ah, sorry. I think there has been a miscommunication. When I said "install" I mean a pre-existing long running installation of Windows. I did not mean during a Windows install.

**Comment by TPS** [comment]
Then **carefully** working through https://docs.microsoft.com/en-us/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services _might_ work.…

**Comment by krllus** [comment]
Is there an easy fix? I'm facing the same problem after "installing" the unified hosts (same as OP);

**Comment by rautamiekka** [comment]
> Is there an easy fix? I'm facing the same problem after "installing" the unified hosts (same as OP);

Use the hosts file compressor in this repo, should help at least some.

**Comment by krllus** [comment]
Huh. I solved by using the bat script[1] described in the README.md plus the `ipconfig /flushdns` and then reboot;

[1] https://github.com/StevenBlack/hosts/blob/master/disable-dnscache-service-win.cmd

**Comment by TPS** [comment]
> Huh. I solved by using the bat script[1] described in the README.md plus the `ipconfig /flushdns` and then reboot;
> 
> [1] https://github.com/StevenBlack/hosts/blob/master/disable-dnscache-service-win.cmd

That's interesting, as that service particularly would be required in corporate environments, so that would match the experiences above of such folks.

**Comment by TPS** [comment]
Both https://blogs.windows.com/windows-insider/2021/09/23/releasing-windows-10-build-19043-1263-21h1-to-release-preview-channel/ & https://blogs.windows.com/windows-insider/2021/09/23/releasing-windows-10-build-19044-1263-21h2-to-release-preview-channel/ mention an update to the DNSCache service to _fix_ an issue that sounds like this, released to Insiders (alpha/beta testers in September 2021), so might be hitting as an update recently/soon?:
> We fixed an issue that causes the DnsCache service to increase the CPU usage to 100% utilization. As a result, the device stops responding.

I wonder if this fix is related to our problems here.

**Comment by krllus** [comment]
> Huh. I solved by using the bat script[1] described in the README.md plus the `ipconfig /flushdns` and then reboot;
> 
> [1] https://github.com/StevenBlack/hosts/blob/master/disable-dnscache-service-win.cmd

when using this script to disable cache, the VPN connections can't be edited, had to revert this change by using the default value (`2`) mentioned in the script;

**Comment by shiguera05** [comment]
I loaded the HOSTS file + fakenews + gambling + social on my Windows 10 Home machine (OS 20H2 build version 19042.1526) and rebooted. It lost its connection to my wi-fi network and it hang, meaning the task bar did not load all the icons, when I moved the mouse over it, it would shows thee sandclock, was not able to modify the HOSTS because "another process was using it".  I waited for maybe 10 minutes and same thing. I had to start on SAFE mode and swap my HOSTS back to default from MS and issue solved. Either its too big of a file (3,401kB) or some line in it is causing some issues on Windows.

**Comment by rautamiekka** [comment]
> I loaded the HOSTS file + fakenews + gambling + social on my Windows 10 Home machine (OS 20H2 build version 19042.1526) and rebooted. It lost its connection to my wi-fi network and it hang, meaning the task bar did not load all the icons, when I moved the mouse over it, it would shows thee sandclock, was not able to modify the HOSTS because "another process was using it". I waited for maybe 10 minutes and same thing. I had to start on SAFE mode and swap my HOSTS back to default from MS and issue solved. Either its too big of a file (3,401kB) or some line in it is causing some issues on Windows.

->
> > Is there an easy fix? I'm facing the same problem after "installing" the unified hosts (same as OP);
> 
> Use the hosts file compressor in this repo, should help at least some.

**Comment by ggvelev** [comment]
> I loaded the HOSTS file + fakenews + gambling + social on my Windows 10 Home machine (OS 20H2 build version 19042.1526) and rebooted. It lost its connection to my wi-fi network and it hang, meaning the task bar did not load all the icons, when I moved the mouse over it, it would shows thee sandclock, was not able to modify the HOSTS because "another process was using it". I waited for maybe 10 minutes and same thing. I had to start on SAFE mode and swap my HOSTS back to default from MS and issue solved. Either its too big of a file (3,401kB) or some line in it is causing some issues on Windows.

Same story. After applying the [unified hosts recipe](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts) I got exactly the same behavior with constantly crashing taskbar, limited network connectivity, high CPU usage by the DNS client service etc. 

Checked the event logs and they were full of these (ID 7011):

> A timeout (30000 milliseconds) was reached while waiting for a transaction response from the Dnscache service.

Compression of the hosts file seems to fix it 🙂

**Comment by peternm22** [comment]
I ran into the same problem today running Windows 10.

I was using the MVPS hosts file and just noticed that it hasn't been updated in quite some time. The StevenBlack files seemed like an appropriate choice to migrate to so I added them as a source in Hostsman. Immediately I could not navigate to any websites in either Firefox or Chrome. I had a Youtube live stream running and it was still going strong so I knew it was a DNS problem and not my entire internet connection.
I attempted to disable (revert) the hosts file in Hostsman but received an error that it was in use by another process. Manually editing the hosts file did not allow me to save it.
I restarted the computer and it hung on the welcome screen making it impossible to get into Windows (I gave it 5 minutes and gave up). I run daily backups using Macrium reflect so I restored my C drive to get Windows running again (quick to do, but safe mode would likely have been quicker).

**Comment by StevenBlack** [comment]
Closing this because it's not actionable here. These are Windows OS userland issues.

**Comment by TPS** [comment]
> ~Compression~ Compaction of the hosts file seems to fix it 🙂 

@StevenBlack Would you be interested in applying some compaction (as discussed above) on the `hosts` files before serving to help those of us on Windows?

**Comment by TPS** [comment]
Else, https://scripttiger.github.io/alts/ lists some *pre*compessed versions that might be useful to Windows users.

**Comment by StevenBlack** [comment]
Hi @TPS we already offer the `--compress` option on hosts file generation.

Absolutely will not make this the default, no.  This is Microsoft's bug, or Microsoft's limitation, or whatever one wants to call it.

**Comment by Meyers07** [comment]
Happens to me recently. Copying the whole list did it but it kills the network connection.
Restarting, trying to replace with the original hosts, it is said to be "open in other program or application" I think it's about how Windows took so much time to read the whole list instead of picking it like what browser blockers did.
I read about booting in safe mode, because full reinstall in this 10+ year old PC is not negotiable given the time that if i want to reinstall might as well when it'll be fully replaced.
I boot in safe mode, replace the original host, done without a hitch.
Restarting, works fine.

Good thing i use my personal computer to test this thing.

**Comment by TPS** [comment]
@Meyers07 Per the comments above, the best workaround is to use your choice of the `Compressed` versions from https://scripttiger.github.io/alts/.  How is that for your setup?
