### ISSUE TITLE
Over 900 new porn hosts

### ISSUE THREAD

**Issue by 1boii** [StevenBlack/hosts#1865]
I've spent hours finding porn sites which are not in the porn extension of this repo. So far, there are over 900 new, unique porn domains and also some gore/scat/torture ones. 

As all my attempts to get some of these merged into https://github.com/Sinfonietta/hostfiles are still pending, I've created my own hostfile repo in the meantime: https://github.com/1boii/hosts

What would you suggest how we should handle this? I cannot promise to update the repo regularly as it is quite time consuming and also mentally scarring sometimes. I will, however, add new domains if I come across any. 

So adding this as an extension would be fine by me, provided the repo is not too small or too new.

**Comment by StevenBlack** [comment]
> ... it is ... also mentally scarring sometimes.

I hear 'ya @1boii.

> I've spent hours finding porn sites which are not in the porn extension of this repo

Did you know... our processes deduplicate domains that appear in more than one list? There is no need to do that.

In fact I prefer if lists are **NOT** de-duplicated because it makes curation harder for no reason, and it prevents analyzing various lists for trends and consensus.

When a proposed new source has low overlap, or zero overlap, it makes me suspicious. Tank you for disclosing this but I prefer lists that are can stand on their own merits, and not tailored for no intersection.

Please don't misunderstand! That's not meant as critisism, I'm just

**Comment by 1boii** [comment]
I understand. I use the porn extension in my pihole and discovered that there are still a lot of porn sites which are not blocked, so I'm trying to fill these gaps. That is kind of the goal. 

@Sinfonietta would you like me to open (another) PR to merge all this? Or can you copy it manually from my repo? 

The problem with PRs is, is that they become outdated so quickly and take a while to get merged. For me personally, it's important that new sites are blocked as quickly as possible. That's why I created my own repo/list in the first place.

The best solution would be if I could write directly to https://github.com/Sinfonietta/hostfiles, but I understand that this is likely not an option.

**Comment by Sinfonietta** [comment]
Hello @StevenBlack and @1boii I have merged the PR in my porn hosts list 👍

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta and @1boii!  

Closing!
