### ISSUE TITLE
Block SalesForce marketing monitor

### ISSUE THREAD

**Issue by theking2** [StevenBlack/hosts#1891]
Exact target
0.0.0.0 cl.S1.exct.net
0.0.0.0 cl.S2.exct.net
0.0.0.0 cl.S3.exct.net
0.0.0.0 cl.S4.exct.net
0.0.0.0 cl.S5.exct.net
0.0.0.0 cl.S6.exct.net
0.0.0.0 cl.S7.exct.net

**Comment by StevenBlack** [comment]
Hi @theking2 thank you for this.

What more can you say about these domains?  We should block them because...? Thanks.

**Comment by MrRawes** [comment]
should edit out THESE
0.0.0.0 cl.S1.exct.net
0.0.0.0 cl.S2.exct.net
0.0.0.0 cl.S3.exct.net

**Comment by theking2** [comment]
These are Salesforce tracking sites

**Comment by MrRawes** [comment]
> These are Salesforce tracking sites
i know i was pointing out that some domains are dead

**Comment by StevenBlack** [comment]
Thanks for that @theking2 but that's not particularly enlightening.

Let me ask again.  You know this because...?  You observed what? and how? What URL yields requests to these domains? What are they tracking with these, do you know?

Also, do Salesforce apps work when these are blocked?  The mobile apps too?  You're sure?

A deeper question is, if someone is on Salesforce, how are they not surrendering ALL their data already?

**Comment by StevenBlack** [comment]
Closing this.
