### ISSUE TITLE
Missing social media sites

### ISSUE THREAD

**Issue by AndrewtheCanon** [StevenBlack/hosts#1905]
lunchclub
telegram
discord

**Comment by StevenBlack** [comment]
Thanks for this Andrew @AndrewtheCanon.

Both Telegram and Discord don't strike me as "social media" sites.  Full disclosure: I use both Telegram and Discord very superficially, always as a software developer with questions for specific support communities. 

Am I wrong about that?

I've never seen Lunchclub.  A superficial scratch indicates this might be a candidate.  Does anyone have insight into Lunchclub?

Ping @sinfonietta, one of our social media curators....

**Comment by StevenBlack** [comment]
Closing this because it doesn't appear actionable.

**Comment by this-is-just-con-tribute** [comment]
> Thanks for this Andrew [@AndrewtheCanon](https://github.com/AndrewtheCanon).
> 
> Both Telegram and Discord don't strike me as "social media" sites. Full disclosure: I use both Telegram and Discord very superficially, always as a software developer with questions for specific support communities.
> 
> Am I wrong about that?

Not the way you personally are using it, no. However, it depends on if you consider discord/chatrooms in general social media. They let you socialize, have notifications, and allow you to waste hours of time. They have pretty much all of the same features of any other social media site/chatroom. Also worth noting is that if someone is trying to block social media, they are probably doing it because it's very distracting. Discord as I use it is absolutely social media and distracting.

So I'll leave it up to you.
