### ISSUE TITLE
Hosts list bricking apps

### ISSUE THREAD

**Issue by secuninja** [StevenBlack/hosts#1924]
Hi,

0.0.0.0 image.ard.de
0.0.0.0 image.mdr.de
0.0.0.0 images.kika.de

this blacklist entries bricks apps like "Kikaninchen" which is required to load pictures from there.

**Comment by StevenBlack** [comment]
Hello @secuninja thank you for this.

All those domains come to us via [AdguardTeam cname trackers](https://github.com/AdguardTeam/cname-trackers/issues) list, which is upstream.

Perhaps you could raise this with them?

Fair warning, though: this may not change because `cname` DNS records cloak the real origin of the resource.
