### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Zorono** [StevenBlack/hosts#1932]
(Suggestion!) Please add @neodevpro/neodevhost (https://raw.githubusercontent.com/neodevpro/neodevhost/master/host) as additional unified data source

**Comment by StevenBlack** [comment]
Thank you for this suggestion John @Zorono.

Using [ghosts](https://github.com/StevenBlack/ghosts) to assess (see below).

This would add `(151709-99428) = 52,281` new domains to this list. It overlaps with '(99428/100055) = 99.3%` of our list.

Looking at the repo (https://github.com/neodevpro/neodevhost) it has a decent curation history but it appears to be mostly automated mechanical curation.

```
$ ghosts -c https://raw.githubusercontent.com/neodevpro/neodevhost/master/host

----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 100,055
Bytes: 3.1 MB
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/neodevpro/neodevhost/master/host
Domains: 151,709
Bytes: 4.3 MB
Intersection: 99,428 domains
```

**Comment by StevenBlack** [comment]
Thanks again John @Zorono however I've decided to decline this suggestion.  Here's why.

I think we have a really solid list here, one that arises from input from many quarters, active for nearly a decade.  I think this assembly of active and carefully curated lists is what makes this amalgamation so special.

This @neodevpro list would increase our list size by 50%. I don't feel this extra load would improve this list by much. Especially on Windows systems which already have difficulty functioning with 100,000-line hosts files.

Becoming a monster hosts file listing several hundred thousand hosts is not what I want to become.  At that level, curation is impossible, and very large hosts files inevitably become add-only buckets.  I'm already uneasy with 100,000 hosts in our base list.  I want to become smaller, with little or no loss in effectiveness, not dramatically larger for a marginal gain.

So that's my thinking.

ALL THAT SAID, if you want to clone this repo and add the @neodevpro list, you can always do that.  I just don't want to go that deep, 50,000 domains deeper, with evidently little to gain.

Thanks for the suggestion nevertheless.

Closing.
