### ISSUE TITLE
Provide uninstall option

### ISSUE THREAD

**Issue by h0r0man** [StevenBlack/hosts#194]
Please provide an uninstall option for easy restoring default hosts file.

**Comment by StevenBlack** [comment]
Hi @h0r0man 

Is this really a problem?   When I Google `default hosts file <substitute os here>` I appear well-served no matter which `os` I substitute in the query.

Do I understand this right?  Am I missing something?

**Comment by jsilvermist** [comment]
I think a pretty easy uninstall option is:
1. Open hosts file
2. Highlight all
3. Hit backspace/delete
4. Save file

**Comment by Atavic** [comment]
Is this an issue? If someone is here to get the host file, he's supposed to know how to handle system files.

**Comment by StevenBlack** [comment]
Closing 😄

**Comment by gir489returns** [comment]
CMD:

C:\WINDOWS\system32>break>%SystemRoot%\System32\drivers\etc\hosts
The process cannot access the file because it is being used by another process.

PowerShell:
PS C:\WINDOWS\system32> Clear-Content $env:SystemRoot\System32\drivers\etc\hosts
Clear-Content : The process cannot access the file 'C:\WINDOWS\System32\drivers\etc\hosts' because it is being used by
another process.
At line:1 char:1
+ Clear-Content $env:SystemRoot\System32\drivers\etc\hosts
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\WINDOWS\System32\drivers\etc\hosts:String) [Clear-Content], IOException
    + FullyQualifiedErrorId : ClearContentIOError,Microsoft.PowerShell.Commands.ClearContentCommand

**Comment by StevenBlack** [comment]
@gir489returns Windows os is a complete dumpster fire.
