### ISSUE TITLE
fakenews + gambling + porn without Unified hosts

### ISSUE THREAD

**Issue by alsyundawy** [StevenBlack/hosts#1954]
hallo,

thx for great list, but can i req fakenews + gambling + porn without Unified hosts only?

**Comment by StevenBlack** [comment]
Hi @alsyundawy thank you for your question, that's an interesting idea.

I don't feel there's much demand for this mix, since the benefits of ad and malware blocking are undeniable.  **However** this repository includes full source code and you could tweak [`updateHostsFile.py`](https://github.com/StevenBlack/hosts/blob/master/updateHostsFile.py) to suit your needs.

If you choose to do so, and make this feature driven by runtime flags, I would certainly entertain a pull request for this. 😄

**Comment by alsyundawy** [comment]
how to grep gambling + porn only?

**Comment by StevenBlack** [comment]
Cangkeman @@alsyundawy this capability is coming, hopefully pretty soon!

**Comment by alsyundawy** [comment]
wow thx, cant wait

**Comment by alsyundawy** [comment]
yes but https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts merger with Unified hosts but

i just need fakenews-gambling-porn without Unified hosts , reason is in. my country gov illegal to access fakenews-gambling-porn bloked using dns but ads allowed

**Comment by alsyundawy** [comment]
any update?

**Comment by StevenBlack** [comment]
Hi @alsyundawy it's coming. I hope to get this realized within the next 30-days.

**Comment by alsyundawy** [comment]
cant wait hehehe

**Comment by jfrederiksen427** [comment]
Oh, that's actually interesting. As for the gambling games, they're getting even more popular nowadays, and it's not even surprising because games like [https://parimatch.in/en/page/online-eagles-gold](https://parimatch.in/en/page/online-eagles-gold) are thrilling, and the experience just can't be described, I think all the people who tried gambling at least once will understand me.

**Comment by alsyundawy** [comment]
> Hi @alsyundawy it's coming. I hope to get this realized within the next 30-days.

hi , any update ?

**Comment by alsyundawy** [comment]
any update @StevenBlack @ScriptTiger ?

**Comment by StevenBlack** [comment]
Still working on it @alsyundawy.

**Comment by alsyundawy** [comment]
cant wait 💕💕💕💕💕💕

**Comment by ScriptTiger** [comment]
@alsyundawy, I'm also still working on overhauling Hosts-BL, with one of the new things allowing removal/filtering out of entries based on a given hosts file. So, in your case, you would be able to just do the base+gambling+porn list and filter the base. The current Hosts-BL is super basic and just written for speed, since I generate 11 different formats for each of the 16 flavors of the hosts file, so 176 different conversions, for my downloadable pre-generated blacklists. Hosts-BL will definitely be able to do the job faster than running a Python script, but having the ability to generate the desired hosts file from scratch locally yourself directly from the start using the updateHostsFile.py will also have plenty of benefits, as well, depending on your workflow and security requirements.

P.S. @StevenBlack, there's a shill four comments up promoting gambling who needs to be removed/blocked/reported.

**Comment by StevenBlack** [comment]
Closing because this is done.
