### ISSUE TITLE
Seperate HOST list for url shortners

### ISSUE THREAD

**Issue by getthit** [StevenBlack/hosts#1962]
Greeting!!

We suggest, it will be good to have separate list for URL shortners. 

We have bunch of URL shortners list and we are ready to share and support this project.

Also this project is helping us a lot.

**Comment by StevenBlack** [comment]
Thank you @getthit that's an interesting idea.

You provide no specifics, so this issue isn't actionable at this time.  Care to elaborate?

**Comment by getthit** [comment]
Dear [StevenBlack](https://github.com/StevenBlack),

Wow, thank you very much for your reply. Please find the sample URL shortner domains given below. 
Please give us sometime to pull and validate all the URL shortner blocked in our service. 

www.cli.re
cli.re
kol.jumia.com
jumia.com
www.linkjust.com
linkjust.com
www.tny.im
tny.im
www.lnkiy.in
lnkiy.in
www.urlzs.com
urlzs.com
www.n9.cl
n9.cl
www.clicklo.world
clicklo.world
www.surl.li
surl.li
www.earn-shortlink.com
earn-shortlink.com

Thank you again for accepting our idea.

**Comment by getthit** [comment]
Also please find our answers below.

**You provide no specifics** - 99% URL shorner spread Adware and malware, then redirects the user to dangerous pages. So it will be good to have a separate block list. Also we are seeing lot of new URL shortner on daily basis. 

We are open to share the list on bi-weekly or monthly basis to you.

**Comment by StevenBlack** [comment]
Thank you for your reply @getthit.

Here's how this works.

We only include lists from reputable curators with a track record of activity that involves additions AND removals over a significant period of time.

Here's why: including your list in our lists gives YOU the power to affect what gets shown, or not shown, on millions of devices.  There's no way of knowing, but maybe that's hundreds of millions of devices.

This is serious business.  We've been doing this a long time, more than 10-years, and contributors here are all very serious and dedicated to this.

So here we are, and you come along.  You allude to some list you have, but you STILL haven't provided a link to that list so we cam assess it.

Please, stop wasting my time.

I'm closing this issue now because I don't sense you have much to offer. If you did, a link to your great list would have appeared in the first panel ⬆️⬆️⬆️.  This is panel six. 🙄 

Thank you for your suggestion, but based on what I see, including your [Github byline](https://github.com/getthit) which states, `Getthit.com's Autosurf Website Traffic Exchanger is a incredible application that will automatically deliver a large number of visitors to your website` I respectfully decline to work with you.

My decision is final. I'm not giving you keys to control what gets shown on millions of devices.

Closing.

**Comment by getthit** [comment]
Thank you very much for looking on this. 

We respect your decision and but we are requesting you to take forward on this idea on your own, if possible. Please have few seconds to look on our reply for your comments.

**I'm closing this issue now because I don't sense you have much to offer. If you did, a link to your great list would have appeared in the first panel **
We already asked you sometime, coz today(03-May-2022) is holiday for offshore support team. We too need few days to validate on our end to. 

**Thank you for your suggestion, but based on what I see, including your [Github byline](https://github.com/getthit) which states,**
Our service is fully functional on your blocklist (Ad + Malware + Porn) and we too serious about this. And we feel sorry for your comment. You can reject our list and but please do not reject our idea.

**Comment by getthit** [comment]
We just created a list of URL shortners as a first batch of 70 domains (+70 with www prefix). Thank you very much for your consideration. 

[URL shortners block list](https://github.com/getthit/getthit-url-block-list/blob/12d7f12d21e1b5f18d82429d382d538976261c56/url-shortners-block-list.txt)
