### ISSUE TITLE
Add phishing/spam site

### ISSUE THREAD

**Issue by 1alessandro1** [StevenBlack/hosts#1965]
`0.0.0.0 10eurodisconto.com` got in my mailbox claiming a 50€ bonus, I recommend adding it to the blacklist

**Comment by StevenBlack** [comment]
Closing this @1alessandro1 because this isn't a threat.  Someone sent a marketing email to you.  That's fine, it's not illegal, it's not bad, just someone tempting recipients via email.

We are not in the business of taking companies down from the internet.  We don't have a legal team here to do that and defend against pushback from that..

We just block their vectors for serving adds and malware and other things.
