### ISSUE TITLE
Pancakeswap.finance is blocked?

### ISSUE THREAD

**Issue by Willhax** [StevenBlack/hosts#1966]
I thought their site was down and I was screwed... why would you block this site?

**Comment by StevenBlack** [comment]
Hi Will @Willhax thank you for your question.

Please see the [readme](https://github.com/StevenBlack/hosts/blob/master/readme.md) for info about how all this works.  In short, we're mostly an aggregator of actively curated hosts files that we merge, de-duplicate, and package in various ways.

The `pancakeswap.finance` domain comes to us from upstream. The source is KADhosts, and you can make the case [here](https://github.com/PolishFiltersTeam/KADhosts/issues).

Hi @krystian3w, do you have insight on `pankakeswap.finance` and `www.pankakeswap.finance`?

**Comment by StevenBlack** [comment]
Will @Willhax I just followed the paper trail behind this inclusion, and I now understand why the domains `pancakeswap.finance` and `www.pancakeswap.finance` are blocked by KADhosts.

cc: Krystian @krystian3w unless you have anything else to add, I'm happy to close this issue.

**Comment by Willhax** [comment]
OIC now, I can't read his language, but pancake.finance is a legitimate crypto defi site. Just a heads up. You can close, thank you!

**Comment by StevenBlack** [comment]
Will @Willhax the translation option in Google Chrome is a big help here.

As far as I can tell there are a few facets to this.

The first appears to be an advisory from the government of Spain about CAKE either not meeting requirements, or failing to disclose. I'm actually fine with that because this could be just Spain being Spain.

The second facet is more troubling and it involves a bunch of involved discussions about whether pancake has its shit together. It's certainly not looking pretty. Have a look.

To be honest I think there's a lot more where that came from and, at some level, Ponzi demand has got to be recognized, and soon, in a wide swath shitcoinspace.

I'm certainly not qualified to make that call, and I have a enormous respect for the people who are sticking their necks out, and calling a spade a spade.

Let's see what @krystian3w says...

**Comment by Willhax** [comment]
Yea that was the gist of what I got too, I used google translate but it was less than helpful. I could see how some governments would be against crypto defi as it's a volatile and risky space. Either way, there is always whitelisting as an alternative. I really like your project, so that as a work around is fine. Thank you for your follow up though.

**Comment by krystian3w** [comment]
It is as [Willhax](https://github.com/Willhax) describes, organizations do not always verify to the maximum that the entity is secure.

We definitely need to implement more checking at the KAD level.

**Comment by StevenBlack** [comment]
Thank you as always Krystian @krystian3w!

Will @Willhax the `pancake.finance` domains will be cleared and this will be reflected in the next release, coming soon. Thank you for opening this issue.

Closing.
