### ISSUE TITLE
reddit.com redirecting to localhost

### ISSUE THREAD

**Issue by RajuKottedi** [StevenBlack/hosts#1982]
remove line "0.0.0.0 www.reddit.com"
from master/alternates/fakenews-gambling-porn-social/hosts

**Comment by gnuaelianus** [comment]
I'm no networking guy, but I don't see the problem with that "code". it does what the hosts file says it does, block all social media including reddit. Also localhost is `127.0.0.1`.

**Comment by StevenBlack** [comment]
Hello Raju @RajuKottedi thank you for your observation.

All our "social" variants block social media which would include Reddit.

I suppose it's helpful to explain why our "social" variants exists.  People who use the "social" variant are expected to fall into at least one of two bins:
1. Those seeking a distraction-free computing environment.
2. Those seeking to limit what children are able to see.

That's why we block Reddit in the social media variants.

**Comment by StevenBlack** [comment]
Thank you for your take Elian @gnuaelianus.

The reason we use `0.0.0.0` is explained in the readme pages for our variants.

See the section titled [`We recommend using 0.0.0.0 instead of 127.0.0.1`](https://github.com/StevenBlack/hosts).

**Comment by StevenBlack** [comment]
Closing!

**Comment by RajuKottedi** [comment]
Hi Steven & Elian @StevenBlack @gnuaelianus  Thank you for your response and explanation. 

I should have read the readme pages before opening the issue. @StevenBlack  Once again thank you. Appreciate your work.
