### ISSUE TITLE
Breaks Williamhill site

### ISSUE THREAD

**Issue by nkbyrne** [StevenBlack/hosts#1995]
Entry static.williamhill.com breaks williamhill.com site.

**Comment by StevenBlack** [comment]
Hi Neil @nkbyrne – thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

The domain `static.williamhill.com` comes to us from the list at `someonewhocares.org`.

Can you please submit this to Dan Pollock at hosts@someonewhocares.org? Dan is typically very responsive and I trust Dan to do the Right Thing.  That said, you may have to make a case for the domain `static.williamhill.com` since Dan has probably seen evidence that this domain may be sketch, to some degree.

I'm leaving this issue open, please report back once you know how this turns out?  Thanks!
