### ISSUE TITLE
block this domain

### ISSUE THREAD

**Issue by holequantum** [StevenBlack/hosts#2003]
i think it is used for capture the user location by gooogle and surely for tracking
`userlocation.googleapis.com`

**Comment by StevenBlack** [comment]
Thank you for this @holequantum.

My research into domain `userlocation.googleapis.com` isn't turning up anything nefarious.

I'm going to need some evidence to support what you think.  I'm not saying you're wrong, I'm just saying, show us.

**Comment by holequantum** [comment]
it is actually extremely hard to actually give evidence.
but i have a pixel device with graphene installed that does not ping that server.
a simple whois showing this is a googles server.
and i have manually blocked that and does not saw any issues at all. everything was working as it should be.
and as you can see this is not a part of android itself https://cs.android.com/search?q=userlocation.

**Comment by holequantum** [comment]
> This could break Google Maps in theory though, right?

nope it does not block gmaps or location services
mobilemaps-pa-gz.googleapis.com
mobilemaps.googleapis.com
android.apis.google.com
this 3 is important in gmaps

**Comment by icedterminal** [comment]
Blocking this domain can actually break or reduce location accuracy for any third party app or service should the developer be using Google's Geolocation API. Websites that use the API to provide service get an error outright.

[This page](https://medium.com/risan/track-users-location-and-display-it-on-google-maps-41d1f850786e) demonstrates how to use this API for a website. If you block this domain, the website will have issues getting your location.

It is not advised to block this domain by default. This could cause a myriad of issues for all manner of users.

**Comment by holequantum** [comment]
Yes it provide some help for other 3rd party apps but that is not all but google collections location with that and use that for tergeting users

**Comment by icedterminal** [comment]
What you think is "not acceptable" is not relevant. Blocking that domain *will* causes issues for services that use Google's Location API. Those services may very well need them and putting that domain in in public host will, again, cause more issues than fix. As I said in a previous comment, you realistically cannot just block API domains carelessly.

**Comment by StevenBlack** [comment]
We have a number of curated sources amalgamated into our lists.  Google is among the most, if not THE most scrutinized company when it comes to assessing its trackng activities.

I'm going to let our curators decide.  Those who watch Google like a hawk will make this call. I'm not making this call.

When I'm driving, and there's a delay ahead, I want Waze to be able to re-route me to avoid the delay with a sensible bypass route.  I give Waze location privileges. I never want my hosts file to make that call for me. That's just me. 

Closing.

**Comment by holequantum** [comment]
Thanks about that having a better understanding about that my device is constantly pinging is good. If it is important then we can not block for sure in my situation blocking this does not make any issue.

**Comment by icedterminal** [comment]
Just to give you some background, many Google and Microsoft domains have been blocked in the past because they are found to include tracking data while not realising blocking that domain broke core services or functionality.

A community managed list is here: https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212

There are a few great examples.

`tracking.epicgames.com` does indeed include tracking data tied to your personal information, *but* blocking the domain completely breaks purchasing anything from their store.

`clients.google.com` is known to track data that is personally identifiable. Blocking the client domains breaks more than one Google service entirely. 

Multiple Microsoft domains are tracking *and* providing OS functionality. Some of these domains are tied to updates, others simply enabling the use of specific apps.

For future reference, when you think you've come across a domain that is suspect, use a web debugger to inspect and scrutinize it. Pass the domain around to friends and have them block it too. The more people the better. You have to be 100% certain it won't affect people negatively. The domains I have submit in the past were inspected and block tested by about a dozen people for months before I opened an issue here to have them added.
