### ISSUE TITLE
Release 3.11.4 seemingly broke Paramount Plus streaming

### ISSUE THREAD

**Issue by jaredbrogan** [StevenBlack/hosts#2030]
All of a sudden my stream of paramount plus (on desktop) stopped working due to an adblock related error. Upon updating my pi-hole to use version 3.11.3 of the hosts file, it allowed the stream to be restored.

**Comment by StevenBlack** [comment]
Thank you for this Jared @jaredbrogan.

We will need to know, which domain does Paramount Plus need, here?

**Comment by jaredbrogan** [comment]
Hi @StevenBlack, it appears to just be these two:
* `tags.tiqcdn.com`
* `s0.2mdn.net`

There may or may not be more that pop up, but I'll report back if they do.

**Comment by StevenBlack** [comment]
An update on this.

* The domain `tags.tiqcdn.com` is blocked by three of our sources (yoyo.org, mvps.org, and Adaway).  So that's probably not going to change.

* The domain `s0.2mdn.net` is blocked by four of our sources (someonewhocares.org, mvps.org, tiuxo, and Adaway).  So that's probably not going to change either.

**Comment by jaredbrogan** [comment]
Noted. I mainly wanted to point this out as others may be having similar issues. If this is unavoidable, you may close out this issue.

**Comment by StevenBlack** [comment]
Thanks Jared @jaredbrogan.

Closing.
