### ISSUE TITLE
(Windows) Disabling DNS Cache Service has consequences

### ISSUE THREAD

**Issue by M1ch431** [StevenBlack/hosts#2094]
It appears that Network Discovery is dependent on the DNS Caching service being active.

So, when the .bat file is applied, I can't (for example) access the Shield (Android TV) on my network.

I suggest adding a warning that something like this could occur to the end-user.

**Comment by StevenBlack** [comment]
Thank you @M1ch431. I would entertain a pull request for this modification to the docs.

**Comment by ScriptTiger** [comment]
I don't know how many users or end devices my script is running on, but I'd say easily several hundred at least, and I've been getting away with only using `ipconfig /flushdns` this whole time for years. Toggling the DNS cache service is only needed if you're working with those ridiculously uncurated lists running several gigabytes in size, which directly goes against the entire premise of this repository. As long as this repository plans to keep a resultant hosts file just a few megabytes, toggling DNS cache can be completely dropped to avoid serious complications.

> :SCset
:: VALUE
:: 2 (Automatic) (DEFAULT)
:: 4 (Disabled) (to prevent network freeze after applying a huge hosts file)

None of the hosts files here could ever be construed as "huge." If you seriously think any of them are "huge," it's only because @StevenBlack has been doing a damn good job with this script and you're perspective has been skewed about what "huge" really means.

**Comment by MidnightD4wn** [comment]
how can i enable DNS Cache Service again

**Comment by StevenBlack** [comment]
@MidnightD4wn try [this](https://wintechlab.com/enable-disable-dns-client-service/) maybe. There are other articles, just Google "enable DNS Cache Service".

**Comment by Lateralus138** [comment]
I'm not sure what method the batch file uses, but I almost assume it's via the registry and if so you can re-enable it via either the registry itself or a ***.reg*** file.

You can create the file yourself or if you want I can upload it later.

To enable from a file just save the following to a file named ***<whatever_you_like>.reg*** (dns_cache_enable.reg for example, don't save as .txt) and then you can execute the file in any way to you can execute any other program/script in Windows:

To enable the cache:
```Powershell
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache]
"Start"=dword:00000002
```
To disnable the cache:
```Powershell
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache]
"Start"=dword:00000004
```
or, of course, you can manually edit directly in regedit ((`Win+r` (or a terminal) -> regedit) or (`Start Menu`->regedit)) and navigate to the above mentioned path and value:

Path
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache

Value
> Start

and then enable by changing ***Start*** to `2` for enabled and `4` for disabled.

I'm actually in the process of writing a C++ tool with to make this.

I'm usually in Linux more in the last few years, but I've spent the last month or so in Windows trying to understand all the newer various changes to the way DNS (and networking in general) works (lots of things have change since Windows 8 came out), but as I've stated before messing with stuff like changing important settings usually messes thing up in Windows in the long run (I have to enable DNS if I ever want to use WSL ☹️, but not a big deal for me because I have other various Linux machines). Disabling the cache is only a temporary solution for those who want large hosts files. I've noticed though that if you do have the DNS Cache enabled when installing a custom hosts if you let it run long enough it actually starts working after a while and if you do this for several days (rebooting in between) after installing a new hosts it eventually starts loading faster (almost like the caching stalls after a while during a session and then restarts caching on the next boot) and then after a few days it works perfect. That would mean that Windows users should update less often and only when they have free time to let their machine sit or at least not do things online. I planned a while ago to try and look into this more, but I've been stuck in Linux a while so it's hard to get over to Windows to actually do any testing and development. It's about time I get around to it.

If you have trouble figuring out how to follow my instructions above then let me know and I'll just upload the files.

**Comment by sudarpo** [comment]
For GUI, I prefer to use Autoruns tool from Sysinternals.
Download link here; https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns

**Comment by StevenBlack** [comment]
Closing.
