### ISSUE TITLE
Remove cloud-news.ionos.com

### ISSUE THREAD

**Issue by sebastiande** [StevenBlack/hosts#2124]
Hi,

I got a mail from IONOS Cloud (to which I have actively subscribed), but I can not really view it cause the images are blocked cause cloud-news.ionos.com is on this blocklist.

Can you remove it? I looked and you should only get something from this URL if you have actively subscribed.

Thanks,
Sebastian

**Comment by StevenBlack** [comment]
Hi Sebastian @sebastiande.

Let's check!

```bash
dig cloud-news.ionos.com all                                                                          15:33:41
cloud-news.ionos.com.	86400	IN	CNAME	go.pardot.com.
go.pardot.com.		3945	IN	CNAME	pi.pardot.com.
pi.pardot.com.		294	IN	CNAME	pi-ue1.pardot.com.
pi-ue1.pardot.com.	28	IN	CNAME	pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com.
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 54 IN A 18.208.125.13
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 54 IN A 34.237.219.119
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 54 IN A 52.54.96.194
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 54 IN A 3.215.172.219
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 54 IN A 3.92.120.28
```

So it appears that `cloud-news.ionos.com` is a CNAME record that fronts for `go.pardot.com` and other `pardot.com` domains. Those are, in any event, also blocked because `pardot.com` is bad news. Three of our upstream curators list quite a few `pardot.com` domains.

You could report this to IONOS Clout, and ask them to stop the shenanigans.

Closing.
