### ISSUE TITLE
lnks.gd is being used in local government e-mail bulletins.  Please consider removing from this blocklist

### ISSUE THREAD

**Issue by mgh128** [StevenBlack/hosts#2125]
lnks.gd is being used legitimately in local government e-mail bulletins.  Please consider removing from this blocklist
This can be verified with the Granicus team ( see https://granicus.com/solution/govdelivery/ )

**Comment by StevenBlack** [comment]
Hi Mark @mgh128 thank you for this.

Why would local government be using `links.gd` as opposed to using actual direct links? Can you imagine a reason for that?

Your local government's IT department, or its communications team, isn't gonna be setting policy here 🤔

I'm sure you understand.

Closing.

**Comment by mgh128** [comment]
Hi Steven @StevenBlack 
I don't know why they do it.  I don't like opaque URLs any more than you do.  

I'd much prefer that local government just use straightforward transparent links to their own website instead of redirections via lnks.gd.  It seems that they've been tricked into thinking that it matters which e-mail newsletter generated the click and paying public money for a service they probably don't need anyway.  At least the JSON Web Token payload doesn't appear to be tracking each recipient (yet!), though such an opaque URL is an ideal mechanism to do so.

Thanks for considering the feedback.  No problem about not removing it from the list of suspicious domains.

**Comment by rvaessen** [comment]
Some might think that the Federal Gov't are 'scammers', but the VA (Veteran's Administration) newsletters that I receive all use lnks.gd URL shorteners, so I've had to whitelist the domain on my pi-hole. I wonder how many veterans (like me) can't get to the VA resources that they need because your blocklist/denylist is preventing them from accessing the resources they need. I also receive newsletters from my local Arapahoe County government that use lnks.gd link shortener.

**Comment by rvaessen** [comment]
Ler762 - Despite your acerbically worded response... I did find parts of your reply helpful. I read the information provided at the site you linked to/referenced, and I did some additional research for link expanders, decrypters and analyzers. I know how to 'show-all' or reveal the source of any email in my inbox, so I decided to use that function in order to avoid clicking on the lnks.gd links. I don't like the tracking either (that's why I'm using a pi-hole), but I also realize that most people don't know how to view and/or ready the source of an email message or any of the HTML/coding behind the pretty pictures in their inbox. I too wish my government (federal and local) wouldn't use any of these 'tracking' and 'analytics' services.

I have taken the links.gd domain off my pi-hole white list, and will do my best to use the 'view-source' of whatever email client I'm using (although that's not easy to find in every case) in order to find the actual URLs hidden behind the shorteners and obfuscation.
