### ISSUE TITLE
imasdk

### ISSUE THREAD

**Issue by trackerct** [StevenBlack/hosts#2132]
imasdk.googleapis.com
The IMA SDK is a Google Ads SDK that allows developers and publishers to show interactive and video ads on their websites and mobile apps.

veve.com
A PERFORMANCE MARKETING PLATFORM TO REACH CONSUMERS THROUGH OEMs AND BROWSERS

adhouse.pro
Adhouse Digital Media Advertising and Research

cleveradvertising.com
In the industry for 15 years, we serve 13+ iGaming operators through Media Buying, SEO, PPC, and Influencer Marketing spanned over 5 continents.

www.adsblue.net
ADS - The best of digital advertising!

pirsch.io
Pirsch is a simple, cookie-free, and open-source web analytics solution that easily integrates into your website or backend.

nowin.mobvista.com
Mobvista is committed to providing global developers with advertising and marketing

tracking.bi.psafe.com
adserverapi.psafe.com
dfndr  antivirus -tracker-ad
https://play.google.com/store/apps/details?id=com.psafe.msuite

a.privacity.se
[Plausible Analytics](https://plausible.io/)

services.insurads.com
tpsc-video-eu.doubleverify.com
tpsc-eu3.doubleverify.com

have a nice day!

**Comment by StevenBlack** [comment]
Hi @trackerct thanks for this input.

Two things.

Firstly, we don't block root domains unless those domains are used to vehicle adware, crapware, or worse.  We are absolutely NOT de-platforming companies just because they are in the advertising business. Can you imagine the legal blowback from that??

Secondly, we're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
