### ISSUE TITLE
Windows 10 taskbar doesnt work

### ISSUE THREAD

**Issue by ghost** [StevenBlack/hosts#2138]
I added the raw file to my hosts and made the windows taskbar to not work. Start menu is grayed out, cant right click or anything with it.
I tried removing the "Windows 10" section of the file, but it didnt work either. Idk which specific domain is doing it.

**Comment by StevenBlack** [comment]
Hello @cieres thank you for this.

Are there any Windows users experiencing this, or something similar?

**Comment by CANADIANPIG** [comment]
Hello,
I am experiencing the same issue. If I were to reboot after updating my hosts file, explorer.exe would be completely frozen and my internet connection fails. I did not realize that this hosts file change was the cause, so I ended up reinstalling Windows 10 entirely thinking it was NordVPN's software. When the same issue occurred on my new installation, I reverted my hosts file to blank and it resolved the issue.

**Comment by rautamiekka** [comment]
> I reverted my hosts file to blank and it resolved the issue.

A blank `hosts` will cause other problems, though, so don't make it totally empty.

**Comment by Mustaf2501** [comment]
How do I fix this? My laptop is totally frozen on startup.

**Comment by rautamiekka** [comment]
My file says that localhost is handled in DNS, so I ain't totally sure if it's necessary, but it sure won't hurt to have the basic localhost lines in there:
```
127.0.0.1	localhost
::1	localhost
```

**Comment by dshemetov** [comment]
Windows 11 user here. Having the same crippling slow down for the first 5 minutes of rebooting the machine. DNS Client Network Service takes up only about 10% CPU, RAM, but querying sites clearly doesn't work, explorer search doesn't work, causes other apps to crash.

Assuming this is related to the large size of the hosts file and the DNS cache service on Windows, as mentioned in the README.

**Comment by MultiKoopa** [comment]
> Windows 11 user here. Having the same crippling slow down for the first 5 minutes of rebooting the machine. DNS Client Network Service takes up only about 10% CPU, RAM, but querying sites clearly doesn't work, the whole explorer process is heavily taxed (search bar, file navigation, system tray barely respond), and many other startup apps hard crash.
> 
> Assuming this is related to the large size of the hosts file and the DNS cache service on Windows, as mentioned in the README.
> 
> I had the DNS caching service turned off for a couple years and the mostly-default hosts file here worked fine. Had to re-enable caching because WSL2 installed from the Microsoft Store crashes otherwise (see [this comment](https://github.com/microsoft/WSL/issues/7669#issuecomment-983836030)).

Ah. Seems I've finally found a solution to this annoying boot issue, but would have to give up WSL2 in the future. Guess I'll take it for now.

**Comment by stefanopini** [comment]
This seems related to #411 . In that case, the `--compress` option should help (but not totally solve the issue given the current huge list of domains)

**Comment by MultiKoopa** [comment]
> This seems related to #411 . In that case, the `--compress` option should help (but not totally solve the issue given the current huge list of domains)

how exactly do you use this option?

**Comment by stefanopini** [comment]
I usually generate the hosts file following this [option](https://github.com/StevenBlack/hosts#option-3-generate-it-in-your-own-environment), running the command with the following flags
```
python3 updateHostsFile.py -b -k -c -m -e <extensions you want to include>
```

The command generates a new hosts file that contains up to 9 domains per line, improving the loading time on Windows.

**Comment by dshemetov** [comment]
Thanks @stefanopini, the compressed hosts file is actually useable on my machine!

**Comment by sudarpo** [comment]
Sharing my experiment so far as I faced similar issues (especially during Windows startup).
PC Spec: Windows 10 22H2; AMD Ryzen 5 5600X; 48GB RAM; 

# With DNS Client **enabled**
I faced similar issues (especially during Windows startup), such as:
- Internet connection is not working during startup
- network internet icon in right bottom corner taskbar is showing as no internet connectivity
- high disk usage
- DNS client service is showing high CPU usage > 10%

Initially I always generate hosts file with `--extensions porn fakenews gambling --compress` parameters enabled. This generates 234,203 entries for me.
Then I tried removing `porn` extensions, and regenerate to get 187,322 entries.
This works for me during startup, I had faster turnaround for 'network internet icon'.

# With DNS Client **disabled**
I also tried turning off / disabling DNS client.
Using 234,203 entries, windows startup has no issues - 'network internet icon' shows up connected immediately.

Problem occurs when I started Google Chrome / MS Edge Chromium. CPU peaks almost immediately at 100%.
Chrome background service: `Utility Network Service` is showing very high CPU utilization.

When using Firefox, I didn't encounter high cpu utilization.

--- 
Summary / Bottomline:
- I guess I will stick with DNS client enabled with hosts file that is less than 200,000 entries. 
- `compress` option is a must for Windows
- Get additional protection with 'ublock origin' - sorry, I'm not endorsing this, but I'm quite happy using this extension for all my browsers usage.

**Comment by mrajema** [comment]
I have the same issues when I want to block all Windows domaine, but I have blocked windows using linux firewall on this time with iptables.

**Comment by pshlos46** [comment]
had the same issues. windows 10 with DNS cache service disabled, seems unusable. Browsers/IM run CPU usage through the roof every 10 seconds. I'll try the compressed version and see how this fares. (i7-4700K). Also since I use WSL2, I cannot actually disable DNS cache. 

Are there any stripped limited versions? I've used stephen black's list for years without issues, but I have not updated it for a couple of years and now that I updated it, it seems the size has gone through the roof.

**Comment by StevenBlack** [comment]
> ...it seems the size has gone through the roof.

Tasos @pshlos46 I agree, I'm well aware of the issue.  One of our source lists is responsible for most of that growth. That sais, they are very diligent and responsive.

The real issue here is, Windows is a dumpster fire. No other OS has these problems. Considering Windows' bloat, the irony is not lost on me.

**Comment by pshlos46** [comment]
@StevenBlack of-course I agree 100% that Window's way of handling this, is the problem here and not the large hosts file. 
However, and without wanting to sound disrespectful as I know and understand what a load of work is to maintain and expand this through the years,  I will provide some feedback.

1. It might be good to have a clear warning in the README for Windows users up top or something, that the unified hosts list with 180+k entries, **will** freeze their PC, so to act preemptively by disabling DNSCache (and that this will disable WSL2 and might create high CPU with some browsers). 
I used to recommend this list in the past in a lot of friends/family etc. that were not computer savvy in a "just copy and paste the hosts" and it worked, I won't do that now, but I think it had a lot of value for them even back when it had 40-50k entries.
2. I setup PiHole with the default list (the unified one) and I noticed that i.e. Samsung SmartTV Youtube was not working even though I've whitelisted almost everything in the FAQ section of PiHole. Turns out I had to whitelist something from `samsungcloudsolution.net` that I stumbled upon in the comment section of a gist. I might suggest that the unified list now might be very strict? And create a lot of issues in tv's/mobile devices etc? I think there might be some value in providing a smaller more "mobile/smart-tv/appliance" friendly list, that still manages to block several of the main ads/threats in the internet but without crippling a lot al this new stuff that has to "phone home"

Just my ideas and feedback. Thanks a lot for all your work through the years. :)

**Comment by rwp0** [comment]
The same issue, also the internet is gone, seems like due to DNS.

Running the BAT file there was error that Python's `request` library is not installed.

I think the BAT script should not run at all detecting the absence of such third party library on Windows.

**Comment by iam-py-test** [comment]
> Running the BAT file there was error that Python's request library is not installed.

Open cmd and run `python -m pip install requests`.

**Comment by rwp0** [comment]
I did that but the error isn't gone for some reason even though the package
is installed.

3 iyn 2023, Ş. 21:03 tarixində iam-py-test ***@***.***> yazdı:

**Comment by iam-py-test** [comment]
Did you try it in an *Admin* command prompt?

**Comment by rwp0** [comment]
Of course

3 iyn 2023, Ş. 21:29 tarixində iam-py-test ***@***.***> yazdı:

**Comment by iam-py-test** [comment]
I have no idea. Maybe there is more than one version of Python installed and the script is using that?

**Comment by rwp0** [comment]
> I have no idea. Maybe there is more than one version of Python installed and the script is using that?

No, that's not the case, there is only one python version on my system.

I think there should be notice in that `StevenBlack/hosts` is buggy and therefore dangerous under Windows somewhere in `README`.

I had to delete my `hosts` from Safe Mode (else it's not deletable since being used elsewhere) to un-froze my PC.

I think I need to restore DNS Cache back now, I see that `4` is set in the bat file (`disable-dnscache-service-win.bat`) as the registry key value, but what was the initial (default) value to restore?

**Comment by rwp0** [comment]
> > I have no idea. Maybe there is more than one version of Python installed and the script is using that?
> 
> No, that's not the case, there is only one Python version on my system.
> 
> I think there should be a notice that `StevenBlack/hosts` (ie. the Python script and friends) is buggy and therefore dangerous under Windows somewhere in `README`.
> 
> I had to delete my `hosts` from Safe Mode (else it's not deletable as `being used elsewhere`) to un-froze my PC.
> 
> I think I need to restore DNS Cache back now, I see that `4` is set in the bat file (`disable-dnscache-service-win.bat`) as the registry key value, but what was the initial (default) value to restore?

For those suffering the same issue after disabling DNS Cache, here's the service values to restore:

![image](https://github.com/StevenBlack/hosts/assets/68062695/3d8fe417-13c5-4e07-87b6-9ddc2cabf22d)

https://www.itprotoday.com/windows-78/jsi-tip-0324-registry-entries-services

**Comment by jekv2** [comment]
I cannot use this hosts file, it locks up my win10 machine, luckily I have an app unlocker unlock the hosts file to edit the hosts file back to 127.0.0.1 localhost.

I also disabled dns cache but I found I need that enabled to access my nvidia shield over smb.

**Comment by iam-py-test** [comment]
Not much StevenBlack can do...
Complain to M$ that their operating system seems unable to handle HOSTs files over a certain size (other operating systems can manage it so it's clearly possible) or use this HOSTs file in another piece of software (i.e. PiHole, uBlock Origin, AdGuard Home, etc).

**Comment by jekv2** [comment]
> Not much StevenBlack can do... Complain to M$ that their operating system seems unable to handle HOSTs files over a certain size (other operating systems can manage it so it's clearly possible) or use something like PiHole, AdGuard Home/Windows which can block ads & handles this HOSTs file properly.

i grabbed the rpi 8GB new $75, just got back in stock.
https://www.adafruit.com/product/4564

**Comment by MultiKoopa** [comment]
> I usually generate the hosts file following this [option](https://github.com/StevenBlack/hosts#option-3-generate-it-in-your-own-environment), running the command with the following flags
> 
> ```
> python3 updateHostsFile.py -b -k -c -m -e <extensions you want to include>
> ```
> 
> (`-c` is the short for `--compress`)
> 
> The command generates a new hosts file that contains up to 9 domains per line, improving the loading time on Windows.

dude holy crap

finally decided to try this out, because at this point, Windows was taking more than half an hour to become usable after booting due to the Hosts file. It just took under 30 seconds with the compressed Hosts file. Thank you so much!

**Comment by ScriptTiger** [comment]
I feel this issue has also been resolved. Unless I'm missing something, all of this stemmed from a misunderstanding/slow adoption of the `--compress` argument. Unfortunately, I'm sure Windows users will continue to create issues for this over time, despite it already being documented in the README.

**Comment by StevenBlack** [comment]
Thank you @ScriptTiger I agree!

Closing.

**Comment by MultiKoopa** [comment]
> I usually generate the hosts file following this [option](https://github.com/StevenBlack/hosts#option-3-generate-it-in-your-own-environment), running the command with the following flags
> 
> ```
> python3 updateHostsFile.py -b -k -c -m -e <extensions you want to include>
> ```
> 
> (`-c` is the short for `--compress`)
> 
> The command generates a new hosts file that contains up to 9 domains per line, improving the loading time on Windows.

hey. Thanks a lot for this. Been using it for almost 3 years now. For some reason, it doesn't seem to be working with today's update. The script gets stuck at "updating source data". any ideas why?

**Comment by MultiKoopa** [comment]
> I usually generate the hosts file following this [option](https://github.com/StevenBlack/hosts#option-3-generate-it-in-your-own-environment), running the command with the following flags
> 
> ```
> python3 updateHostsFile.py -b -k -c -m -e <extensions you want to include>
> ```
> 
> (`-c` is the short for `--compress`)
> 
> The command generates a new hosts file that contains up to 9 domains per line, improving the loading time on Windows.

Hi. A question about this. Been super helpful; when I run it, I get several questions in a row requiring a Y or N response. I realized since I started using it 2.5 years ago, I always give the same answers. Is there a way to run the script and automatically give the answers, for lack of a better term? Like Y Y Y N N .
