### ISSUE TITLE
Please add these porn sites

### ISSUE THREAD

**Issue by appeasementPolitik** [StevenBlack/hosts#2182]
https://www.ebookrenta.com/
https://poop.vids.rip/

**Comment by appeasementPolitik** [comment]
@Sinfonietta

**Comment by jheuck** [comment]
https://www.pornv.xxx/

**Comment by jheuck** [comment]
https://eporner.com.es/
https://wargers.org/

**Comment by Muhammad-Furqan-PIAIC-183270** [comment]
https://www.indiansexmms.me/
and many more websites which are not blocked by list.
Please add

**Comment by Muhammad-Furqan-PIAIC-183270** [comment]
Steven Black porn list is very helpful and working. It is kind request to update all Indian porn sites which are open and working.
if there is any procedure to block these please let me know.

**Comment by bigdargon** [comment]
@Muhammad-Furqan-PIAIC-183270 If you are interested in the adult blocklist, please refer to the blocklist I am building https://github.com/bigdargon/hostsVN/blob/master/extensions/adult/hosts

**Comment by Muhammad-Furqan-PIAIC-183270** [comment]
still in this many adult links are opening

**Comment by bigdargon** [comment]
@Muhammad-Furqan-PIAIC-183270 I have split on request here https://github.com/bigdargon/hostsVN/issues/333, only domain names with Vietnamese language will update to this repo. The other domains will not update, the reason is the large number of domains makes the capacity increase. The hosts file won't work!

You can consult the formats and languages via my project repo https://github.com/bigdargon/hostsVN/tree/master/extensions/adult

**Comment by Sinfonietta** [comment]
@StevenBlack I have added all these to my porn list.

**Comment by StevenBlack** [comment]
Thank you everybody, these domains are in the latest release.

**Comment by Muhammad-Furqan-PIAIC-183270** [comment]
many of the indian links are working how to block thease.
indiangirlsporn.net
newindian.vids

**Comment by Muhammad-Furqan-PIAIC-183270** [comment]
> 

are indian liks also updated on stevsen porn list.
