### ISSUE TITLE
Docker command fails to replace contents of /etc/hosts

### ISSUE THREAD

**Issue by AlvinKuruvilla** [StevenBlack/hosts#2188]
When running the docker command in the readme, it fails to update the contents of the hosts file. 

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/46870885/210466740-18a77afd-bbd3-4ba6-a5b4-29bf191191d6.png">

**Comment by StevenBlack** [comment]
Hi Alvin @AlvinKuruvilla thank you for your question.

What are you running?

Here's the segment of Python code that's not working for you.

https://github.com/StevenBlack/hosts/blob/f91285ebe73d82b48875aee2fcd06c20f4566e12/updateHostsFile.py#L1297-L1319

**Comment by AlvinKuruvilla** [comment]
Thanks for your response @StevenBlack, I may be misunderstanding your question but I am running the docker command in the README exactly

**Comment by StevenBlack** [comment]
Hi ALvin, sorry I was unclear. Yes, it's very clear what *command* you're running, that's in the screen shot.

What OS are you running? What version of Python?

**Comment by AlvinKuruvilla** [comment]
MacOs Monterey with python 3.10.9

**Comment by karlbrown-va** [comment]
I have a similar issue; running basically the same command, on OSX Ventura 13.1, with Docker (via Rancher):
Docker version 20.10.21-rd, build ac29474

However, unlike @AlvinKuruvilla, my replace command seems to succeed, but it doesn't actually replace the contents of `/etc/hosts` - this is true whether I run the docker command as `sudo` or not. If I run docker as `sudo` and also the `updateHostsFile.py` as sudo, then it fails with:
`Replacing /etc/hosts requires root privileges. You might need to enter your password.
cp: can't create '/etc/hosts': File exists
Replacing /etc/hosts failed.
`

I think the instructions say the Docker image is for linux only, but have you ever gotten the docker image approach working on OSX? Otherwise I'm thinking of just using the container to generate the file and then moving it to the final location after.

**Comment by AlvinKuruvilla** [comment]
Hi @karlbrown-va, my current approach to the issue was I made a stripped-down clone of the repository with the python file, the extensions folder, and the readmeData.json file. Then I just ran the python script normally, and it seems to work fine
