### ISSUE TITLE
Authentication for MS Teams requires "browser.pipe.aria.microsoft.com"

### ISSUE THREAD

**Issue by PaulTGG** [StevenBlack/hosts#2232]
I'm loathed to write this (I promise I only use Teams because I have to for my job... ha), but

`browser.pipe.aria.microsoft.com`

appears to be required to log in to Teams.  When it's blocked, Teams ends up in a loop that ends with a generic "we can't log you in, try again" error.

(On a side note, there's also a `mobile.pipe.aria.microsoft.com` in the block list.  I haven't tried logging into Teams on mobile, but if anyone else is having issues on mobile, check there first.)

**Comment by sudarpo** [comment]
If you use Microsoft SaaS, it's best that you create your own whitelist. 

Here is my whitelist
```
data.microsoft.com
aria.microsoft.com
smartscreen.microsoft.com
officeapps.live.com
```

**Comment by StevenBlack** [comment]
thank you for this Paul @PaulTGG. And thank you for your input Wei @hiyan.

An other consideration is, we've been listing `mobile.pipe.aria.microsoft.com` for a long time. It's been at least 18-months, likely longer. If this domain was problematic for logging into MS Teams, I would think we'd have heard about that.

**Comment by MaZZly** [comment]
I was having trouble with having to "login again" every morning when I started working.

The "login again/try again"-button never worked (endless loop, showing the same dialogue again after clicking the button and loading the page).

The only thing that worked was to "Clear site data" for `teams.microsoft.com` to be able to log in again. (Dev tools > Application > Clear site data) 

Looking at my PiHole logs, the `browser.pipe.aria.microsoft.com` was being queried and blocked, so I found this issue and decided to try and whitelist the domain.

No issue with having to clear data to login since then... 
This might be related to our Organization's SSO setup to access Teams, but anyway whitelisting the domain seems to have done the trick :)
