### ISSUE TITLE
Issue with localhost

### ISSUE THREAD

**Issue by d-Rickyy-b** [StevenBlack/hosts#2246]
Hi there, since a few days this list blocks access to 'localhost'.

I use [this list](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts) with the ublock origin firefox addon.
Accessing a local dev server or tools like Duplicati is basically being prevented that way. 

![grafik](https://user-images.githubusercontent.com/5798157/221418141-40796ec9-2701-4512-a9f9-c700c829f7b3.png)

Why exactly did localhost land on the list?

Cheers,
Rico

**Comment by StevenBlack** [comment]
Thank you for your question Rico @d-Rickyy-b.

Why exactly did `localhost` land on the list?

Because if it wasn't defined in the `hosts` file, `localhost` wouldn't be defined at all.

It's the presence of `localhost` in the `hosts` file that defines how `localhost` should be resolved on this machine.

So without a `localhost` definition line in the `hosts` file, there would be no meaning to `localhost`.

Every valid hosts file on earth defines `localhost` at the very top of file, on line 1.

Closing 😄

**Comment by d-Rickyy-b** [comment]
Hi @StevenBlack, thank you for your reply and sorry, maybe my issue was a bit misleading.

uBlock blocks any connection to localhost since a few days ago. I did not change any uBlock related setting, nor did I change the lists on my own. Still uBlock suddenly starts *blocking* connections to localhost, which never has been an issue before.

Do you happen to know why that is? Did you change anything related to localhost entries so that uBlock is blocking connections to localhost?

**Comment by StevenBlack** [comment]
Hi Rico @d-Rickyy-b, this hasn't changed in this repo over 10-years. Overall this hasn't changed since the mid-1980's, when ARPANET was a thing.

Note that you aren't calling `localhost` here. You're calling `localhost` over the specific port `8200`.

A lot of things could be blocking that port.  Like, is that port even open and receptive? Is there a firewall layer here? Etc.

**Comment by StevenBlack** [comment]
Rico @d-Rickyy-b for example, I don't have port `80` open on the machine I'm using right now.

I get this:

```
$ curl localhost                                                                                        
curl: (7) Failed to connect to localhost port 80 after 8 ms: Couldn't connect to server
```

Which is normal, port 80 isn't open; I don't have a web server running right now.

Similarly,

```
curl localhost:8200                                                                                   
curl: (7) Failed to connect to localhost port 8200 after 11 ms: Couldn't connect to server
```

Again because I don't have anything listening on local port `8200`.

Note that uBlock Origin doesn't enter here. This ⬆️⬆️⬆️ is thought the local terminal. There's just nothing there.  Nothing is "blocking" localhost, there's just nothing listening on port `80` or `8200` or most other ports.

**Comment by d-Rickyy-b** [comment]
> Note that you aren't calling `localhost` here. You're calling `localhost` over the specific port `8200`.
> 
> A lot of things could be blocking that port. Like, is that port even open and receptive? Is there a firewall layer here? Etc.

As said before, the reason why the connection is blocked is because uBlock seems to interpret the hosts list in a way so that it wants to block non html responses coming from localhost, as can be seen on my screenshot. It's not only the port 8200. That just happens to be the port Duplicati uses. I also had the same issues with my local vscode dev server (running on 5500) which was working fine just until a few days ago. Using the actual loopback IP works fine as well for both of the tested services.

Regarding your second comment: Yes, I figured that my initial request sounded like I am inexperienced. I am aware of the concept of ports and services and IP connections and the whole OSI model :D, honest thank you though for taking the time to explain it.

```
~ via 🐍 v3.8.10
❯ curl --head localhost:8200
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store, must-revalidate, max-age=0
Date: Sun, 26 Feb 2023 19:45:45 GMT
Content-Length: 1906
Content-Type: text/html; charset=utf-8
Server: Tiny WebServer
Connection: close

~ via 🐍 v3.8.10
❯ curl --head localhost:5500
HTTP/1.1 200 OK
Vary: Origin
Access-Control-Allow-Credentials: true
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 13606
Date: Sun, 26 Feb 2023 19:45:47 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

It's just an issue within the Firefox browser where I have uBlock enabled, which (as per my first screenshot) also tells me that uBlock did block the connection. Additionally it only blocks non HTML responses within the browser, which are being served from `localhost`.

But since you already said that the `localhost` entries in the mentioned hosts file did not change, I'll file a bug report in the uBlock bug tracker, since the reason for the problem is clearly uBlock. Maybe its dev can spot why this suddenly happens while it worked just fine for years now :)

Best regards and thanks for your time,
Rico
