### ISSUE TITLE
Hotstar ads block

### ISSUE THREAD

**Issue by AdityaGarg8** [StevenBlack/hosts#2277]
Recently ads on hotstar have started appearing again. Found out that a domain named **akamai.net** is causing the trouble. The problem is that there are many hostnames from this domain as per https://www.netify.ai/resources/domains/akamai.net

Blocking the whole domain breaks ZEE5 for me. So we obviously cannot block the whole thing. But the host names on hotstar are quite random like:

a1814.dscdi3.akamai.net
a1863.dscd.akamai.net
a425.dscv.akamai.net

Whereas on zee5 this is used :

zee5vod.akamaized.net

so I whitelisted the zee5 domain and blacklisted the akamai domains in general, now nothing has broken for me.

**Comment by StevenBlack** [comment]
Thank you for this Aditya @AdityaGarg8. 

Yes we can't blanket-block `akamai` because that would take down a sizable chunk of the internet in userland 😄 

We already list a few `akamai` and apparently related domains. I'm surprised we list so few, actually, considering that Akami is [colossal](https://en.wikipedia.org/wiki/Akamai_Technologies).

Here is a tally of root `akamai` and apparently related domains that we presently list.

```bach
$ ghosts -root | grep akamai

   akamaihd.net: 11
   akamaized.net: 10
   akamai.net: 2
   akamaiedge.net: 2
```
Here are the two `akamai.net` domains we presently block:

```
a1843.g.akamai.net
a50.g2.akamai.net
```

Given your research, I would entertain a Pull Request for the domains you list above. 😄

**Comment by AdityaGarg8** [comment]
The list of host names seems to be endless. Do you know any way to get the list?

**Comment by StevenBlack** [comment]
Sorry Aditya @AdityaGarg8 evidently I was unclear.

A pull request for the small number of domains you’ve already listed ⬆️

**Comment by AdityaGarg8** [comment]
https://github.com/StevenBlack/hosts/pull/2279

**Comment by hagezi** [comment]
@StevenBlack https://github.com/StevenBlack/hosts/pull/2279#issuecomment-1500816046

**Comment by StevenBlack** [comment]
Thank you for sharing that Gerd @hagezi that's helpful.

**Comment by abhijithvijayan** [comment]
@AdityaGarg8 as of today, the ads are served using `hesads.akamaized.net` 

blocking that manually disabled all the ads.

a simple google search for the above domain gave an old thread forum too
https://techenclave.com/threads/pihole-should-be-a-must.195036/page-8
