### ISSUE TITLE
VS Code Telemetry

### ISSUE THREAD

**Issue by JobcenterTycoon** [StevenBlack/hosts#2301]
Visual Studio Code sending telemetry to the following domain

`mobile.events.data.microsoft.com`

The code: https://github.com/microsoft/vscode/blob/73fd3f11032e7b83c2ae011b5516e6ddd19e3db2/src/vs/platform/telemetry/common/1dsAppender.ts

Please take a look and add `mobile.events.data.microsoft.com` to the blocklist.

**Comment by Lateralus138** [comment]
I'm not commenting on whether or not to add this, but is this not what the well established and well maintained VSCodium is for? It's literally VS Code minus telemetry. Just wanted to point that out.

**Comment by StevenBlack** [comment]
Thank you very much for this @JobcenterTycoon. Good catch.

This is very interesting. I'd like broader input on this. Let's let this simmer for awhile.

Gerd @hagezi what do you think? Do you have any insight into the domain `mobile.events.data.microsoft.com`?

**Comment by hagezi** [comment]
Thanks for the ping @StevenBlack.

Yes, it is used for client telemetry. If you disable telemtry in VSCode, the domain should no longer be triggered.

Microsoft has changed a lot in the past regarding telemetry. Because of the different data protection regulations, there are now region-based domains, the complete list of mobile events that I know of:

```
mobile.events.data.microsoft.com
us-mobile.events.data.microsoft.com
eu-mobile.events.data.microsoft.com
au-mobile.events.data.microsoft.com
jp-mobile.events.data.microsoft.com
```
The following domain seems to be used to retrieve the default configuration:
`mobile.events-sandbox.data.microsoft.com`

The telemtry changes can be seen in the following PR:
https://github.com/microsoft/cpp_client_telemetry/pull/1097/files/a5b293bd1b77b264c6bb79b39124f04c53d6c80b

I maintain a native tracker list for Windows and Office, it can be found here:
https://github.com/hagezi/dns-blocklists#native
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.winoffice.txt

Since there have been reports in the past that blocking various `events.data.microsoft.com` caused restrictions in Office 365 online (Office in the browser, Outlook, Teams, online collaboration on Office documents, Office Forms and ...), I only block these domains in my aggressive lists. 
I myself have not noticed any restrictionsin my region (EU), except for the following domains, which have also been removed from my native list:

Breaks Office 365 Admin Center, saving Office documents in the cloud, Windows floods the DNS with queries when blocked:
```
self.events.data.microsoft.com
self-events-data.trafficmanager.net
```

Breaks Windows/XBox Achivements:
```
au-v10.events.data.microsoft.com
au-v20.events.data.microsoft.com
eu-v10.events.data.microsoft.com
eu-v20.events.data.microsoft.com
jp-v10.events.data.microsoft.com
jp-v20.events.data.microsoft.com
uk-v20.events.data.microsoft.com
us-v10.events.data.microsoft.com
us-v20.events.data.microsoft.com
us4-v20.events.data.microsoft.com
us5-v20.events.data.microsoft.com
v10.events.data.microsoft.com
v20.events.data.microsoft.com
```

I hope I could help, greetings,
Gerd

**Comment by StevenBlack** [comment]
Thank you for this detailed insight Gerd @hagezi.  Wow.

To curate is to choose. I'm leaning towards not blocking this.

I'll sleep on it @JobcenterTycoon.

**Comment by hagezi** [comment]
@StevenBlack 

Blocking telemetry should not actually lead to restrictions. However, the past shows otherwise, bad software design or perhaps pure intention. Which, of course, does not mean that it will be the same tomorrow.  Microsoft seems to be making some changes in client telemetry.

I was also unsure whether I should block it in the non-aggressive lists, but after research I decided against it. For people who don't use Office 365 with Cloud, blocking shouldn't be a problem.

**Comment by StevenBlack** [comment]
Thanks Gerd @hagezi I'm very glad I pinged you.

**Comment by JobcenterTycoon** [comment]
So it will not be added to the blocklist?

**Comment by StevenBlack** [comment]
@JobcenterTycoon the issue here is, do we (do I) want an avalanche of complaints due to breaking MS Office and MS Outlook and MS Teams from potentially all quarters?

**Comment by StevenBlack** [comment]
Thank you for your suggestion @JobcenterTycoon. I have decided not to list the domain `mobile.events.data.microsoft.com`.

Closing.

**Comment by stevenya97** [comment]
@hagezi I apologize for necroposting. I noticed this domain being blocked constantly 5k+ entries per day. It seems like this domain is now a part of `Pro`, when it was previously tied to more aggressive lists like `Pro+` and up according to the table you posted at the time. Was there a reason for this addition to `Pro`? Are there any updates based on your findings and knowledge for what it is used for today? I have disabled VS Code's telemetry setting. I've also whitelisted domains like `v10.events.data.microsoft.com` due to potential issues with Xbox achievements, Azure portal, and Windows Defender endpoint. Should this domain also follow a similar diagnosis? Thanks!

![Image](https://github.com/user-attachments/assets/91eaab21-343d-4439-b947-2356057fca6f)

![Image](https://github.com/user-attachments/assets/905c0163-d5a3-4da2-a273-47dad7d9cc59)

**Comment by AdamAnon** [comment]
Hi,

Yup, mobile.events.data.microsoft.com accounts for 32% of blocked domains according to my AddGuard Home dashboard.  I've already ran O&O Shutup 10 and Chris Titus utility but it did nor eliminate those requests. They're getting blocked allright, but I would love to know if I can kill whatever pesky processes are making those requests? Those are all Windows 11 Pro clients and none has Visual Studio installed, no OneDrive, Teams, Xbox, no MS services of any sorts, etc. This a custom build ISO image (using NTLite) that is supposed to have telemetry disable, but it doesn't seem to be the case and these requests have increased in the last coiuple of months. Thank you!

**Comment by bbotz** [comment]
@stevenya97 you wrote "I have disabled VS Code's telemetry setting.". I'd ask how did you do that? Something in my system is pinging mobile.events.data.microsoft.com every FIVE seconds. This madness has to stop...
