### ISSUE TITLE
Block `unity3d.com pinpoll.com supl.google.com supl.vodafone.com nielsen.com klisc.or.ke`

### ISSUE THREAD

**Issue by WebworkrNet** [StevenBlack/hosts#2304]
**Lists in use:**
- Unified Hosts
- Fakenews
- Gambling
-  Porn
- Social

**Client:**
Blokada/Android

**Domains:**
```
unity3d.com
www.unity3d.com
collect.analytics.unity3d.com
events.mz.unity3d.com
operate-sdk-telemetry.unity3d.com
pls.prd.mz.internal.unity3d.com
sdk-diagnostics.prd.mz.internal.unity3d.com

pinpoll.com
www.pinpoll.com
api.dmp.pinpoll.com

supl.google.com

supl.vodafone.com

nielsen.com
www.nielsen.com

klisc.or.ke

```

**Details:**

- https://github.com/badmojr/1Hosts/issues/1246
- https://github.com/badmojr/1Hosts/issues/1274
- https://github.com/badmojr/1Hosts/issues/1277
- https://github.com/badmojr/1Hosts/issues/1278
- https://github.com/badmojr/1Hosts/issues/1283
- https://github.com/badmojr/1Hosts/issues/1286

**Comment by icedterminal** [comment]
What evidence do you have to support the need to include these domains? I'm finding it very hard to accept most of these are necessary on any level.

> unity3d.com
> www.unity3d.com
> pinpoll.com
> www.pinpoll.com
> nielsen.com
> www.nielsen.com

All of these are "No" for obvious reasons.

> supl.google.com
> supl.vodafone.com

If you are unaware, this provides location based services for devices when the more prominent location API is not available (typically Google's API). It's a fall back method primarily used for emergency services (device based GPS). Your carrier can override any blocks in place via their own DNS as these are typically hard coded into the mobile OS... again for emergency purposes. I did a trace on the Vodafone domain and it just points to Google.
```
Non-authoritative answer:
Name:    supl.google.com
Addresses:  2607:f8b0:400e:c09::c0
          74.125.195.192
          74.125.195.192
Aliases:  supl.vodafone.com
```
It is pointless and ill advised to block either of these.

> klisc.or.ke

Is not existent. DNS failure. Tried 1.1.1.1 and 8.8.8.8. 

> api.dmp.pinpoll.com
> events.mz.unity3d.com

Generally a bad idea to block APIs without any sort of evidence to support why you think it should be included. There are a handful of network debuggers you can use to do this. Both of these are used to facility server-side functions for services/software.

> collect.analytics.unity3d.com
> operate-sdk-telemetry.unity3d.com
> pls.prd.mz.internal.unity3d.com
> sdk-diagnostics.prd.mz.internal.unity3d.com

These are all for analytics. However, Unity MZ domains are used for call back functions. This may present a problem with apps if there is a pop-up consent form that never appears. Resulting in an app that can't or won't progress because there is no acceptance or denial.

**Comment by StevenBlack** [comment]
Thank you for your input @icedterminal and thanks for the assist Gerd @hagezi

Denis @WebworkrNet I am closing this, and other issues like this, now.
