### ISSUE TITLE
Only 44% Filtering-Score on d3ward.github.io/toolz/adblock.html

### ISSUE THREAD

**Issue by FingusDE** [StevenBlack/hosts#2310]
Tested your List on my SailfishOS-Mobile, it just scores 44% on this test:

![Bildschirmfoto_20230426_001](https://user-images.githubusercontent.com/48802630/234581698-e364a080-da49-4d92-ae1c-a523fd812906.png)

https://d3ward.github.io/toolz/adblock.html

**Comment by hagezi** [comment]
Such tests have little significance for the quality of a block list, they can at most provide a very rough indication. First of all, I have not checked which domains are not blocked with this list.

You can only use the host file from the test page, then you reach the maximum for DNS, 93%. However, you will then not block many popular ads/trackers and you'll see lots of ads on pages.

Apart from which doamins are tested in this test, they are definitely not all selected according to popularity, the tests are quite inconsistent as far as the result is concerned. The browser cache, the DNS cache of the operating system and other things, perhaps also the humidity, play a role. You have 44%, I had 54%.

In the beginning I often had discussions why this and that is not blocked in my lists. I then tried to explain that these tests are not particularly meaningful. Since I finally got tired of these discussions, I added the host list of the test page to the sources of my lists and now achieve the maximum 93% for DNS. This has not changed the block performance and quality of my lists, because some domains are never accessed. But I have my peace of mind and they are now happy.

**Comment by bigdargon** [comment]
Safari + Adguard + NextDNS

![3D7307F3-2425-4EC1-8B10-DD533FA10C93](https://user-images.githubusercontent.com/10969626/234929934-c6723c72-e8e9-4d4e-a871-21a8babfc199.png)

**Comment by StevenBlack** [comment]
Thank you for this @FingusDE. Thank you Gerd @hagezi for your insight, as well.

The mission of this list is to provide security and an ad-free networked experience for a wide variety of devices and applications.

This list is a curated list of other curated lists.

The goal is not to block everything. That would require a massive list that would not run on Windows machines and devices, for example. A million-element list would render many portable devices functionally useless, or nearly so.

And what happens when one vital domain is blocked? What happens, for example, when a domain critical for MS Office or MS Outlook functionality?  Then what?  We actually discussed exactly this here, earlier this week.

And what about lists that are add-only?  Endless add-only buckets cumulating a million or millions of domains?  That's not what we do here.

**Comment by StevenBlack** [comment]
Closing.
