### ISSUE TITLE
Consider removing "fake news" list? 

### ISSUE THREAD

**Issue by persona5** [StevenBlack/hosts#232]
I don't like where this is going. 
This used to be the best anti-malware, anti-tracking and adblock hosts list out there, but I'm not sure anymore.
"Fake news" list looks really political and usually, when things get political, shit happens. Smells censor-ish.

People tend to imbue their political views in their works, and I'm concerned that this might happen to this repo. Like, inserting websites you don't agree with into unified hosts base to block them, or something like this. I would prefer to have politics as far away from it as possible. 

Can you reconsider and push out politics away into separate designated repository?

**Comment by blaqkr** [comment]
it's not like you must download the list, that's why it has 16 variants.

**Comment by StevenBlack** [comment]
Yes echoing @blaqkr here... 

Fake news is an *extension* to the base hosts file.  You need to actively download the versions that have this extension mixed-in, or explicitly flag it for inclusion if you are building the hosts file yourself using the Python script.

So it's just like the *porn* or *social media* extensions.  You would include those for specific reasons.  *Fake news*, same thing.

Better?

**Comment by inoas** [comment]
The problem with Fake News is what to categorize. And it isn't so easy. Major news sites have been copying faux/hoax/fake news. Facebook and Twitter are the primary source of distribution for Fake News. So you want to put nyt, wp, fb, tw etc on that list?

**Comment by StevenBlack** [comment]
The curator of Fake News is @marktron who's done, and continues to do, a fine job.  He's a reasonable guy.  He's not curating this because it's easy.

Originally both CNN and Fox News were on the list.  As a Canadian, I feel both should probably be listed, but it's a close-call.   I trust Mark.

**Comment by inoas** [comment]
I don't think its a good idea at all, at least not until all major news sites and social networks are listed because they are the primary fake news distributors.

**Comment by StevenBlack** [comment]
@inoas I'm closing this issue now.  Happy computing!

**Comment by inoas** [comment]
@StevenBlack I do value your work highly, but this crosses the line into dark waters.

Obviously you are the maintainer and all I can and want to do is appeal to your critical thought.
People will download the full package and having things like rt.com, CNN or Fox News on the list really shows the inherit issue with this approach.

You can consider later - I hope!

Carpe Diem :)

**Comment by marktron** [comment]
@inoas & @persona5: I understand your concerns, this is something I've been thinking about a lot.

I originally started the block list just for my personal use as a frustrated American citizen during the election. When I published it for others to use, I removed a lot of the sites I had on there (for example Fox News and Huffington Post are both on my personal block list because they don't meet the standards I try to hold for what I consume). I've made an effort to not add sites based on political ideology, but only ones that willfully spread clickbait, hoaxes, propaganda and disinformation. There is obviously a degree of human judgment that goes into that, so I'm always open to suggestions for specific sites that should be added or removed from the list.

RT.com is an interesting case. While it's a large news organization that does report actual news, it also consistently publishes rumors and outright lies in an attempt to give those stories an appearance of legitimacy. One can make the argument certain mainstream US media outlets do the same, but I felt RT consistently does this enough to warrant being on the list. The fact that Donald Trump appears to be trying to give these sites more legitimacy by granting interviews and re-tweeting their stories illustrates how challenging it is to accurately define what constitutes "fake news" in 2017.

One improvement I'm working on is splitting the list up by category so it's easier to ignore parts you don't care about. For example, you'd be able to block sites that deal mostly in Satire/Hoaxes but not Propaganda if that's something you aren't concerned about. It's taking some time to go back and categorize all the items in the list, so it may be a while before I'm able to complete it.

**Comment by ohadschn** [comment]
From the `fakenews` repo:

> Looking at the list, you may notice the vast majority of political sites blocked are far-right conservative in focus. While I would consider myself centrist to left-leaning, I have made a concerted effort to limit this list to sites that meet the purpose listed above

Now let me ask you this @StevenBlack, in all honesty - would you have used a list that read like this instead?
> Looking at the list, you may notice the vast majority of political sites blocked are far-**left progressive** in focus. While I would consider myself centrist to **right**-leaning, I have made a concerted effort to limit this list to sites that meet the purpose listed above

At the very least I would consider _some_ objective factors, such as number of readers. But clearly Mark disagrees: https://github.com/marktron/fakenews/issues/37. Banning Breitbart which has tens/hundreds of millions of readers but not HuffPost or NY Times? Come on...

Now, I don't doubt @marktron's good intentions - many censors truly believe they are helping the people they are censoring, but I think we should strive to make the web _free_, not close it off. We already have enough polarization in the world and on virtually every platform, the last thing we need is some conservative guy forking this repo and replacing the fake news list with its right-wing equivalent...

**Comment by hdntc** [comment]
Any movement on this? A strange move to say the least

**Comment by StevenBlack** [comment]
Hi @hdntc. I closed this issue over six years ago, on Jan 16, 2017.

So no, there is no movement on this 🙃

**Comment by hdntc** [comment]
Fair enough
