### ISSUE TITLE
re-enable yoyo?

### ISSUE THREAD

**Issue by hyder365** [StevenBlack/hosts#2324]
The pgl.yoyo.org source was paused (in data/yoyo.org/update.json) due to the provider blacklisting **t.co**, which is required for clicking Twitter links. Pausing the update was a wise decision at the time, but I'd like to revisit the idea of enabling that list again. It would need an extra one-liner somewhere to remove **t.co** from the result, of course, but we're missing out on what I believe to be a good list otherwise. Any thoughts?

I would also extend this to @pgl directly: Would you consider removing **t.co** so more users and downstream lists can resume making use of your work?

**Comment by pgl** [comment]
@hyder365 Sure, so - add an exclusion for that domain? Do you not have an easy way to do that?

I include domains which are primarily used for ads or tracking. `google.com` is not primarily used for tracking, which is why it's not in my list. My inclusion policy is here: https://pgl.yoyo.org/as/policy.php

**Comment by pgl** [comment]
Oh, hey, I just remembered - you can easily exclude domains from my list by using the `skip` query parameter: https://pgl.yoyo.org/as/formats.php#skip

Example: https://pgl.yoyo.org/adservers/serverlist.php?skip=101com.com,207.net

(Went into a bit of a rabbit hole here: I just went to check this and it wasn't working, because previously it was using the PHP `[]` array assignment format - this was due to caching, so I've changed it to support comma-separated values instead.)

**Comment by StevenBlack** [comment]
Hi Devon @hyder365 yup, gonna do this, just need to sequence this because I've been travelling for the past while and that has messed with my priorities.

**Comment by shunkica** [comment]
@StevenBlack This adlist added the click.discord.com domain to the blocklist which is preventing users from signing in to discord. (You must visit a link on this domain when signing in with a new device as part of 2step verification)

I have reported it to the list admin and this was the response:
```
click.discord.com is a tracker. If you're OK with it tracking you, then
choose Don't Warn Again. It's not preventing anything that doesn't have
an incredibly easy way provided to stop the block happening.
```

**Comment by pgl** [comment]
@shunkica 
<img width="667" alt="image" src="https://github.com/StevenBlack/hosts/assets/1181139/bc81135f-a419-4576-bfbb-3194bd5bf9e3">

Click it. I dare you.

**Comment by pgl** [comment]
@shunkica I mean, that's true, but if you're using a service that doesn't allow you to easily add exclusions to your allow list, then I would suggest reconsidering that service. Blocks are going to happen that don't apply to every single person, the ability to bypass them is a fairly important feature.

**Comment by StevenBlack** [comment]
Hi @hyder365 thank you for those thoughts.

So we're clear: if Discord wants seamless service to their customers, it behooves THEM to behave ethically.

In other words, Discord is not special. We don't serve Discord, nor do we back this particular mode of operation.

The people we serve here are those who do not want be tracked. It's really that simple.
