### ISSUE TITLE
how to dowload hosts file from here

### ISSUE THREAD

**Issue by 1alexman1** [StevenBlack/hosts#2336]
My netguard 2.304 has 0 hosts, even I dowloaded them from its submenu. Is it any method to manually dowload hosts files from here?How to proceed?I apologize for this question but I really don't know.

**Comment by dennisvandehoef** [comment]
Heey,

Have you tried following this guide: https://github.com/M66B/NetGuard/blob/master/ADBLOCKING.md ?

I have no clue about Netguard, though step 4 sounds like you either need to download the file and then select it or you can use a URL.

To download, go to the start page of this repository: https://github.com/StevenBlack/hosts
On your phone, long press the link and then select "Download", you can use the links form the columns `RAW hosts` or `Non GitHub mirror`.
On your computer, simply click the link and then select save in the menu of the browser.

You now have a file that you should be able to use in step 4.
If you can use a link, also use the one from the `RAW hosts` or `Non GitHub mirror` column.

Good luck.
If you still have issues, please give a more precise description of the problem you are facing, so that we can give a more precise advice.
