### ISSUE TITLE
Clean non existent domains to decrease list size

### ISSUE THREAD

**Issue by lf-novelt** [StevenBlack/hosts#2341]
Hello

New to PiHole, I wanted to check randomly check a few domains.

I was surprised most of my tries were obsolete domains that no longer exist

like http://booking.bezdeliv.by

*** dns server  can't find booking.bezdeliv.by: Non-existent domain
![image](https://github.com/StevenBlack/hosts/assets/46479127/356e91f1-51e3-43ab-ba6b-c4a1210618c9)

It should be easy to run a script to test they still exist and remove the ones that don't?
To lighten the lists and get processed faster.

**Comment by StevenBlack** [comment]
Bounjour Louis @lf-novelt et merci pour cette question.

> It should be easy to run a script to test they still exist and remove the ones that don't? 

Yes it's very easy, and no we're never going to do that. Here's why.

Think about how you might engineer a sleeper virus, trojan, or tracker.  Here's how I would do it.

1. Malicious actor develops and deploys a program that "phones home".  Home is a domain with no DNS records (for now).
2. People notice and report details of a process that phones home.
3. Curators add this to their list of potentially malicious domains.
4. Naïve list managers cull these domains because they "don't exist in DNS".
5. Malicious actor activates DNS (for awhile) to assess the distribution of their malware. DNS is repeatedly activated for a short time for assessment, then deactivated for much longer time.
6. Malicious actor continues to gauge the distribution of their malware.  They can do this for weeks/months/years.
7. When the time is right, DNS is activated with the domain that now has a clear unfettered channel to do whatever they've ultimately decided to do over the weeks/months/years their malware has been active, with a free pass by naïve security maintainers.

DNS can be activated at anytime and it only takes a few minutes. With a short record TTL, DNS can be deactivated very quickly too.

So you see, we aren't gonna do this.

Notice something else? only MS Windows has problems with larger hosts files.  Guess who therefore needs lightened lists.

We're never going there. We're going to continue finding a balance that seems to work, without giving a "free pass" to sleeper malware.

**Comment by StevenBlack** [comment]
Closing.

**Comment by lf-novelt** [comment]
cool, thanks for the comprehensive answer, and thanks for the good work!

Bonne journée et bonjour aux canadiens ;)
