### ISSUE TITLE
Just a suggestion...

### ISSUE THREAD

**Issue by mithubindia** [StevenBlack/hosts#2396]
May I suggest  new categories of lists  for ...

1.  Dating sites  // major time pass in office
2.  Jobs sites   // HR will thank you. 
3.  News & Current Affairs Sites  // major time pass in office
4.  Sports Sites // major time pass in office
5.  Shopping Portals //major time pass in office
6.  VPN / Proxy sites  // stop bypassing firewall / router 
7.  Cloud Services  sites  // stop moonlight working from office itself
8.  Web Mail Services Sites  //  stop transferring office files
9.   Torrent Sites  // stop illegal file transfers
10.  Streaming Videos Sites  // bandwidth consuming and time pass sites

**Comment by StevenBlack** [comment]
Hello @mithubindia thank you for this suggestion.

I don't feel that office gatekeeping is a significant segment of our base. Moreover there's an industry built around isolating office networks where hosts files have a necessarily limited place.

Secondly it's one thing to declare categories, quite another to find serious curators to maintain such lists over the long term.

Thirdly, since we amalgamate broad categories of lists, our offerings grow geometrically. I need to keep a lid on that.  I'm not keen on generating and maintaining hundreds of variants. Presently we have 5 basic categories (`n = 5`) which leads to 31 (`(2^n) - 1`) variants already.

Nonetheless thank you for the suggestion, but presently I decline to entertain it for the reasons listed above.

Closing.
