### ISSUE TITLE
please remove false positive (wwwpatreon.com) from the list 

### ISSUE THREAD

**Issue by sefinek24** [StevenBlack/hosts#2405]
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts

**Comment by StevenBlack** [comment]
Thank you for this @sefinek24.  We presently don't list the domain `wwwpatreon.com`.

Closing.

**Comment by iam-py-test** [comment]
`www.patreon.com` is falsely listed, though

**Comment by sefinek24** [comment]
@StevenBlack 👀 https://cdn.sefinek.net/static/12.08.2023/brave_lfOeYMV5sMzD.png
![](https://cdn.sefinek.net/static/12.08.2023/brave_lfOeYMV5sMzD.png)

**Comment by StevenBlack** [comment]
@sefinek24 yes properly identifying the domain you request action upon is kinda clutch.

**Comment by StevenBlack** [comment]
@sefinek24 Patreon is not a false positive for porn. So I must decline this request.

**Comment by sefinek24** [comment]
//:

**Comment by iam-py-test** [comment]
I get there is porn on Patreon, but that's true of any website hosting user content.
I would think the porn list would block websites who's primary purpose is to promote or host pornography

**Comment by yoshimo** [comment]
Patreon is used for a variety of projects and content creators to get money from their communities.
This website has a completely different focus than OnlyFans for example.
Therefore i'd say this doesn't belong to a block list.
You can't block wordpress or googleblogs completely just because of a few "black sheep" and collateral damage

**Comment by sefinek24** [comment]
@yoshimo, I definitely agree with you

**Comment by StevenBlack** [comment]
The domain `patreon.con` appears in the porn extension and is distributed in the porn variants only.

The promise of the porn variants is, it blocks porn.

Yes, Patrion is only partly porn.  You know what else is only partly port?  4chan, reddit/redgifs, and countless others.

This isn't gonna change. Because the guiding principle is, if it vectors porn, it gets blocked.

**Comment by iam-py-test** [comment]
> reddit

Reddit isn't blocklisted.
If "someone has at some time uploaded to porn" is the sole criteria, why isn't X blocklisted? There is outright naked photos on X (NSFW: `https://twitter[.]com/xlilcumprincess/status/1692659678637949406`).
Thanks.

**Comment by krystian3w** [comment]
I think this photo/gif is now private.

Optionally, the Musk 🇿🇦  moderation it off after 4 months.

**Comment by sefinek24** [comment]
> I think this photo/gif is now private.
No, it still exists

**Comment by TylonHH** [comment]
> Reddit isn't blocklisted.

It IS blocklisted!!!

**Comment by iam-py-test** [comment]
I only see `nsfw.reddit.com` listed, though I don't know how Reddit's NSFW/SFW partitioning works (also Patreon was removed)
