### ISSUE TITLE
Add "SS" websites

### ISSUE THREAD

**Issue by ymhcanada** [StevenBlack/hosts#2450]
We would like to request the addition of two website domains associated with Sanctioned Suicide (SS) to the blocklist.

```
sanctioned-suicide.net
sanctioned-suicide.org
```

These domains have been identified as platforms that promote and discuss suicide methods, including those involving substances and gases, as mentioned in the [analysis conducted by the University of Padua](https://thesis.unipd.it/retrieve/3f2c4551-edf3-494f-9fc6-ff39821ac254/Sartori_Elisa.pdf). The analysis highlighted the presence of methods such as Hydrogen Sulfide, Sodium Azide, and Nembutal on the Sanctioned Suicide forum.

While this scenario does not fit into any of the categories on the list you keep, please feel free to close this issue if you believe it is not applicable.

**Background Information:**

Sanctioned Suicide is an internet forum known for its open discussion and encouragement of suicide and suicide methods. The forum has garnered widespread scrutiny for its promotion of suicide.

Wikipedia
https://en.wikipedia.org/wiki/Sanctioned_Suicide

Letter from the Members of Congress
https://trahan.house.gov/uploadedfiles/doj_sanctioned_suicide_letter_final_dec21.pdf

The New York Times investigation
https://www.nytimes.com/interactive/2021/12/09/us/where-the-despairing-log-on.html

University of Padua analysis
https://thesis.unipd.it/retrieve/3f2c4551-edf3-494f-9fc6-ff39821ac254/Sartori_Elisa.pdf

Fix The 26
https://fixthe26.com/category/stop-sanctioned-suicide/

The presence of websites like Sanctioned Suicide, which openly discuss and encourage suicide methods, poses significant harm to online users. These platforms can have a detrimental impact on individuals who may already be vulnerable or struggling with mental health issues. By providing a space for the exchange of detailed information on suicide methods, these websites can potentially facilitate and normalize self-harm behaviors. This can further exacerbate feelings of hopelessness, isolation, and despair among individuals who are already contemplating suicide. Moreover, the exposure to such content can potentially trigger and influence vulnerable individuals, pushing them towards dangerous actions. It is crucial to take proactive measures to restrict access to these harmful websites in order to protect individuals and promote a safer online environment.

**Comment by gaurav-310** [comment]
I have gone through your code and JSON file. You want me to add these websites to the JSON file, which should provide information about what they do, similar to what you have in your 'readmedata.json' file.

**Comment by gaurav-310** [comment]
Can you please assign this issue to me

**Comment by StevenBlack** [comment]
Thank you for this @ymhcanada.

This is a very interesting ask.  Here are my initial thoughts:

We block adware, tracking, and computer malware here.  We also optionally block porn, gambling, social media, and consensus fake news.  Key word there: optionally.

One category we don't block is ideas.  For example, we're not going to block sites that suggest how to launder money, how to make briefcase bombs, sites that promote white power, racism, gay and transexual lifestyles, abortion, or anything like that.

Our mission here is therefore narrowly defined, and that's by choice.  We aren't here to censor the internet.  We're here to protect people's privacy and, optionally, keep some addictive proclivities away.

ALL THAT SAID, I understand what you're asking. I can't begin to imagine the combination of grief and passion that drives your organization. God bless you for that.

So my first impression is, this is not within our mission.

But I'm happy to talk it through, and happy to be convinced otherwise.

**Comment by ymhcanada** [comment]
Thank you @StevenBlack for your thoughtful response to our request. We completely understand and respect your mission to protect people's privacy, as well as the optional nature of blocking specific content categories. We recognize that our request may not be directly related to your current mission. 

To avoid further exposure of the websites in question, I will close this issue and remove the content within it. Once again, thank you for the work you do maintaining this list and appreciate the dedication it takes to uphold its principles.
