### ISSUE TITLE
The Weather Network false positive (images.twnmm.com)

### ISSUE THREAD

**Issue by rnnc** [StevenBlack/hosts#2509]
images.twnmm.com

this domain included in the lists blocks images and video hosting for website https://theweathernetwork.com

**Comment by StevenBlack** [comment]
Thank you for this Rohan @rnnc.  

On what platform are you experiencing this?  Seems functionally fine here on PC.

By the way, the Weather Network doesn't get a free pass here. 

Try this experiment: open a browser window, activate an inspection and watch the network tab. Then open the weather network, and peruse a forecast or two.

Observe: a torrent of heinous inbound garbage, hundreds of network requests. Stopping this nonsense is what we do here.

I'm gonna close this issue because, frankly, we presently don't block enough weather network shenanigans.

So this isn't a false positive but, rather, a reminder that we're not doing enough to control this bad weather network behavior.

**Comment by rnnc** [comment]
sorry getting to this late, but it's happening on PC for me

but i understand the reasoning
