### ISSUE TITLE
tags-eu.tiqcdn.com

### ISSUE THREAD

**Issue by frankrpi3** [StevenBlack/hosts#2513]
Hi!

Blocking the URL "tags-eu.tiqcdn.com" prevents the login on [magentacloud.de](url) as it blocks the cookie and DGSVO popup to appear.
"Magentacloud" is the web based cloud portal from the Deutsche Telekom and it's been used by millions of users.

It would be nice, if you can remove this URL from your list.

best regards, Frank

**Comment by StevenBlack** [comment]
Thank you for this Frank @frankrpi3.

We've talked about the domain `tags-eu.tiqcdn.com` many times before.  See here: https://github.com/search?q=repo%3AStevenBlack%2Fhosts+tags-eu.tiqcdn.com&type=issues

This isn't going to change. 

This issue is Deutsche Telekom's responsibility to fix. They've coded their stuff to fail if `tags-eu.tiqcdn.com` does not respond, and this is their problem, not ours.

Closing!
