### ISSUE TITLE
Please remove www.gstatic.com from StevenBlack/hosts, it is needed by legit sites

### ISSUE THREAD

**Issue by whorfin** [StevenBlack/hosts#2514]
Commit 6fb2c3e added "www.gstatic.com" to `data/StevenBlack/hosts`
This breaks all kinds of things...  For example I could no longer log in to bafta.org until I fixed this in a local copy.

**Comment by StevenBlack** [comment]
Thank you for this @whorfin.

This is fixed in commit 1e6c9deb and will be live in the next release.

**Comment by hagezi** [comment]
@StevenBlack 
The same applies to the `encrypted-tbn*.gstatic.com` domains, see
https://github.com/StevenBlack/hosts/issues/2329

**Comment by goproslowyo** [comment]
@StevenBlack How are you verifying things that are being added to this "curated" list? I think we've lost the meaning of curated somewhere along the way.

You shouldn't be arbitrarily adding unverified sites to be blocked on your list. `gstatic` is one obviously huge mistake, but looking at the referenced commit.... how did you determine that `freecodecamp.org` also needs to be blocked? Because there's nothing inherently malicious about that site but now it's blocked on my network and any network using your list so I'd love to hear your reasoning about how this list gets compiled so I can reason about whether I want to trust both the judgement and curation of this list in my firewall. 

Call to action: Please help me understand why I should continue to trust the maintainers of this repository.
