### ISSUE TITLE
piwik.org is blocked (mvps.org)

### ISSUE THREAD

**Issue by Findus23** [StevenBlack/hosts#256]
The blocking list "MVPS hosts file" you are using seems to be overly strict. (#242)

As an example it blocks piwik.org, which is the homepage of an open source, self hosted google analytics alternative, which is useless as it doesn't track users itself and is just anoying if you want to lookup their documentation.

I'll contact the owner and keep this issue as a reference.

**Comment by StevenBlack** [comment]
Thanks @Findus23.

The Tor browser bypasses local hosts and DNS.

Everyone should have Tor on-hand; this is just another reason for it.

**Comment by Findus23** [comment]
Answer:

>Lukas,
Thanks for the feedback ...
>
>re: and doesn't track users"
>They do attempt to set a cookie ... and that's why it's included ...
>
>You can disable that entry in your HOSTS file by placing a # in front of
>the entry ... then File > Save > Exit
>
>Mike Burgess
Consumer Privacy and Security
"There's no place like 127.0.0.1"
http://winhelp2002.mvps.org/hosts.htm

**Comment by funilrys** [comment]
or exlude it with the script @Findus23

**Comment by millette** [comment]
It was just hit by this too. There is no reason to block piwik.org, I hope you will reconsider and add it to your script or whitelist so it's not blocked in the next release.

I will also contact mvps again and try to convince them too, just in case.

**Comment by StevenBlack** [comment]
@Findus23 so this is exactly the thing.

The whole point of this is to expressly ***not*** be tracked by Google Analytics, Piwik, or anything else.

> It tracks online visits to one or more websites and displays reports on these visits for analysis
> Source:  [Wikipedia](https://en.wikipedia.org/wiki/Piwik)

**Comment by StevenBlack** [comment]
@millette Robin, so this is exactly the thing.

The whole point of this is to expressly ***not*** be tracked by Google Analytics, Piwik, or anything else.

> It tracks online visits to one or more websites and displays reports on these visits for analysis
> Source:  [Wikipedia](https://en.wikipedia.org/wiki/Piwik)

**Comment by millette** [comment]
Sure, you're obviously against the software, but the website itself isn't doing any tracking, nor does it host tracking services.

**Comment by Findus23** [comment]
@StevenBlack 
But blocking the documentation isn’t going to stop this. 
Piwik is Selfhosted which means that every user is going to install it to Piwik.theirdomain.example (or something else)
The domain Piwik.org doesn’t have to do anything with this as it just hosts the information about the software. If you wanted to block the tracking on this page you should be blocking demo.piwik.org and demo2.piwik.org instead as they are the demo tracking instances.

**Comment by ScriptTiger** [comment]
This issue has come up before regarding other analytics providers, such as Google Analytics, the website/docs versus the analytics code itself. "analytics.google.com" is still blocked by yoyo.org, while @mitchellkrogza corrected this on Bad Boyz (https://github.com/StevenBlack/hosts/issues/415). I think this is more of a docs issue on our end to clearly define the goals of this project (https://github.com/StevenBlack/hosts/issues/421) and to standardize it across the end results, possibly curating the local whitelist file to compensate for deviations. From the point of view of the curators, some take the stance of blocking only the code while others have clear intentions to block all related domains, as well. As most do what they do as a passion project, it's better to standardize on our end than to inconvenience the curators and ask them to change their ideals and what it is they are trying to personally accomplish. And in light of recent discussions (https://github.com/StevenBlack/hosts/issues/456), it's clear there can be arguments in any direction as long as nothing is firmly set in stone.

I am also not dissuading anyone from contacting the curators to discuss what they wish to discuss. Being an open-source community, we thrive on open discussion. However, the point of this project is aggregation and not curation, and so having systems in place, be it documentation, local whitelisting, etc., to hold the aggregation to a certain standard would make sense as it relates to this project. I think a good chunk of the recent issues that have been coming in could easily be solved simply by documentation, something solid we can link to and just say, "This is it, this is the rule on that." And if there is a problem with it, we can discuss that rule directly rather than idealizing about multiple things at once without clear focus and an abundance of opinion. We can just set up some starter rules and go from there. It doesn't even matter if they are clearly flawed to start, as discussion is sure to ensue regardless. It could even be something as simple as just drafting up the .github/ISSUES_TEMPLATE.md and .github/PULL_REQUEST_TEMPLATE.md just to give people a quick reference while they are typing up their issue or PR.

**Comment by mattab** [comment]
Hi all,

Please re-consider this issue, as it does not make sense to block "piwik.org" domain itself.

It is the website of the open source decentralised, privacy friendly, analytics platform. It contains documentation, guides, FAQs, has free forums, etc. Removing from the white list will enable people to use our products which help limit the spread of centralised online surveillance, as it is a decentralised platform which help each user keep full control of their data. The piwik.org website does not do any user tracking for other websites. It is not a service provided, just the website to download and learn about the official Piwik project.

-> Would you please remove the "piwik.org" domain from the list?

Thanks,
Matthieu
Piwik founder

from https://twitter.com/RoLLodeQc/status/946139302240636931

**Comment by ScriptTiger** [comment]
@mattab and @millette, can you provide some live examples of the code in question in action to better put people at ease so they can see clearly what you are talking about? What I am about to say is NOT meant to be rude or spiteful, so PLEASE do not take it that way as others have in the past. Users and especially the founder of a service are going to have a biased opinion of that service, so debating it this way is not helpful. If we operate on the facts and debate clear evidence given in the form of live demos, etc., it's much more helpful and can even back you up and serve as a quick reference to link to if you ever find yourself having to make this case elsewhere. @StevenBlack and others do not have experience with your services and don't have time to read all the documentation or test the code itself, but he is a quick study to seeing things in action.

**Comment by Findus23** [comment]
@ScriptTiger I am not sure which code you mean but Piwik is licensed under GPL and the whole source can be found here: https://github.com/piwik/piwik
You can find Piwiks opinion on privacy here: https://piwik.org/privacy/
To sum it up, by default Piwik
- anonymises IP addresses
- respects Do-Not-Track and doesn’t save any data of users who enabled it 
- allows users to set an opt-out cookie which also excludes them from all tracking 
- doesn’t share the data with anyone as it is only stored in the MySQL database of the person who set up the piwik instance

**Comment by ScriptTiger** [comment]
Is there anyway to demonstrate the code live similar to how @xetorixik does in https://github.com/StevenBlack/hosts/issues/430? I know in your case there may not be a tracking file, but just link to a website that is currently using the code so they can just quickly open it up in Chrome dev tools or whatever they're using and check all the sources and what have you to make sure they're okay with everything. It's highly likely your software is completely fine and acceptable, but extra caution is just being taken on their part just due to the fact there are a number of buzzwords they don't normally likely to see in association with the product.

**Comment by Findus23** [comment]
No problem, checking the sources is what open source is for:
You can visit http://issues.piwik.org , a simple website with the default tracking code. 
You can see the data here: https://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=44&period=day&date=yesterday&updated=1#?idSite=44&period=day&date=yesterday&category=Dashboard_Dashboard&subcategory=1 (I’m not sure if it is live or a bit delayed)
You can read through the non-minified tracking code here: https://github.com/piwik/piwik/blob/3.x-dev/js/piwik.js
It is a bit verbose as it needs to support very old browsers that e.g. don’t habe json support
