### ISSUE TITLE
888casino

### ISSUE THREAD

**Issue by triatic** [StevenBlack/hosts#2580]
888casino.com and www.888casino.com appear on the unified hosts list (excluding gambling), but this is a regular gambling site and not malware/adware.

**Comment by StevenBlack** [comment]
Thank you for this Anon @triatic.

You say the domain `www.888casino.com` because... ? What investigations have you conducted, how did you do it, and what did you find?  And we would believe you why?

Regardless, the domain `www.888casino.com` comes to us from upstream. You can make your case with Dan Pollock by email at hosts@someonewhocares.org.

Closing.
