### ISSUE TITLE
cant change my host file contents

### ISSUE THREAD

**Issue by osllepe** [StevenBlack/hosts#2584]
almost no website is loading and on top of that the network is too slow 
i wanted to revert back to default host file but i cant change contents of file 
its says i dont have permission 
i have tried using notepad in admin
have tried making myself adminstaryor priveleges but still not working

**Comment by Lateralus138** [comment]
> its says i dont have permission

It's possible it's in use by *svchost.exe* or it is set to *Read Only* mode in the file's properties (I assume the former).
 - If it's in Read Only mode you change it by right clicking on the HOSTS file and then either clicking `Show more options > Properties` or just `Properties` (depending on which version if Windows you have) and uncheck `Read-only` at the bottom of the 'Attributes' section. This is only a possibility of being the reason, but you can check anyway.
 - If it's in use by *svchost.exe* (which I assume so) then you can either go into *Safe Mode* (which you can look up yourself if you don't know how) and then you should be able to do whatever you like with it. But and easier way would be to use a common *file unlocker* program (I recommend the completely free [IOBit Unlocker](https://www.iobit.com/en/iobit-unlocker.php)). Once installed you can either force unlock & move or unlock & delete the file and replace the file.
 
^ almost no website is loading and on top of that the network is too slow

This is because Windows doesn't deal with large hosts files well, but you have 2 working solutions;

 1. Disable DNS caching service in Services, but ***I DO NOT RECOMMEND THIS METHOD*** as it can break things like WSL and other things. I will not give instructions on that here as it is explained here on this repo somewhere (IIRC) or you can definitely lookup "disable DNS Cache Service in Windows" on you own.
 2. You can compress the HOSTS file using my command line tool (or scripts, but I recommend the C++ tool). You can do so by downloading my tool and reading my instructions in the repository. You would use my tool to compress the HOSTS file to a file in a different folder or different file name, use an unlocker to delete the main HOSTS file in ....\System32\drivers\etc, and then move(and rename of necessary) the new compressed file to the etc folder. It's not really that difficult and there are more detailed instructions at my repository.

As stated before Windows (specifically DNS caching) can't handle too many IP lines. My tool joins up to 9 urls per IP line (instead of 1 url per line) and essentially reduces the caching workload up to 9 times. This works well for myself on many machines and it has worked well for many other as well.

My tool is represented here at Steven's repository README under "Interesting Applications" and you can find the program and instructions at my repository here: [https://github.com/Lateralus138/hosts-compress-windows](https://github.com/Lateralus138/hosts-compress-windows) and the file is in the *Releases* section.

**Comment by StevenBlack** [comment]
Closing this now since this is covered by instructions in the Readme.
