### ISSUE TITLE
Remove imgbox.com 

### ISSUE THREAD

**Issue by fakhamatia** [StevenBlack/hosts#2598]
Why is the entire domain of this site in the list?
The adult content of this site has a special category.

![image](https://github.com/StevenBlack/hosts/assets/20030910/64924a77-e3d0-44da-8b90-13800e39e02e)

**Comment by StevenBlack** [comment]
Thank you for this Ali @fakhamatia.

The domain `imgbox.com` is blocked by our porn lists, and you don't provide any actionable information to improve that.  

Unless `imgbox.com` segregates porn from family content by specific subdomain, we can't do anything about this because of the way hosts files work.

Closing.
