### ISSUE TITLE
add tosdr?

### ISSUE THREAD

**Issue by lucasnuic** [StevenBlack/hosts#2642]
Hey there @tastapod @Voker57 @kant @StevenBlack

ToS;DR do distribute a hosts file blocking any website with an E grade. It can be found at https://api.tosdr.org/pihole/

**Comment by StevenBlack** [comment]
Thank you for this Lucas @lucasnuic.

We definitely will not be doing this.

We try not to block the root domains of businesses.  Like their home pages, for example.  Because we don't employ enough lawyers to deal with that.

We try to block the actual domains used to convey ads, tracking, or worse. This is rarely the root domain, and certainly never the root domains of large companies.

Closing!
