### ISSUE TITLE
couple of ad-domains

### ISSUE THREAD

**Issue by br1an-cloud** [StevenBlack/hosts#2734]
Hello,

I'm submitting the following domains for your consideration to be added to the adware list:

live.trmzum.com
a.magsrv.com
s.magsrv.com

beakpee.com 
proftrafficcounter.com
examplesclasp.com
www.profitabledisplaycontent.com
(source: https://beakpee.com/83e4f6b162b351108cae913a51a6ece1/invoke.js)

yonmewon.com
(source: https://www.malwarebytes.com/blog/detections/yonmewon-com)

fleraprt.com
(source: https://www.netify.ai/resources/domains/fleraprt.com)
the following hostnames seem to belong to the same "network":
pushimg.com
lalapush.com
pushpong.net
fleraprt.com
flerap.com
publpush.com
notix.io 

t.seedtag.com
shb.richaudience.com
t.adx.opera.com

**Comment by StevenBlack** [comment]
Hello for this Brian @br1an-cloud.

We already list the domains `t.adx.opera.com` and `t.seedtag.com`.

But aside from that, most of the others are root domains.  Root domains are problematic because most (almost all) ads are served via subdomains. Since hosts file mechanisms don't support wildcards, and don't cascade, blocking root domains actually serves no practical purpose.  Example: we don't block `google.com` even though Google serves ads. And if we blocked `google.com` that would block exactly zero ads, but cause all kinds of other potential problems, and lots of blowback.

Moreover root domains are often the main portals for legal businesses doing perfectly legal activities that happens to be advertising. Have you ever dealt with someone else's officious legal counsel? I have. 

Let's not go there. I just don't want to go there unless it's certain that a root domain is a direct vector for serving ads.  I'm not getting that vibe from this issue.

I'll leave this open for awhile, if you feel like making the case for each root domain you suggest.

**Comment by StevenBlack** [comment]
Seeing no reply from Brian @br1an-cloud, I'm closing this now.
