### ISSUE TITLE
The difference between 127.0.0.1 and 0.0.0.0

### ISSUE THREAD

**Issue by sy618** [StevenBlack/hosts#274]
I would like to ask, why is the use of hosts 0.0.0.0 rather than 127.0.0.1? What are the benefits of comparing 127.0.0.1?

**Comment by jjaaccoobb** [comment]
Its meaning varies by context. For this project, this excerpt explains it. 

"0.0.0.0 is a non-routable meta-address used to designate an invalid, unknown, or non-applicable target (a ‘no particular address’ place holder)" 

https://www.howtogeek.com/225487/what-is-the-difference-between-127.0.0.1-and-0.0.0.0/

**Comment by Jezza-x3** [comment]
If you actually read the readme you would see. Since you're so lazy I just copied and pasted from it.

We recommend using 0.0.0.0 instead of 127.0.0.1

Traditionally most host files use 127.0.0.1, the loopback address, to establish an IP connection to the local machine.

We prefer to use ``0.0.0.0`, which is defined as a non-routable meta-address used to designate an invalid, unknown, or non applicable target.

Using 0.0.0.0 is empirically faster, possibly because there's no wait for a timeout resolution. It also does not interfere with a web server that may be running on the local PC.

**Comment by sy618** [comment]
I see！
Thank you very much for answering. @jjaaccoobb @Jezza-x3
