### ISSUE TITLE
Standalone pure bocklist to block malwares 

### ISSUE THREAD

**Issue by trimechee** [StevenBlack/hosts#2740]
Hi, i didn't find blocklist dedicated to block malwares, virus,phishing, so we hope please blocklist that only  blocks malwares and esasy to add to ublock origin manifest v2 of firefox, brave, supermium and esay to add to dns provders like rethink dns, dnswarden, ahadns, blahdns ,  thank you : 

these rare security blocklists may help : 

like 

famous quad9 dns blocklist that blocks malwares and and use AI to detect early threats are considered the best secure dns in the world (i don't know if this is the offcial quad9 dns blocklist, i found this quad9 dns blocklist  in the website of german dns callad "dnsforge" and it include quad9 blocklist in harden list of one of its servers:  

https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/quad9_blocklist.txt            

                                                                                               

and maybe  also famous zerodot blocklist to block crypto mining jacking : 

https://github.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists

https://github.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists_browser

and maybe this promising blocklist discovered yesterday:

https://github.com/jarelllama/Scam-Blocklist

https://github.com/tweedge/emerging-threats-pihole
https://hosts.tweedge.net/

and maybe take inspiration from the multiple anti-malware blocklists present in ultimate hosts blacklists :

https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist      

And i add this awesome  blocklist : 

https://github.com/bogachenko/fuckfuckadblock

Thanks a lot

**Comment by StevenBlack** [comment]
Thank you for this Anon @trimechee.

I am aware of all these resources.

Instead of suggesting eight potential lists to carry, with zero evidence, why don't you try picking one list among the eight, and make the case for why we should include that one list.

Because this ⬆️ is more like an information-free, context-free, and motivation-free url dump that says, "Here Steve, you figure out all these URLs I stumbled on."

Again, submitting unfocused issues just wastes my time.  I want to know, which list I should consider, and why.

Closing.
