### ISSUE TITLE
nordvpn.com (root domain) is included in Porn Feed

### ISSUE THREAD

**Issue by AcidSlide** [StevenBlack/hosts#2745]
Why is the main/root domain of nordvpn.com included in the **porn feed**?

Please remove main **nordvpn.com**

Although I'm also scratching my head even **offers.nordvpn.com** is included in the same feed

**Comment by StevenBlack** [comment]
Hello Rikki @AcidSlide thank you for this.

The domain `offers.nordvpn.com` comes to us from upstream, in the someonewhocares.org list.

The maintainer is Dan Pollock, who is always very responsive to things.  You can reach him at hosts@someonewhocares.org.  In your email, you'll need to make the case why domain `offers.nordvpn.com` should not be in his list.  "scratching my head" probably is not gonna cut it, because Dan really knows what he's doing.

**Comment by StevenBlack** [comment]
Rikki @AcidSlide the domain `nordvpn.com` no longer is appearing in the porn lists as of the latest release.  Thanks for that.

Closing.

**Comment by AcidSlide** [comment]
@StevenBlack thanks for the fast response
