### ISSUE TITLE
False positive detection by windows defender

### ISSUE THREAD

**Issue by SobusaDriver** [StevenBlack/hosts#2775]
After downloading the last release windows defender detects the zip file as a trojan named `Trojan:Script/Wacatac.B!ml` with the next mesage:
![image](https://github.com/user-attachments/assets/22f76973-8449-4ae6-9e44-40cb0de82e0c)

**Comment by StevenBlack** [comment]
Thank you for this Keneth @SobusaDriver.

This is a false positive assessment by Windows Defender.  I'm not sure what you should do to report this to Microsoft, but there is certainly not much we can do about that here.

Nonetheless, thank you for the heads-up!

Closing.

**Comment by Lateralus138** [comment]
@SobusaDriver

The hosts file would be different from a normal (executable bins) false-positive submission (especially since it's an ever changing text file) I believe, but yeah, it's a pain in the butt to report false-positives to Microsoft.

I do have a feeling that since it's more about the detection of an alteration of a system file and not about a program there's not much that can be done as MS would have to change their system and not white list the file so I don't recommend wasting your time.

If you want to attempt to do so anyway you can follow the instructions found here: [https://learn.microsoft.com/en-us/defender-xdr/submission-guide](https://learn.microsoft.com/en-us/defender-xdr/submission-guide).

I've only ever attempted to submit excutables so I'm not sure how it will go for you. You don't actually submit the file directly, you submit the whole Defender log archive and they analyze everything involved with the detection.

**Comment by StevenBlack** [comment]
As always, thank you for the assist Ian @Lateralus138!
