### ISSUE TITLE
IDEA: New category "Mixed"

### ISSUE THREAD

**Issue by dev-elian-aav** [StevenBlack/hosts#2779]
Hi! I think a good addition would be a mixed category. My proposition is removing Whatsapp and Linkedin from social and move them to this new category, maybe adding YouTube to this one. Or some sites like the AI ones with NSFW potential, but that would be far too mixed and would create new issues.

**Reasoning**

My reasons are that: a) Whatsapp is a instant messaging service b) Linkedin is also for job seeking. c) Could help with blocking sites that not all users agree in what category they fall.

**Comment by Lateralus138** [comment]
Not that I have a say in any of this, but I feel compelled to interject my opinion; there are too many different opinions/ideas on what goes where and what justifies (in|ex)clusion to justify anything like this. Where would it begin and where would it end? This would be a jumbled mess. At the point where too many opinions are involved it is then up to the end-user to compile/(white|black)-list there own lists from the source list. You can write your own scripts. I personally might even write a universal script/program to strip|add items to the base file based on separate (in|ex)clusion lists files, but I don't think it's a good idea to start having countless "mixed" lists as countless it would probably end up being. Just my two cents...

**Comment by StevenBlack** [comment]
Hi Elian @dev-elian-aav and thank you as always Ian @Lateralus138 for the assist.

Elian I have imaginary archetypal users for each of our lists.

For the social media lists, my archetypes have two flavors:

1. People with social media addictions who want a reliable way to block social media temptations.
2. Parents who feel compelled to protect their kids from the internet, or prevent certain facets of the internet from entering their homes.

This ⬆️ is because we have to draw the line somewhere.

I think drawing fuzzy lines just leads to problems. These archetypes help to keep the lines sane and consistent.

Nonetheless, thank you for your views on this. I think your views are valid, but the day-to-day implementation is, in my experience, problematic.

Closing.

**Comment by dev-elian-aav** [comment]
Thanks @StevenBlack & @Lateralus138 for your responses. I agree this idea would bring new problems, I will follow @Lateralus138 advice on writing my own scripts for solving this issue. Have a good day!
