### ISSUE TITLE
Youtube blocks playback with unified hosts file

### ISSUE THREAD

**Issue by vassijoseph** [StevenBlack/hosts#2790]
I am using Firefox with ublock and the host file here
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

Something in this list triggers youtube and it blocks playback
If I turn ublock back to default settings the block gets resolved and videos play normally

**Comment by StevenBlack** [comment]
Thank you for this @vassijoseph.

Is anyone else experiencing this?

YouTube plays fine for me using Firefox on MacOS.

**Comment by Lateralus138** [comment]
I just tested on Windows, Ubuntu, and Android all in Firefox, all using not only ***Ublock Origin***, but system wide versions of the *hosts* file directly in Windows and Ubuntu and a DNS client using NextDNS with your main hosts file as it's source. All versions play YT videos just fine.

I did read somewhere not too long ago that YT was going to be implementing some way to limit account usage if found to be blocking ads, but I have yet to personally see any repercussions from that and I have not followed up on it since. Will do so sometime this coming week.

**Comment by vassijoseph** [comment]
@StevenBlack I don't know what, if anything, changed but now it works without blocking

Maybe ublock added something that blocks youtube's blocking, maybe it was something random
Since lateralus says they were using the hosts file directly on windows I doubt it's anything to do with ublock changing something but in any case it seems like the problem no longer apperas

**Comment by StevenBlack** [comment]
Thank you for the update @vassijoseph and thank you Ian @Lateralus138, as always, for the assist.
