### ISSUE TITLE
Pick, config a Python code linter

### ISSUE THREAD

**Issue by StevenBlack** [StevenBlack/hosts#298]
Arising from PR #297: it would be nice to involve a Python linter in this repo.

**Comment by gfyoung** [comment]
You can use `flake8`, which you can install with `pip`.  I'm putting up a PR to fix all linting errors in `updateHostsFile.py`.

**Comment by gfyoung** [comment]
If you want to enforce these style errors, what you could consider is hooking up your repository to a CI service (e.g. Travis) to perform style checks on all PR's before merging.

**Comment by StevenBlack** [comment]
Nice suggestion.

**Comment by gfyoung** [comment]
@StevenBlack : I have a branch that implements style check testing on Travis.  <a href="https://travis-ci.org/gfyoung/hosts/builds/232629321">Here</a> is one where the builds fail the style checks.  <a href="https://travis-ci.org/gfyoung/hosts/builds/232629794">Here</a> is one where the builds pass the style checks.

If that looks good to you, I can put this up as a PR, though you will have to link your repository to Travis (since you own the repository).

**Comment by StevenBlack** [comment]
Looks good @gfyoung.  If you submit the PR then I'll link `flake8` through Travis.

**Comment by gfyoung** [comment]
@StevenBlack : PR submitted, though Travis isn't triggering.
