### ISSUE TITLE
Confused about submitting suggestion

### ISSUE THREAD

**Issue by paxperscientiam** [StevenBlack/hosts#332]
Hello, thanks for this amazing collaborative product. It's super.

I'd like to start making contributions, though I'm unsure how to go about it. Should I contact the curator or should I submit a PR?

For instance, I think `holylandnutrition.com` falls under the category of "fakenews." What is the expected way to suggest this?

Thank you.

**Comment by StevenBlack** [comment]
Hi Chris @paxperscientiam,

Yes, I understand that it's currently not obvious who is curating what since the Github home page is for the plain-vanilla hosts file with adware and malware only.

If you go deeper into the docs, to a page for hosts that include Fake News, like [this page for example](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews-porn-social/readme.md#sources-of-hosts-data-unified-in-this-variant) therein is listed all the repos, with links, that make up that variant.

To answer your question directly, [Mark Allen curates Fake News](https://github.com/marktron/fakenews).

I'm open to suggestions about how to list all the sources for the various variants of hosts files on the project home readme.

**Comment by paxperscientiam** [comment]
Thank you @StevenBlack 👍
