### ISSUE TITLE
bad address at /etc/hosts line 5

### ISSUE THREAD

**Issue by Ackis** [StevenBlack/hosts#333]
Noticing this in my error.log:

`Jun  3 15:19:44 ubuntu dnsmasq[28680]: bad address at /etc/hosts line 5`

I'm running dnsmasq 2.75
`Dnsmasq version 2.75  Copyright (c) 2000-2015 Simon Kelley`

```
>lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

Here's the first few lines of /etc/hosts:

```
# This hosts file is a merged collection of hosts from reputable sources,
# with a dash of crowd sourcing via Github
#
# Date: June 03 2017
# Number of unique domains: 36,247
#
# Fetch the latest version of this file: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
# Project home page: https://github.com/StevenBlack/hosts
#
# ===============================================================

127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
255.255.255.255 broadcasthost
::1 localhost
fe80::1%lo0 localhost
0.0.0.0 0.0.0.0
127.0.1.1 ubuntu
127.0.0.53 ubuntu

# Custom host records are listed here.
```

I update my hosts file via cron:

`0 0     * * *   root            /usr/bin/python /opt/hostupdate/updateHostsFile.py -a -r -f 2>&1 | /usr/bin/logger -t UpdateHosts`

Not sure what else I could provide. Could just be my system, or something more common? Doesn't seem to have any issues though.

**Comment by StevenBlack** [comment]
Hi John @Ackis thanks for this report.

One clarification, please: does the flagged line include the first blank line?

I'm trying to understand if the problem, line 5, is

    255.255.255.255 broadcasthost

or

    ::1 localhost

**Comment by Ackis** [comment]
Good question. It looks like the actual line that's causing the error is:
`#fe80::1%lo0 localhost`

I'm not really sure how I got line 5 - I'm not seeing it in the logs anywhere. Sorry for that misdirection

Played around with the hosts file manually - this gave the error at line 7:

```
# ===============================================================

22.2.2.2 foo.com


127.0.0.1 localhost
127.0.0.1 localhost.localdomain
```

This gave no error:
```
# ===============================================================
127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
#255.255.255.255 broadcasthost
#::1 localhost
#fe80::1%lo0 localhost
#0.0.0.0 0.0.0.0
#127.0.1.1 ubuntu
#127.0.0.53 ubuntu
```

This gave the error at line 4:

```
# ===============================================================
127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
#255.255.255.255 broadcasthost
#::1 localhost
fe80::1%lo0 localhost
0.0.0.0 0.0.0.0
127.0.1.1 ubuntu
127.0.0.53 ubuntu
```

This gave no error:

```
# ===============================================================
127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
255.255.255.255 broadcasthost
::1 localhost
#fe80::1%lo0 localhost
0.0.0.0 0.0.0.0
127.0.1.1 ubuntu
127.0.0.53 ubuntu
```

**Comment by spirillen** [comment]
@Ackis I'm not sure, it's a thought....

But it could looks like ubuntu have issues understanding the # prefix in front of a 0:0:0:0:0:0:0 aka :: ipv6 address...  maybe some searches can help here..

**Comment by aasril** [comment]
@StevenBlack I'm on Linux Mint 18.3 (based on Ubuntu 16.04) and dnsmasq also has a **bad address** error on a line. By omitting the comments and empty lines my suspect was `fe80::1%lo0 localhost`. I confirmed it by commenting out that line, restarting the service and dnsmasq is stop having the *bad address* error.

![dnsmasq_log](https://user-images.githubusercontent.com/37625377/55764827-5db1b680-5a97-11e9-9efa-ff72d6adea7b.png)

**Comment by StevenBlack** [comment]
Thanks @aasril.

**Comment by StevenBlack** [comment]
This was introduced in commit 012c6a49b, over three years ago, by that @StevenBlack asshole dude.

Anybody have access to a default MacOS hosts file?   I found [this](https://gist.github.com/andretw/e3946bd9c9b4571702e5) but it's 4-years old.  Also, what's in that file matches what I put in commit 012c6a49b.

[This Stack Overflow issue](https://stackoverflow.com/questions/30851101/localhost-meaning-of-fe801lo0) confirms this isn't a bug, *per se*, so why would Mint complain?

Anyone have insight into this?

**Comment by StevenBlack** [comment]
The comments in this [Stack Overflow thread](https://superuser.com/questions/241642/what-is-the-relevance-of-fe801lo0-localhost-in-etc-hosts) are brilliant.

In particular this...

![2019-04-08_23-08-44](https://user-images.githubusercontent.com/80144/55770738-700a0100-5a53-11e9-8655-0b78b9c4aed8.png)

...and this:

![2019-04-08_23-09-26](https://user-images.githubusercontent.com/80144/55770755-7b5d2c80-5a53-11e9-9197-e4b8cc1b28f9.png)

**Comment by aasril** [comment]
Since I saw that you were responding to this issue I've been motivated to find some more info and fixes I could.

The first thing I do was to make sure that I didn't disable ipv6 intentionally or unintentionally in the past. After following three different tutorials which check three different files, I can say that ipv6 is not disable on this machine.

The first possible fix I tried is to add my interface to /etc/network/interfaces with added `inet6` on the line. It didn't work. The second thing I did was to disable dns-over-https proxy that I'm using since in one of my search this was mentioned, but also didn't get rid of the error. The third thing I did was to install wide-dhcpv6-client. After it was installed I added a recommended config, then I also applied a patch for script the application used since it was mentioned that the default script was buggy. This also has no effect on the error.

I should mention that I rebooted the machine after each of try, just in case.

Since this error message seems doesn't have any negative effects on my day-to-day use, I didn't even notice this for more than a couple of years I have this machine. So there it is how far my motivation to the bottom of the problem go :grinning:  I don't have any knowledge to go deeper, though if anyone has some suggestions I'll be happy to try. 

And @StevenBlack, thanks for your hard work maintaining this ever growing lists.

**Comment by dnmTX** [comment]
@aasril the simplest thing you can do is while IPv6 is enabled on your end run `ifconfig` and it will show you every network interface that is. You'll see `lo` which is the loopback for IPv4. If you don't see any `lo0` which suppose to be some sort of loopback for IPv6 that's mean dnsmasq will not be able to read it.
I assume that it's specifically connected to MacOS as i never seen such a thing on Linux nor on Windows.
Probably the bast thing is to be commented with some note for Mac users in order to avoid such a errors.

**Comment by aasril** [comment]
@dnmTX I'm on Linux Mint. Here's the output of `ifconfig` command
```sh
$ ifconfig lo
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1066 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1066 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:133176 (133.1 KB)  TX bytes:133176 (133.1 KB)

**Comment by dnmTX** [comment]
That's just proofed my point that under Linux IPv6 is using `lo` as a loopback and `lo0` doesn't exist there.

**Comment by aasril** [comment]
@dnmTX I understood your points up to this sentences

>I assume that it's specifically connected to MacOS as i never seen such a thing on Linux nor on Windows.

Hey, but I'm on Linux. That's why I clarified that I'm using Linux Mint.

>Probably the best thing is to be commented with some note for Mac users in order to avoid such a errors.

I'm on Linux though, also OP of this issue.

**Comment by dnmTX** [comment]
@aasril that is why i suggested to be commented out as it's not needed for Linux or Windows users with some note for the Mac users to uncomment if they need it. You understand that the lists provided here is very universal and tries to cover all the OS's.

**Comment by aasril** [comment]
@dnmTX now that you've said it like that, i get it. maybe it was only me, but you could have phrased those sentences more clearly.

>I assume that it's specifically connected to MacOS

which one? the error, the line for ipv6 link-local? i thought you're talking about the error, hence my response.

>Probably the best thing is (the line `fe80::1%lo0 localhost`) to be commented(by default.) with some note for Mac users(.)

----------------------------------------------

I'm not picking up on your post just trying to clarify what was my line of thought. and thanks btw, for now I'll just comment out that line.

**Comment by lewisje** [comment]
This is specifically connected to MacOS: https://github.com/StevenBlack/hosts/issues/86

**Comment by StevenBlack** [comment]
Closing this.  Won't fix.
