### ISSUE TITLE
Whitelist this site [www.geckoandfly.com]

### ISSUE THREAD

**Issue by clementine123** [StevenBlack/hosts#337]
Just observed that the unified hosts has an entry for this site. Not sure why was it blacklisted. Can you provide the reason. I don't see any threat visiting that site.

A quick look at other filters shows many sites which are perfectly fine but which are included in your filter like "http://freshwallpapers.info".

Can you explain on what basis are these blocked? I would strongly advise to relook at all your filters and exclude those which are safe.

**Comment by Jezza-x3** [comment]
Unless it's in his small list, it's not added by him. You'll have to find out which source has it added and raise an issue there.

**Comment by clementine123** [comment]
Ok, thanks! Found the culprit. It is "Mitchell Krog's - Badd Boyz Hosts" found at:
https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts

Will contact the developer of this host and check with him. Found many good sites that are blocked in this host.

I would advise that this host be removed from the unified host list. Thanks!

**Comment by zymase** [comment]
Be it this list, be it whatever HOSTS file it may happen that a site is clean, or that we think it is, or that for whatever reason we wish to whitelist it. Of course this can be done by adding a # before the site's entry in the HOSTS file but that will have to be done most likely every time the HOSTS file is updated.

For those who may not know, there's an application called _HostsMan_ which includes an _Exclusion List_ feature: enter the site and it'll remain whitelisted whenever the HOSTS file is updated. Not to mention that the first feature of _HostsMan_ is to aggregate HOSTS files from different sources. _StevenBlack_'s HOSTS file does it marvelously (that's why I use it!) but one may wish nevertheless to add another specific source ( i.e. ZeusTracker at https://zeustracker.abuse.ch/blocklist.php?download=hostfile ) and that's where HostsMan comes in really handy. Cleans redundancies, shifts 127.0.0.1 to 0.0.0.0 and vice-versa, as an option, when updating sources, and more. Really a handy tool for HOSTS management.

**Comment by rautamiekka** [comment]
^ HostsMan is a Window$-only software.

**Comment by zymase** [comment]
@rautamiekka , looks like I'm intoxicated, forgetting that there are other worlds than the one I live on ...

**Comment by Atavic** [comment]
@clementine123 https://github.com/StevenBlack/hosts/issues/336#issuecomment-309190646

**Comment by mitchellkrogza** [comment]
Those were removed June 19 in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/462f3a5b236bdf3bc23fac0bd4cf983b72d81a9d and some other false positives removed in today's https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/00243260650ead64ab9b0226c940601b58d9760c
