### ISSUE TITLE
Issue with 'Unified hosts file with social extensions'

### ISSUE THREAD

**Issue by ghost** [StevenBlack/hosts#367]
I'm using the '_**Unified hosts file with social extensions**_' (http://sbc.io/hosts/alternates/social/hosts) together with a few other sources, all managed by the _HostsMan_ application.

I noticed this morning an issue when _HostsMan_ -- once all sources updated -- showed that about 3,000 entries were missing.

The cause was that 2 entries in http://sbc.io/hosts/alternates/social/hosts were blocked because considered by Hostsman as possible hijacks, for the sole reason they appeared as:
```
#216.34.181.45 s # slashdot.org
#74.125.127.105 g # google.com
```

This blocked following sources. Moreover, the '_**Unified hosts file with social extensions**_' seems uncleaned. I just downloaded it separately (when searching for the two above oddities) and discovered a rather chaotic file. First time this happens. From there on I ignore what source of '_**'Unified hosts file with social extensions**_' included 
```
#216.34.181.45 s # slashdot.org
#74.125.127.105 g # google.com
```

but this should never appear in a Hosts file, even disabled with a "#'

It appears HostsMan took into consideration, logically,
```
s # slashdot.org
g # google.com
```
which is nonsense and broke Hostsman's concatenation/removal of duplicates feature.

EDIT : I found the culprit.

```
**Dan Pollock - someonewhocares.org** AT http://someonewhocares.org/hosts/zero/hosts
#<shortcut-examples>
# As well by specifying the ipaddress of a server, you can gain access
#   to some of your favourite sites with a single letter, instead of
#   using the whole domain name
# It is perhaps a better solution to use Favourites/Bookmarks instead.
#216.34.181.45   s        # slashdot.org
#74.125.127.105	g        # google.com
#</shortcut-examples>
```

I'll have to contact the author of this list, the entries are insane.

**Comment by StevenBlack** [comment]
Salut @zymase, thank you for reporting this.

Dan Pollock – someonewhocares.org – has been providing host files for a very long time.

This is a Hostman bug.  `#` is a line comment, as far as I know.

> Text from a "#" character until the end of the line is a comment, and is ignored. 

Source: http://man7.org/linux/man-pages/man5/hosts.5.html

**Comment by zymase** [comment]
Hi @StevenBlack,

I'm aware of the seriousness of someonewhocares.org, I've used its hosts file long before switching to your Unified Hosts file.

My intent was in no way to discredit Dan Polock, his work, but rather to report an issue, indeed when managing files with the HostsMan application.

I wouldn't say it's a bug but rather related to the way HostsMan operates.
If the line is
`#216.34.181.45 # slashdot.org`
then there is no problem. HostsMan will only consider the entry is a possible hijack because it is neither 0.0.0.0 nor 127.0.0.1

But with
`#216.34.181.45   s        # slashdot.org`
Hostsman considers two entries,
`#216.34.181.45`
and
`s        # slashdot.org`

because
`#216.34.181.45   s        # slashdot.org`
is not respectful of a Hosts file syntax. On the other hand one can indeed say that anything following '#' is considered as a comment and ignored.

OK. Nevertheless, even with a '#' my opinion is that, in a Hosts file, the syntax must be only,
`127.0.0.1 site.ext #comment `
or
`0.0.0.0 site.ext #comment `

Whatever, this is obviously the first such an extra appears in Pollock's Hosts file. With all the respect I have for the author my opinion is that the paragraph,
```
**Dan Pollock - someonewhocares.org** AT http://someonewhocares.org/hosts/zero/hosts
#<shortcut-examples>
# As well by specifying the ipaddress of a server, you can gain access
#   to some of your favourite sites with a single letter, instead of
#   using the whole domain name
# It is perhaps a better solution to use Favourites/Bookmarks instead.
#216.34.181.45   s        # slashdot.org
#74.125.127.105	g        # google.com
#</shortcut-examples>

has not its place in a Hosts file. This is an explanation paragraph when one expects a Hosts file to include pertinent lines with address and item, plus comment, no more.

Whatever, I've emailed to pollock@theorem.ca to inform him of this.
Dan Pollock – someonewhocares.org – remains an excellent source, that is not the problem.

**Comment by rautamiekka** [comment]
Where do you suppose that shortcut example can be found then ?

**Comment by zymase** [comment]
> Where do you suppose that shortcut example can be found then ?
On the author's site. Yhere are xeveral Hosts file providers which explain extensively what a Hosts file is, what it can and cannot perform, but they explain it independently of the Hosts file itself.

I don't want to be puritan, and I do agree that, basically, everything which follows a '#" on the same line, in a Hosts file as in many coding contexts (if not all) is considered as a comment. If we start arguing on the rights then we may remain formal and accept such a thing as 
`#216.34.181.45   s        # slashdot.org`
in a Hosts file. But IMO -- and not only because HostsMan is affected -- I'd prefer code with code (if you can define a Hosts file line as code) and explanations with explanations. Moreover with very heavy Hosts file (mine is average I guess) all extras take place and can reduce speed. 

It's not a problem without Hostsman, I agree. But but but :)

**Comment by Jezza-x3** [comment]
I use Hostman and everything works fine. Just set it to allow comments and browser hijacks. See if that works.

**Comment by zymase** [comment]
> I use Hostman and everything works fine. Just set it to allow comments and browser hijacks. See if that works.
I've been using HostsMan since as far as I can remember, I know the application by heart.
What I do now is,
Preferences / Import / Comments : Do not import (unchanged)
Preferences / Import / Possible hijacks : Import and disable

Once lists updated, I edit the resulting Hosts file (with HostsMan's internal editor), search for possible hijacks, find and delete the two:
```
s        # slashdot.org
g        # google.com
```
And all is fine.

Side note: I also enable what various hosts files have set to disabled for various reasons most often commented with the following '#'. Why? Well, take my example of sources:

hpHosts-EXP - https://hosts-file.net/exp.txt
hpHosts-HJK - https://hosts-file.net/hjk.txt
hpHosts-PUP - https://hosts-file.net/pup.txt
StevenBlack's Unified hosts file - http://sbc.io/hosts/alternates/social/hosts
ZeusTracker - https://zeustracker.abuse.ch/blocklist.php?download=hostfile
hosts-base - a local, personal list

With those, HostsMan shows something like 30 disabled entries, OK.
If I add host-file.net's ad&tracker list, half of the above disabled entries have disapeared, which means that an entry considered by one Hosts file author as worth being disabled is not by another source. I say, if its on the list and disabled because otherwise it could block my pleasure to surf in peace, I'd rather avoid suspicious entries (disabled) at the cost of my comfort. Beware with disabled entries...

So, we manage the oddity of a Hosts file, which remains most valuable for its content.

**Comment by StevenBlack** [comment]
This is Hostman's bug.
