### ISSUE TITLE
/etc/hosts overwritten + comments and questions

### ISSUE THREAD

**Issue by forthrin** [StevenBlack/hosts#376]
Thanks for a great service! Some comments and questions:

1. Bug: Even though I use the `-s` option,`/etc/hosts` was completely overwritten, erasing vital system and development entries. Please make sure `-s` skips all lines until the first empty line of the file.
1. Request: Please make a Homebrew package so the software stays updated as part of "brew upgrade" rather than having to go in and do "cd ~/somepath/github/hosts && git pull" all the time.
1. Request: After installation, make it possible for the user to instantly write something short and lowercase like "hosts -a" rather than "python ~/somepath/github/hosts/updateHostsFile.py".
1. Request: Ask for sudo password only when the script absolutely needs it (eg. when writing to `/etc`). Otherwise, root owns hosts files created in $HOME, etc.
1. Question: Are the lists so complete that using uBlock Origin et. al. becomes unnecessary?

**Comment by rautamiekka** [comment]
1. No way, you can't assume there won't be empty lines like that. Tbh I'm not sure if a better way would be reading until EOF, an idea I just got.
4. `$HOME` should apply to `root` exactly like to other users.

**Comment by forthrin** [comment]
You could keep everything in `/etc/hosts` up until `# This hosts file is a merged...` (or EOF) and replace from there.

**Comment by rautamiekka** [comment]
^ I suppose that'd be good enough since the Admin should be the one making sure the file doesn't already have bad entries.

**Comment by forthrin** [comment]
Any comment on question 5? And question 2+3, which sort of belong together.

**Comment by rautamiekka** [comment]
^ I can say to 5th this system ain't as complete cuz adblockers can block way more stuff on the spot, especially if using HTTPS since HTTPS normally can't be decrypted outside the web browser, if the hostname/IP can be seen in plain text.

The rest is up to @StevenBlack.

**Comment by ScriptTiger** [comment]
The AutoUpdate script for Windows covers 1 and 2, so you might be able to just mimic that in Python.

1.) It tags the beginning and ending of the Unified Hosts list:
#### BEGIN UNIFIED HOSTS ####
#### END UNIFIED HOSTS ####
It automatically overwrites between those entries every time you update.

2.) Steven Black already includes a "# Date: " line you can just fetch to check the hosts file version since he never changes it multiple times in a day. And if you want to automatically update the Python scripts, you can just include a VERSION file with a number in it to be easily be fetched, as well. The AutoUpdate script also include an emergency stop feature in the VERSION file (just add X in front of the number) to be able to stop the script from updating if Steven is, say, updating the fundamental project structure at the time and it could be dangerous to use the script at all in its current state.

**Comment by forthrin** [comment]
I added `#### BEGIN/END UNIFIED HOSTS ####` after my custom lines in `/etc/hosts` and did `sudo updateHostsFile.py -b -s -n -o /etc`. The whole file was still completely overwritten. No backup was taken either (at least not where I could find it).

As for the updating stuff, this seems a rather complicated ordeal to lay on every single user to figure out. I stand by my earlier suggestions for simpler updating and execution of the software.

**Comment by ScriptTiger** [comment]
Oh, definitely. I stand by that, too. I was suggesting changes to the repo, not for users.

**Comment by forthrin** [comment]
That's good to know :)

`sudo update... -o /etc` overwrites `/etc/hosts` and creates `root staff 0 hosts` in the Git directory. My goal is to update my `/etc/hosts` with a fresh block list, leaving my custom lines at the top alone.

I also noticed that as lists are updated, the Git tree gets soiled, though the files are in `.gitignore`. `git update-index --assume-unchanged <files>` cleans the tree, though this may not be the correct solution .

	modified:   data/KADhosts/hosts
	modified:   data/yoyo.org/hosts
	modified:   hosts
	modified:   readmeData.json
