### ISSUE TITLE
Badd-Boyz blocking pastebin.com

### ISSUE THREAD

**Issue by GLaDOSDan** [StevenBlack/hosts#389]
A recent addition to the Badd-Boyz list has introducted the following three lines:

https://github.com/StevenBlack/hosts/blob/e1287f4357e9f970611f6433183f75f41655a927/data/Badd-Boyz-Hosts/hosts#L5345

````
0.0.0.0 pastebin.com/h0aj4gel
0.0.0.0 pastebin.com/n4anjbnw
0.0.0.0 pastebin.com/qhqa0mxn
````

This results in the Pi-hole software pulling in the list and blocking pastebin.com in its entirety. Is this an issue to be raised here or on the Pi-hole repository?

**Comment by ScriptTiger** [comment]
I would say it's an issue for the Badd Boyz Hosts repo, this repo, and also Pi-hole. Paths shouldn't show up on a domain name list, so someone curating a domain name list should know when something other than a domain name is on their list. But this has happened before from other sources just due to the sheer volume of entries these guys are dealing with and not having time to check every single one personally, so I think the script here and Pi-hole should automatically filter out any entry with anything beyond just a domain name as they are not valid domain names from the start. For the script here, that's a quick and easy grep line to filter out entries containing the "/" character. Pi-hole is not the only software that will hit errors with invalid domain name entries, some DNS servers will also have this problem. But for good measure they should have error-handling to make sure it's taken care off and doesn't cause a problem in the future. "PR requested" tag here?

**Comment by StevenBlack** [comment]
@GLaDOSDan thanks for this.  This is fixed in the latest build.

Closing.
