### ISSUE TITLE
unblock mc.yandex.ru / the devs are not able to use webvisor

### ISSUE THREAD

**Issue by englishextra** [StevenBlack/hosts#402]
```mc.yandex.ru``` is the host for counter script that records user pointer/keyboard events

[https://mc.yandex.ru/metrika/watch.js](https://mc.yandex.ru/metrika/watch.js)

by [Yandex.Metrika](https://metrica.yandex.com/about)

which is a major competitor of GA.

Perhaps a regular user may not want that, but a webdev that use Session Replay by [Yandex.Metrika](https://metrica.yandex.com/about) wont be able to see what their visitors where doing on their sites, and thus the whole service is useless.

So, please, remove, or at least:

```
# [yandex.ru]

# if U use Yandex.Metrika, comment-out mc.yandex.ru 
0.0.0.0 mc.yandex.ru
```

as for ```an.yandex.ru``` yes it hosts API and script for context ads. This very item and others with ```.yandex``` really never bothered me.

**Comment by StevenBlack** [comment]
Hi @englishextra, Google Analytics is blocked too.  That's the whole point of this.

Closing.

**Comment by ScriptTiger** [comment]
@englishextra, while Steven is correct, I do believe you are raising this issue because you are perhaps not aware of how this project works and of all of its features. If you would like to build a list without specific domain names, there is a "whitelist" feature included with this repo which you can add domain names to and they will be omitted from the final result. If you need more help with that, please feel free to ask further. We will be putting together some docs later and all such Q&A will be extremely important for guiding its direction.

**Comment by englishextra** [comment]
@StevenBlack 

> Google Analytics is blocked too. That's the whole point of this.

Gosh, thanks for mentioning Google.

@ScriptTiger Yeah, I need to build it. Now it's clear, thanks.
