### ISSUE TITLE
Convert to IP addresses for use with iptables

### ISSUE THREAD

**Issue by joolz** [StevenBlack/hosts#416]
Not an issue, just something that would be helpful for me. I prefer to not block hosts with /etc/hosts but with iptables (my Ubuntu Touch has /etc/hosts on a read-only filesystem). What I did so far was download yoyo's list and use that one. No problems, only a lot of ad sites slipped through. Then I found this project with lots more hosts, so I used it, like this
```
#!/bin/bash

# first clone https://github.com/StevenBlack/hosts to /opt/hosts

OUTPUT_DIR=/var/www/html
TMPFILE=/tmp/hosts.tmp
HOSTSDIR=/opt/hosts

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

logger $0 Update hosts project $HOSTSDIR
cd $HOSTSDIR || exit 1
git pull -u

PREFIX="/sbin/iptables -A OUTPUT -o wlan0 -d"
POSTFIX="-j DROP"

rm $TMPFILE

logger $0 Parse hosts file
while read LINE
do
	if [[ $LINE =~ 0\.0\.0\.0.* ]]; then
		if [[ ${LINE:8} != "0.0.0.0" ]]; then
			printf "%s\n" "$PREFIX ${LINE:8} $POSTFIX" >> $TMPFILE
		fi
	fi
done < $HOSTSDIR/hosts

logger $0 Remove existing rules
/sbin/iptables -F 

logger $0 Allow established sessions
/sbin/iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

logger $0 Allow http and https
/sbin/iptables -A INPUT -p tcp --dport http -j ACCEPT
/sbin/iptables -A INPUT -p tcp --dport https -j ACCEPT

logger $0 Block ads
source $TMPFILE

logger $0 Set iptables logging
/sbin/iptables -I INPUT 5 -m limit --limit 5/min -j LOG --log-prefix "iptables denied: " --log-level 7

logger $0 Save rules
/sbin/iptables-save > $OUTPUT_DIR/iptables.rules

logger $0 Remove $TMPFILE
rm $TMPFILE

logger $0 Finished
```
Probably there is a lot that can be optimized here but that's not the issue. What happened is that my provider had some script monitoring ns lookups, and it was decided that I was doing suspicious things and I got blocked. The block is removed and they advised that if I want to do something like this I might (temporary) use another dns (eg Google's).

Does anyone have another suggestion? Or is it an idea to include an iptables script in this project?

Thanks for the good work :)

**Comment by rautamiekka** [comment]
A more portable would be to change all explicit references to IPTables binaries to auto-searching ones like so:
```bash
IPTABLES="$(which iptables)"
IPTABLES_SAVE="$(iptables-save)"

$IPTABLES -A INPUT -p tcp --dport http -j ACCEPT

$IPTABLES_SAVE > $OUTPUT_DIR/iptables.rules
```

**Comment by ScriptTiger** [comment]
I like this idea for it's furthering of security, but there are several real problems that should be addressed before being rolled out for public consumption. Similar to the StevenBlack hosts repo, this project would have to do some serious duplicate filtering as obviously many domains are going to share the same IPs. This is more obvious with things like www.blah.com and blah.com sharing the same IP, but maybe not so obvious for those unfamiliar with vhosts and how widespread they currently are on all major web hosts. Also, because of the vhosts issue, you are going to get many websites that share the same IP arbitrarily blocked for having the same IP as an ad provider or what have you. There's also other front-end web services such as Cloudflare which are the face of a website as far as DNS, but behind the scenes proxy to the real IP. So if services like this are blocked, you will also have some very serious issues with a great many sites becoming blocked. And then, of course, leaving the Web realm and getting into other hosted services, like the multitude of app servers out there for games, collaboration, streaming, etc., hosted by the same vendor on the same AWS Cloud and/or getting piped through the same Akamai content delivery networks, things like this are bound to get even more complicated. I think if you do a lot of manual curating to pinpoint these problem IPs ahead of time, maybe using ASN information from a data source like MaxMind (https://github.com/ScriptTiger/IP), this could definitely be an enhancement to security, but not recommended for use by itself. And that is not to say that the StevenBlack hosts is recommended for use by itself either, in the security realm everything is best when complemented.

**Comment by rautamiekka** [comment]
@ScriptTiger is very correct, you have a big problem with blocking with firewall where you're strictly relying on IP addresses (IPTables resolves domains once and sticks to it until you tell to replace the rule).

Use the firewall to block only what you need to and use something more sophisticated for the rest.

**Comment by joolz** [comment]
@ScriptTiger @rautamiekka Sound advice. The only reason for needing this was not being able to write /etc/hosts. The iptables workaround solves that but leaves me with possible erronious results.

Thanks for your feedback!
