### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by kisst** [StevenBlack/hosts#420]
Running the updater from cron the update errors with the following error.
```
Traceback (most recent call last):
  File "updateHostsFile.py", line 1276, in <module>
    main()
  File "updateHostsFile.py", line 152, in main
    update_all_sources(source_data_filename, settings["hostfilename"])
  File "updateHostsFile.py", line 552, in update_all_sources
    update_data = json.load(update_file)
  File "/usr/lib/python3.4/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 27: ordinal not in range(128)
```

The cron line is 
```
/usr/bin/python3 updateHostsFile.py -a -s
```
relevant for 
```
commit 3d027fd436579318152120369ca1818142047db0
```

**Comment by StevenBlack** [comment]
Thanks @kisst.

This line works fine here – [Works Mn My Machine Certification](https://blog.codinghorror.com/the-works-on-my-machine-certification-program/) – using MacOS and both Python 2.7.10 and ython 3.5.1.

Can you tell me a little more about your rig?

I don't understand the reference to commit 3d027fd?  Is this your first issue submit?

**Comment by kisst** [comment]
The reference to the commit is just to tell that I'm few commits behind but not something super old stuff, and also as it used to work before I pulled.

About the rig
```
$ facter virtual lsbdistdescription architecture pythonversion
architecture => i386
lsbdistdescription => Debian GNU/Linux 8.9 (jessie)
virtual => physical
pythonversion => 3.4.2
```
in the meantime I validated and on an interactive shell ( cli on ssh ) it works fine, but on cron it is crashing with the error above.
on cli
```
$ env | grep "LANG\|SHELL"
SHELL=/bin/bash
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
```
on cron 
```
LANGUAGE=en_GB:en
SHELL=/bin/sh
```

**Comment by kisst** [comment]
@StevenBlack do you need more info about the setup, or can I help in any other way to debug this ?

**Comment by StevenBlack** [comment]
@kisst thanks for the offer.  I have no way to debug this here. 

Is anyone else able to reproduce this issue?

**Comment by kisst** [comment]
As I received a daily reminder from the cron daemon to get this fixed I went after it, the issue was the missing `LANG`  environment variable, so for now I patched the cron line to be
`export LANG=en_GB.UTF-8  ; /usr/bin/python3 updateHostsFile.py -a -s `

I hope this help with the debugging, managed to reproduce the error on an active shell,
```
$ /git/hosts$unset LANG
$ /git/hosts$env | grep LANG
LANGUAGE=en_GB:en
$ /git/hosts$/usr/bin/python3 updateHostsFile.py -a -s 
Updating source ./data/StevenBlack from https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts
Updating source ./data/SpotifyAds from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/SpotifyAds/hosts
Traceback (most recent call last):
  File "updateHostsFile.py", line 1276, in <module>
    main()
  File "updateHostsFile.py", line 152, in main
    update_all_sources(source_data_filename, settings["hostfilename"])
  File "updateHostsFile.py", line 552, in update_all_sources
    update_data = json.load(update_file)
  File "/usr/lib/python3.4/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 27: ordinal not in range(128)
```
Not a common use-case I know, but I guess cron can be nice to have.

**Comment by myd7349** [comment]
I also encountered this issue on my PC. Since the default system encoding of my Win10 x64(simplified Chinese) is not utf-8, but GBK.
>F:\myd_backup\hosts>updateHostsWindows.bat
Updating source data\adaway.org from https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
Updating source data\add.2o7Net from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
Updating source data\add.Dead from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Dead/hosts
Updating source data\add.Risk from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
Updating source data\add.Spam from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
Updating source data\Badd-Boyz-Hosts from https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts
Updating source data\KADhosts from https://raw.githubusercontent.com/azet12/KADhosts/master/KADhosts.txt
Updating source data\malwaredomainlist.com from http://www.malwaredomainlist.com/hostslist/hosts.txt
Updating source data\mvps.org from http://winhelp2002.mvps.org/hosts.txt
Traceback (most recent call last):
  File "updateHostsFile.py", line 1276, in <module>
    main()
  File "updateHostsFile.py", line 152, in main
    update_all_sources(source_data_filename, settings["hostfilename"])
  File "updateHostsFile.py", line 552, in update_all_sources
    update_data = json.load(update_file)
  File "e:\ProgramData\Anaconda3\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 30: illegal multibyte sequence

**Comment by ScriptTiger** [comment]
Can a non-volatile PR be suggested for this that would solve the issue for those affected and not cause issues for those not affected, and then we can take a look at it and go from there? It seems like explicitly specifying encoding would keep the environment more uniform from system to system and doesn't sound like it should cause problems, but I'm not the resident expert on these things.

**Comment by bshouse** [comment]
I've got the same issue. The hosts file https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/social-hosts says it has an illegal ascii character # 216854. URLs can be more than ascii (eg. in non-ascii languages for all of Asia) can we change the encoding to UTF-8?

**Comment by notDavid** [comment]
Same error here with https://hosts-file.net/psh.txt line 168754 containing: ```127.0.0.1   www.hualañe.cl```

(macOS 10.13.3, Python 2.7.10)

**Comment by funilrys** [comment]
This can now be (also) closed @StevenBlack :+1:
