### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by ddhelmet** [StevenBlack/hosts#421]
As mentioned in the comments in the hosts file, blocking google analytics breaks several websites. But it is still listed again a couple of times. Is this intended? I deleted them manually to fix my internet issues.

**Comment by StevenBlack** [comment]
Hu @ddhelmet,

Yes, of course this is intended.  

Preventing the tracking of people on the web is one of the many protections of these amalgamated host files.

Closing.

**Comment by kronflux** [comment]
@StevenBlack it might be a good idea to change the readme.md to have the Goals at the top instead of further down, and add a little splur about the intended purpose.
Something about being targeted at privacy and sites with malicious intent.

Just a thought, not sure if it would make a difference with these type of posts xD

**Comment by StevenBlack** [comment]
Hi Richard @kronflux the [goals of this unified hosts file](https://github.com/StevenBlack/hosts) were once at the top of the readme.  The goals section was moved to its current location because I think the operational and installation facets are more immediately useful.

**Comment by ScriptTiger** [comment]
We have talked about a docs directory before to also clarify the intent of certain code structures, as well. And Steven has given positive feedback about that in the past, so I am sure PRs are open and welcome to anyone wanting to contribute to some docs that are in keeping with the standards expected herein.
