### ISSUE TITLE
Please block some web ads

### ISSUE THREAD

**Issue by bigdargon** [StevenBlack/hosts#435]
ants.vn
admicro.vn
adnetwork.admicro.vn
adtima.vn
mobilead.vn
amobi.vn
adx.admicro.vn
adtimaserver.vn
vads.vn
iad.eclick.vn
novanet.vn
adsota.com
adsplus.vn
vietnamnetad.vn
adsvietnam.vn
vietquangcao.com.vn
blinkb.vn
blog-xtraffic.pep.vn
novaonads.com
myad.vn
adtimes.vn
admarket.vn
vietadsgroup.vn
conversion.vn
alada.vn
moore.vn
vmarketing.vn
trenddigital.vn
xhs.vn
infolinks.vn
quangcaohieuqua.net
vietbuzzad.com
polyad.net
miixad.com
vmax.com
qc.coccoc.com
newonads.com
adplay-mobile.com 
adasiaholdings.com
adservice.google.com
adsoptimal.com
newonads.com
media.net
chitika.com

**Comment by StevenBlack** [comment]
Hi @bigdargon we don't do much domain curation here.  We amalgamate curated sources of hosts files.

Curation means there is reasonable updating activity behind each source of host files.

So we can't accept host data unless it comes with a commitment to maintaining that data on an ongoing basis, which means adding to the data, and removing domains that are no longer problematic.

Thank you anyway @bigdargon !

**Comment by ScriptTiger** [comment]
That being said, please feel free, however, to contact any of the ad list curators to check your list for possible integration into their curation processes so that they might handle that maintenance commitment for you. As Steven was saying, the function of this repository is to combine curated sources, while the source curators curate the actual lists.

You can find the contact information for each curator in the update.json file in each of the curation sources:
https://github.com/StevenBlack/hosts/tree/master/data

I have e-mailed several of them in the past and they tend to be very helpful and responsive. If they have a GitHub repository, you can of course create an issue with them there, as well.
