### ISSUE TITLE
Please add BarbBlock

### ISSUE THREAD

**Issue by AdKiller** [StevenBlack/hosts#460]
list of sites which have used legal threats to remove themselves from other blacklists. 

https://github.com/paulgb/BarbBlock

**Comment by StevenBlack** [comment]
@AdKiller oh great, just what I need  😄 

Joking aside, this looks very good, except for one thing.  The BarBlock repo was created on August 12 2017, then saw [a flurry of commit activity](https://github.com/paulgb/BarbBlock/commits/master) for a few days, and nothing since.

So it doesn't appear actively curated, which is one of my criteria for inclusion.

What are your thoughts on this?

**Comment by ScriptTiger** [comment]
I waited for you opinion first, @StevenBlack, and I'll try to keep this brief and limited to one comment, unless further discussion is wanted.

I really like the project and it's certainly a good watch list to reference, but I'm not sure if it's relevant for incorporation into our project, unless the domain admins of the sites listed there are directly reaching out to our sources and feeding them BS of some kind. I am certainly right there with you for the need for your project in general, as I have had plenty of "legal" disputes of BS take-downs and rights claims, etc. But this project is mostly curated by network admins analyzing live traffic and trends and creating block lists from their personal encounters, and many others simply reporting domains that their personal anti-virus/anti-malware/threat protection software detects contain resources (analytics, coin mining scripts, etc.) that this community feels should be blocked. There are currently no laws in place that can dictate to our open-source project what domains should or shouldn't be on the list. We could block Google or Facebook if we wanted to and there is nothing anyone can do about it as we are not contractually obligated to anything of that nature and can run things how we see fit as a community, and the same goes for all of the sources personally curated by individuals and not business entities with contractual obligations, which I believe is the majority of our current sources.

@StevenBlack and @AdKiller, if it would be helpful, I can personally reach out to each of the sources and check with them further about this if they have had any issues or have taken known "baddies" of their lists and restrain from blocking them due to any kind of consumer/legal complaints. Like I said, I know that this can be a very real and legitimate issue in certain circumstances, but I am just not sure if it's a right fit for this particular project.

**Comment by mitchellkrogza** [comment]
@ScriptTiger @StevenBlack Happy New Year and all the very best for 2018 !!

@ScriptTiger certainly an interesting topic, I've personally not had any legal threats of any sort but then I am also very responsive to logged issues on my projects and if a true false positive has entered my list it gets removed after being manually checked first. But if I get an issue logged and I check the site and find unsavory things still going on or continue to find spam tactics from them in my logs, I won't remove them. 

As you say we can block Google or Facebook if we like and neither one of them can do anything about it, even with their massive legal teams and I doubt they would care anyway. So those who are making legal threats to people are pretty much just chancing their luck and lawyers can very easily scare people to do things they want with just one letter containing lots of big confusing words and threats. 

I have in fact got a number of users of my Nginx Bot Blocker who actually use my custom include files to block googlebot, bingbot and other search engines from accessing their sites completely, so it really is up to people what they want to block and nobody's holding a gun to their head to use any of these hosts or blocker lists.

Certainly will keep eyes on the BarbBlock list.

**Comment by AdKiller** [comment]
@StevenBlack it could be a static addon list for now. It's all up to you tho.

**Comment by DavidCWGA** [comment]
BarbBlock may not have been updated in a while but it still contains sites which are not in EasyList, or this list, so it still seems relevant.

**Comment by DavidCWGA** [comment]
A quick search of EasyList commit doesn't reveal any more DMCA takedowns since the original set, so unless they haven't included the word DMCA in the commit name, it probably hasn't been updated because there haven't been any more takedowns.

https://github.com/easylist/easylist/search?q=DMCA&type=Commits&utf8=✓

**Comment by StevenBlack** [comment]
Thanks for the input, @DavidCWGA.

**Comment by StevenBlack** [comment]
This list is not curated.  Closing.
