### ISSUE TITLE
pfSense list?

### ISSUE THREAD

**Issue by ArneAnka** [StevenBlack/hosts#478]
Hi!

I have been using StevenBlack/hosts on my machine, but recently starting using pfSense as my router with the pfBlockerNG package. Wouldn't it be nice to have the StevenBlack/hosts as a list, like for example: http://adaway.org/hosts.txt?

**Comment by ScriptTiger** [comment]
You mean getting in touch with the pfBlockerNG team and having StevenBlack/hosts built into their package as an option for its initial configuration? I am sure you can manually input it, yes? Does that package also include a way for its block lists to be routinely updated, or is that a manual process? Also, what operating system are you using? I only ask because I script for Windows and have means of scripting automatic updates of StevenBlack/hosts and alts for network devices over telnet/SSH.

**Comment by StevenBlack** [comment]
@ArneAnka can you please provide a link to a typical pfBlockerNG list, or a description of its format, or a spec?  Thanks.

**Comment by funilrys** [comment]
@ArneAnka I don't get it a pfBlockerNG list is only a list of IP?

**Comment by Atavic** [comment]
Raw hosts: https://github.com/alexbogus/pfblockerng-blacklist

**Comment by Atavic** [comment]
Raw adresses: https://github.com/alexbogus/pfblockerng-blacklist

Techically those are blackhole DNS lists.

**Comment by Atavic** [comment]
DNSBL: https://github.com/alexbogus/pfblockerng-blacklist

It's Blackhole DNS (raw addresses list).

**Comment by ScriptTiger** [comment]
It's the same format as DNSCrypt: https://github.com/StevenBlack/hosts/issues/434

bigdargon commented on Nov 6, 2017:
>@StevenBlack it work! Many thanks!

I'm not sure, but possibly he was referencing https://github.com/StevenBlack/hosts/issues/237 as having a solution to that.

**Comment by DavidCWGA** [comment]
The regular list works just great in pfBlockerNG, which is the default way of handling dns blocklists in pfSense. There's no need for a special format.

**Comment by MaxXor** [comment]
Just use this list URL `https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts` in pfBlockerNG, it's working fine already.

**Comment by funilrys** [comment]
Good to know thanks for the input @DavidCWGA :+1:
