### ISSUE TITLE
Working with ios11 ?

### ISSUE THREAD

**Issue by tazulrey** [StevenBlack/hosts#489]
Hi
I heard that entries is limited for hosts file in iOS.. around 4000..
I don't know if it's true or not, so  does someone use the Unified hosts with 42K entries for blocking ads in iOS ?
will it work ? and not slow down or even crash internet access ?

thanks a lot for this good job
regards

**Comment by ScriptTiger** [comment]
If this is a problem, I'm curious if the new "compression" option might help here, as well.

**Comment by tazulrey** [comment]
On my side it's not working with iOS 11. Internet browsing is completely blocked with safari iOS.
Files is too big I think.
Don't know what 'compression' is.

**Comment by ScriptTiger** [comment]
There is an option to "compress" the file to less lines by removing all the empty lines and comments (lines starting with "#") and putting 9 entries on the same line like this:

127.0.0.1 example1.com example2.com example3.com example4.com example5.com example6.com example7.com example8.com example9.com

Instead of having 9 different lines for each. Maybe someone can attach one here for you to try. I know it has solved some people's issues on various operating systems, but I am not sure about iOS. The hosts format used to be a universal standard before DNS came out, similar to a POSIX standard, so I would hope most systems would read it the same way.

**Comment by StevenBlack** [comment]
Closing.
