### ISSUE TITLE
Problematic domains

### ISSUE THREAD

**Issue by Matthaiks** [StevenBlack/hosts#496]
Hi!
**0.0.0.0 connect.facebook.net** disables comment sections at blabbermouth.net (and maybe elsewhere).
**0.0.0.0 d2gatte9o95jao.cloudfront.net** breaks urbandictionary.com.

**Comment by funilrys** [comment]
Hello @Matthaiks and welcome here!

Because of the listing below, I'll suggest you to whitelist those domains if you really need them.

Indeed, because they are both into `./hosts` that means that they are into the unified file (`./data/`)  which is almost exclusively updated if upstream update their lists because of new entry, false positive deletion or deletion of inactive domains (for reintroduction later ?). 

In this case, as they are not false positives and are both listed in more than one list, that only gives us the whitelist as the only option.

I'm not @StevenBlack but that's my point of view regarding those domains. 

____________________
# Occurence search 

## `connect.facebook.net`
Can be found in the following lists:

```
./extensions/social/hosts
./data/StevenBlack/hosts
./alternates/fakenews-porn/hosts
./alternates/fakenews-gambling/hosts
./alternates/social/hosts
./alternates/gambling/hosts
./alternates/fakenews-social/hosts
./alternates/porn-social/hosts
./alternates/gambling-porn/hosts
./alternates/fakenews-gambling-porn-social/hosts
./alternates/fakenews-gambling-porn/hosts
./alternates/porn/hosts
./alternates/fakenews/hosts
./alternates/gambling-porn-social/hosts
./alternates/fakenews-porn-social/hosts
./alternates/gambling-social/hosts
./alternates/fakenews-gambling-social/hosts
./hosts
```

## `d2gatte9o95jao.cloudfront.net`

Can be found in the following lists:
```
./data/mvps.org/hosts
./alternates/fakenews-porn/hosts
./alternates/fakenews-gambling/hosts
./alternates/social/hosts
./alternates/gambling/hosts
./alternates/fakenews-social/hosts
./alternates/porn-social/hosts
./alternates/gambling-porn/hosts
./alternates/fakenews-gambling-porn-social/hosts
./alternates/fakenews-gambling-porn/hosts
./alternates/porn/hosts
./alternates/fakenews/hosts
./alternates/gambling-porn-social/hosts
./alternates/fakenews-porn-social/hosts
./alternates/gambling-social/hosts
./alternates/fakenews-gambling-social/hosts
./hosts
```

**Comment by StevenBlack** [comment]
There must be something about `d2gatte9o95jao.cloudfront.net`... the fine folks at mvps.org, they take their listkeeping very seriously.

**Comment by ScriptTiger** [comment]
"connect.facebook.net" and "facebook.net" also handle embedded/hidden event triggers similar to events in Google Analytics and can be used to track your behavior without your knowledge and are not just used for comments, sharing, liking, or other obvious social media functions, as we have seen in a couple issues in the past.

**Comment by StevenBlack** [comment]
Closing, as per Issue #656.
