### ISSUE TITLE
CoinBlocker Blocking Valid Domains

### ISSUE THREAD

**Issue by SilkySmooth** [StevenBlack/hosts#509]
This list is blocking dozens of domains that have nothing to do with browser mining. Things like coinbase, binance, bitfinex, etc.

**Comment by dnmTX** [comment]
Not sure where @StevenBlack  i getting the list from,but if it's from the @ZeroDot1's repo he should use [https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts_browser](url) which protects against browser mining and the domains mentioned by OP are not there.

**Comment by StevenBlack** [comment]
@SilkySmooth @dnmTX my mistake!  You're right I took the wrong data set.

Fixing now.

**Comment by dnmTX** [comment]
@StevenBlack  is it possible to make it like additional extension like fakenews,porn....this way there will be more choice? Just a suggestion  .

**Comment by StevenBlack** [comment]
It's certainly possible.  In my view the in-browser miners are bad-apples that belong in the main group, along with malware.

I can be convinced otherwise.  But for now, it's default.

**Comment by StevenBlack** [comment]
Fixed!  Thanks for the heads-up everybody.

**Comment by dnmTX** [comment]
@StevenBlack  i think you can remove  the "# JS based cryptocurrency mining sites" from your list now the you included the ZeroDot1's one.I see too many duplicates.

**Comment by ScriptTiger** [comment]
I definitely agree with Steven on this one. Most, if not all, anti-virus programs immediately detect mining scripts and require action to be taken. Rather than trying to fight an already lost battle here, people that want access to blacklisted sites should just whitelist them. The majority of the users here don't have time to look into everything and trust active members are contributing and doing the right thing. If we can't prevent a simple anti-virus popup from wasting several minutes of your day asking you if you should quarantine this or that or add exceptions or decide whether you should do a full scan because you're not sure what's happening, etc., etc., I feel as though many people would be let down by this project at large.
