### ISSUE TITLE
Download TIMEOUT is too low

### ISSUE THREAD

**Issue by FadeMind** [StevenBlack/hosts#513]
# Issue

When script trying download LARGE files, then cannot do this.
When script trying download small hosts files, then all went fine.

It is not matter what version of Python using. 
For example I cannot downloading host from https://someonewhocares.org/hosts/ or HP Hosts LARGE main file, BUT I can simply download smaller files from HpHosts like Ads servers. 

@StevenBlack

**Comment by ScriptTiger** [comment]
Think we should change the HTTP(S) fetcher, wget, cURL, etc.? Does the current fetcher have timeout options?

**Comment by funilrys** [comment]
Wow, where was I when this was posted? :joy_cat: 

@StevenBlack `urlopen()` provide a `timeout` option ... Do we have/need to implement that ? :thinking:

**Comment by funilrys** [comment]
@FadeMind is this issue still actual with #520 ?

**Comment by ScriptTiger** [comment]
With larger files comes an increased probability of running into pre-#520/pre-1.0 issues. It's possible it could be #520, especially since someonewhocares.org was specifically called out again. @FadeMind, can you download the porn extension without issue? It's 6 times the size of someonewhocares.org, so that will definitely tell us something. Porn URLs have to be user-friendly and easy to type on a typical U.S. keyboard, while phishing or malware are more often clicked in search results or links in e-mail etc., unless it's typo phishing hoping you miss a character here or there and put in their URL by mistake. A possible weakness to this test would be if the someonewhocares.org server itself has timeout issues, but we just did a major update and I am sure it was tested over a billion times by @funilrys just in the last week alone.

**Comment by FadeMind** [comment]
@ScriptTiger see
https://github.com/StevenBlack/hosts/pull/526/files?diff=split

**Comment by FadeMind** [comment]
@StevenBlack @funilrys @ScriptTiger **resolved** in PR #527
