### ISSUE TITLE
Torrent sites blocked

### ISSUE THREAD

**Issue by ameyagokhale** [StevenBlack/hosts#569]
Torrent websites are being blocked under the porn category. some examples are RARBG and some of the Piratesbay proxies.

**Comment by StevenBlack** [comment]
Hi Ameya @ameyagokhale I'm going to need specific details.

I can tell you the Tor browser, for example, bypasses the hosts file entirely.  So tell me about your Tor client software as well.

**Comment by ameyagokhale** [comment]
This is nothing particular to any browser. Under the alternates/porn category, torrent websites have been added which should be the case according to the category.

So, inside alternates/porn/hosts
`0.0.0.0 www.rarbg.com`
is added which is wrong as that is a torrent site.

**Comment by dnmTX** [comment]
Yep... rarbg.com is a torrent site(just checked it) which also provides XXX movies for download but that doesn't make it a porn site.Good catch @ameyagokhale .

**Comment by ScriptTiger** [comment]
I think this one might be tricky though. For people that are trying to block access to inappropriate content from underage household members, basically the porn category sounds like it does exactly that, to include torrents. If you open it, then underage people would then have access to such material that is meant to be blocked. If you are trying to get around the blocks on an individual basis, as Steven was hinting at, using the Tor browser is a quick and easy way to do so.

To be completely honest, if you are connecting  to a torrent file/magnet link anyway, it's best to use Tor. Or even better would be I2P to both download the torrent/magnet data as well as download the actual file you are wanting to get, which provides end-to-end torrent protection. If you are just using regular protocols, like regular DNS to send queries to a local DNS server to find the torrent sites, and then regular direct HTTP(S) connections to connect to the torrent websites, you can easily be tracked at any step in the process. And then, of course, downloading the actual file you want, if there is a copyright troll lingering in the pool you connect to, you can be caught there, as well. I2P is end-to-end for torrents and resolves all of the above issues, although nothing is perfect, of course, nor can anything be completely guaranteed.

**Comment by dnmTX** [comment]
Good point @ScriptTiger ,looks like most of the extensions are meant to be more like "parenting control" then anything else(call me stupid but i never thought of them as such till now though).So....yeah.... @ameyagokhale  you might have to whitelist this one in order to access it.

**Comment by ameyagokhale** [comment]
@ScriptTiger but most of the torrent websites have things like these but blocking all of them will create problems. One Solution to it is making another category like "torrent" which contains all the domains. Then people can use the complete list to whitelist or blacklist those websites as per their requirements.

**Comment by ScriptTiger** [comment]
I think most people, once they find their torrent portal of choice, they just stick with it. So even if we blocked them all, most people would only have to whitelist one, maybe two if you have a backup favorite. Does anyone here use multiple torrent portals?

**Comment by rautamiekka** [comment]
I think the reason torrents are blocked alongside porn is cuz you can get porn as easily as you can Linux distros, assuming you know the keywords or can browse the site.

**Comment by ameyagokhale** [comment]
@opticyclic that's what I am trying to say :)

@rautamiekka yes, people can find that just by browsing on those sites. But, even google will show images and will provide links to different sites but that doesn't mean we can add google or any other search engine in that list.

**Comment by ScriptTiger** [comment]
However, we can block domains that show up in Google search results, Bing search results, DDG search results, etc., all simultaneously. Let's all just be honest here, if you are blocking porn it's most likely for kids. If a grown man wants to look at a naked lady, there is nothing in this world to stop him from doing so. Is there honestly anyone here blocking porn from themself? I guess it's possible if you have some kind of unhealthy addiction or other related problem, but social accountability apps that e-mail all your Internet history to friends, family, colleagues, etc., are probably more effective. And I am not trying to be flippant either, this is just how I personally see it. I give full props to Terry Crews for spreading the word about his personal struggles and doing what he does.

**Comment by ScriptTiger** [comment]
Regardless of anyone's stance, I think compiling a list of all torrent domains would be useful at our current juncture. Right now torrent portals aren't specifically targeted with porn, there is just the one-off site that landed on the list. Having a curated list of torrent domains would be useful whether you want to whitelist them on a porn block list or if you want to block them in their own extension.

**Comment by dnmTX** [comment]
@ScriptTiger  i for once have to disagree with you on the whole argument here.I know where you coming from,parenting control and all but when it comes to torrent sites they are such a "grey area".You go to any of those sites and search for...lets's say "russian porn",i can bet you that 90% of them will have something to offer to your satisfaction.So...because one site for some reason advertising it doesn't mean that the rest are "clean".In conclusion you guys either block all of them(for the good of the children,not that they won't find another way to watch porn if they want to) or just let them stay in their "gray area" and pretend that they don't exist(little sarcasm here).Just my 2 cents man,no bad feelings.

**Comment by ScriptTiger** [comment]
@dnmTX, I can agree with that. I think if someone was to curate/find a suitable torrent list that can be used for either blacklisting or whitelisting, I think this thread in total proves there is at least some interest there.

**Comment by ScriptTiger** [comment]
I found this project curated by a bot, but it seems pretty extensive:
https://github.com/ngosang/trackerslist

It doesn't include the portal sites, but if we implement this as a blacklist/whitelist we can just agree that we won't include the portals on any lists since they are basically like search engines, as @ameyagokhale was saying. Whitelisting/blacklisting the trackers are similar to whitelisting/blacklisting the websites that show up in Google search results, except in this case we would be essentially whitelisting/blacklisting all of the possible search results to effectively enable/disable torrents no matter what portal you're using.

**Comment by Jezza-x3** [comment]
The hosts file should not be used as a parental control option. It would need all proxy sites, weapon sites, all other bad things prohibited. Then we would have too large of a hosts file. 

If they want to block torrent sites they should manually add them or use a DNS filter. Most people that can change the DNS would probably be capable of bypassing a hosts file.

**Comment by ScriptTiger** [comment]
First off I would just like to state that, as with my previous comments, creating said list is not only for "parental control," but also can be used as a white list for those that use torrents and want to make sure they are always available. Torrent sites will continue to pop up in our lists because of the nature of how they make revenue, namely from locally hosted ads that cannot be blocked with external domains, many of which extremely explicit and pornographic in nature, and cryptomining, with a dash of cryptocurrency donations. And some have been known to also host more malicious software, as well. Obviously legally partnering/affiliating with most reputable business organizations is difficult, at least publicly, so they are limited in that way.

That being said, I agree that using a hosts file alone is not the best parental control, but, like security, everything is best complemented. We already know from experience with manual curation that the list would not become "too large," maybe a couple hundred extra if everyone seriously worked together on it. I can guarantee it definitely wouldn't be larger than the porn list we already curate, which is obviously the top searched subject on the Internet since its inception. And even if someone felt it was too large, it's an add-on anyway and they would not even have to use it, as has been stated with other similar debates.

Although one may be capable of changing DNS, the hosts file will remain the same independent of what DNS they are using, as well as the NTFS permissions protecting it from being changed and those protecting from third-party software being installed that might bypass it. And obviously we know some such third-party software doesn't require installation, namely Tor, but the Windows Firewall can clean up the rest of those unknown connections. And we are talking about kids anyway, so only parents teaching their children such abilities out of the cradle should have to worry about that. Once they're of age to know how to do all that, I think they have the right to access whatever they want because they HOPEFULLY already understand the pros and the cons and how to live a well-balanced life with technology, but ultimately that comes down to parenting.

Many prefer to use hosts files instead of third-party software because it's a fundamental feature that is core to most modern networked devices and, as long as you trust this repo, you know we aren't collecting any data from you or running any adware or other malware software in the background, as is the problem running rampant in modern times with most third-party software claiming to "protect" you and/or your children. I am fairly certain this is the same reason why many people use this repo.

Lastly, all that being said, I think for the time being it is clear none of this has community support anyway, this being the larger point. Although perhaps in the distant future some of these points might be revisited. I think we can consider this issue closed with the outcome being that if torrent sites pop up on the lists because of malware or explicitly pornographic advertising containing pornographic imagery, that's just the way it is and they can be whitelisted on a per-user basis. And I will reiterate that pornographic advertising will only be a problem for those using the optional porn add-on.

**Comment by StevenBlack** [comment]
Amen.

Closing.

**Comment by Jezza-x3** [comment]
When I said getting too big. I'm thinking of stuff like hphosts that got up to line 15mb? 

Not trying to insult you. I just don't think this is designed for anyone to help control there kids. 

I mean change the DNS to one that lets you have parental controls. Like the opendns blocking of a lot of categories. Not using a hosts file for the entirety. 

But yeah. Not trying to dis you or anything?

**Comment by StevenBlack** [comment]
People use hosts files for all sorts or reasons.  Of course people use hosts files to control what enters their homes.  On what fucking planet is this not the case?

Can we please stop talking about this here?

Porn extension of this hosts file blocks torrents.  End of discussion.

**Comment by ScriptTiger** [comment]
@Jezza-x3, no worries, I never thought you were :) A large portion of my audience using the blacklists I convert from this repo live in Third-World countries that censor non-ISP DNS requests and would either have to host their own local DNS or use a hosts file. I don't expect everyone to understand or even think about that perspective, but a lot of what I do is just try to support the lesser heard from people that have the same struggles but less to work with.
