### ISSUE TITLE
[dnsmasq] bad address when reading the lists

### ISSUE THREAD

**Issue by dnmTX** [StevenBlack/hosts#574]
@StevenBlack  i was looking at dnsmasq's logs and it was showing bad address on line 8 which is this: "fe80::1%lo0 localhost" line. I thought you should know.Thanks.

dnsmasq[567]: bad address at /media/AiDisk_a1/Hosts/add.hosts line 8
dnsmasq[567]: read /media/AiDisk_a1/Hosts/add.hosts - 57123 addresses

**Comment by ScriptTiger** [comment]
How are you generating your dnsmasq file? None of the following lines should be on a server-side blacklist implementation (DNS server, dnsmasq, proxy server, network firewall, pfSense, etc.):

```
127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
255.255.255.255 broadcasthost
::1 localhost
::1 ip6-localhost
::1 ip6-loopback
fe80::1%lo0 localhost
ff00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
0.0.0.0 0.0.0.0
```

Those lines are specifically for end-user devices and cannot be distributed over a server protocol. If you use the lists on my website, it filters those and other problem lines out for servers.
https://scripttiger.github.io/alts/

**Comment by dnmTX** [comment]
@ScriptTiger i'm not generating it because if i do it has to be .config file and has to go in the same directory where dnsmasq is installed but due to limited space(remember i mention it in the other thread?) i'm just fetching the @StevenBlack 's lists to a USB drive connected to the router with .hosts extension and then pointing dnsmasq to read the file with "addn-hosts=" command and it's working.The thing is i'm very limited on options,unless you have better idea.....?

**Comment by ScriptTiger** [comment]
If your limit is 8 mb, it should still be enough for even the largest blacklist, which is 2.5 mb with all extensions in dnsmasq format. But then again I also don't know how much room your custom OS is using. However, If your current setup is fully compatible with the hosts file format, you can use the compressed formats and just omit the lines I mentioned above and that should free up more space to help it run faster. Manually deleting them should be easy enough because they're always together at the top, but you could also script it relatively easily using the whitelist functionality to ignore those lines. If you do it that way, it takes the largest blacklist with all extensions in hosts file format down to 1.4 mb.

Can you install dnsmasq on a host machine rather than on the router which has more limitations?

In any case, this is a software-specific issue and not a problem with Steven Black's files. We just need to figure out how to get it to work in your particular case.

**Comment by ScriptTiger** [comment]
@dnmTX, I literally JUST made this for you, so it's a bit rough. It just does individual files, but it will be easy enough to allow you to compress directories in the future.

https://github.com/ScriptTiger/Hosts-Compressor

I got a bit tired of putting off your ideas and this one was a short one anyway. You really do have a lot of great ideas for simple utilities I think others would find useful, my offline repos are mounting.

**Comment by dnmTX** [comment]
Thank you @ScriptTiger  for making the script and taking the time to do it.Let me see how it's going to work and i'll move to your repo for  further assistance,i think @StevenBlack had enough of me cluttering here 😋.Soryyyyy !

**Comment by StevenBlack** [comment]
@dnmTX #notaproblem  😄
