### ISSUE TITLE
Duplicate entries found.

### ISSUE THREAD

**Issue by Kolyunya** [StevenBlack/hosts#58]
There are duplicate entries in current hosts file: lines `200458` and `200459`.
May seem not so critical, but may break particular systems.

Also line `200459` violates file format consistency.

**Comment by StevenBlack** [comment]
Thanks for this @Kolyunya.

**Comment by rahlzel** [comment]
Also lines 20269 and 27961 (adf.ly)

**Comment by FadeMind** [comment]
[tomasz@arch ~]$ cat /etc/hosts|grep adf.ly
0.0.0.0 adf.ly
#0.0.0.0 adf.ly

adfy.ly is just commented out in some source and in another is uncommented.

**Comment by FadeMind** [comment]
@StevenBlack 

someonewhocares.org
have:
[tomasz@arch someonewhocares.org]$ cat hosts|grep adf.ly
#0.0.0.0 adf.ly

yoyo.org
have:
[tomasz@arch yoyo.org]$ cat hosts|grep adf.ly
0.0.0.0 adf.ly

**Comment by StevenBlack** [comment]
I propose that we not parse comments :-)

[adf.ly](http://adf.ly) is definitely an link monetization network so I'm OK with blocking that.

**Comment by rahlzel** [comment]
It's not ok. There's a lot of useful downloads that people need by dealing with Adfly, such as Minecraft mods, Terraria mods, etc. A lot of mod makers use Adfly as a means of making a small amount of money. It really shouldn't be blocked.

**Comment by lavventura** [comment]
Add it to your whitelist then.

**Comment by hd074** [comment]
Maybe there should be an extra section in the readme about this because you read about it here more often.

``` "Site XY is blocked by your list, but people may need it because of reason XYZ" ```

This is a point people should not discuss in the issues section of the repo, because this project is about merging lists - not about creating lists or defining rules. This kind of question/proposal should be addressed to the actual creators of the original lists (e.g. yoyo). So a reference to the whitelist and its meaning may be useful in the readme.

**Comment by StevenBlack** [comment]
@hd074 good idea!

**Comment by StevenBlack** [comment]
Closing.
