### ISSUE TITLE
Cannot Resolve DNS for 5-10 Minutes After Wake

### ISSUE THREAD

**Issue by z0oinks** [StevenBlack/hosts#593]
[Issue can be seen in detail here](https://itgeeknotes.blogspot.com/2018/01/windows-10-dns-client-load-in-case-of.html) 

This happens when waking from sleep, hibernation, or just turning the computer on.

Is there any resolution?

**Comment by dnmTX** [comment]
Hmm...never had this happened on my pc but i'm still using Anniversary Update here which is stable,anyway,you can try the following:
1. Download HostMan 4.8.106 with it you can remove all comments,empty lines and compress it if you want to up to 9 domains per line which will make the whole file smaller and hopefully will fix the issue.
2. @ScriptTiger's repo offering small script to update,remove lines,compress if you want to so you can try it too.
3. Last but not least you can disable the DNS service see if there is any difference but judging by the link you posted the hosts file is not that big and i think there something else that causing the issue,maybe clean windows install could help.If you can't disable the service there is a workaround:
Flush the existing DNS cache (see above)
Start > Run (type) regedit
Win8 users - from the Charms Bar, select: Search (type) run and select Run (left pane) and (type) "regedit" (no quotes)
Navigate to the following location:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters
Click Edit > New > DWORD Value (type) MaxCacheTtl
Click Edit > New > DWORD Value (type) MaxNegativeCacheTtl
Next right-click on the MaxCacheTtl entry (right pane) and select: Modify and change the value to 1
The MaxNegativeCacheTtl entry should already have a value of 0 (leave it that way - see screenshot)
Close Regedit and reboot ...
This is taken from Microsoft site: [https://support.microsoft.com/en-us/help/318803/how-to-disable-client-side-dns-caching-in-windows-xp-and-windows-serve](url)

**Comment by z0oinks** [comment]
I downloaded HostsMan and tried the MVPS Hosts file, which doesn't take nearly as long to load (maybe 5-10 seconds). I tried this file again, and it brought me back to the 5-10 minute mark again, so the issue definitely lies within it

**Comment by ScriptTiger** [comment]
MVPS is tiny, 464 KB, compared to the hosts files here, the smallest being 1.55 MB. @dnmTX suggested my script, but you could also just download a pre-generated one here:
https://scripttiger.github.io/alts/

Try testing out the compressed and mcompressed formats.

P.S.: @dnmTX, how is that script working out for you? Any notable issues with it?

**Comment by dnmTX** [comment]
@ScriptTiger  shoot...i forgot about your ready compressed lists that you offering,sorry,ill make sure to mention them next time.
On your other question,script is working just fine(thank you),and it's a big benefit if you are with Windows and using it's DNS service but....as you know i switched to DNSMASQ and there it doesn't make slightest difference being compressed or not,that thing is so fast that **"LARGE"** lists like @StevenBlack 's one(being sarcastic here) are appetizers for dnsmasq,not even the main dish.So i ended up having the router do all the work-cleaning,merging and so on due to the fact that Linux in general have much better tools to do the job.I finalized my little script(see https://github.com/ZeroDot1/CoinBlockerLists/issues/136 somewhere in the middle) and now i just have to SSH to the router and activate it and that's it.Works like charm.But don't get me wrong,your hard work is always appreciated here,your script will help many others Windows users for sure.

**Comment by z0oinks** [comment]
@dnmTX @ScriptTiger I tried the compressed  version with HostsMan and it's working great :) Thanks for all the help!
