### ISSUE TITLE
IPV6

### ISSUE THREAD

**Issue by csib** [StevenBlack/hosts#595]
Hi,

In my tests if I enable ipv6 some DNS is still resolving (mostly Google). 

With enabled ipv6 I see almost all Google AdWords 
Disabled ipv6 - Its blocked.

Any idea how to block them totally with ipv6 enabled?

**Comment by ScriptTiger** [comment]
I honestly can't say if this would work or not because I don't have that issue, but maybe you could try replacing 0.0.0.0 with ::1. It should be quick enough to test, you can just "replace all" in whatever text editor you're using. Let us know what happens.

**Comment by dnmTX** [comment]
@csib  see #47  for further help and solution.

**Comment by ScriptTiger** [comment]
@dnmTX, just so I am clear on the format, the issue you referenced and this issue are both in normal hosts file format but just with added IPv6 lines for devices that don't override properly like the below?:
```
0.0.0.0 example.com
:: example.com
```

**Comment by dnmTX** [comment]
@ScriptTiger i just saw that you added more to your previous question,the  IPv4_IPv6  looks good and will do the job.I see that you duplicated each entry which is fine but makes the file twice the size for one,second it's probably a good idea to post some note that whoever use it might experience slower dns resolving,i think that was the other reason to remove my duplicate,and also note that it's only for anyone who has IPv6 enabled on it's network,otherwise my research showed that it's not really needed.

**Comment by ScriptTiger** [comment]
Hmm... I think I misunderstood your original meaning when you said "duplicate." You mean the IPv4 "0.0.0.0" entries don't need to be present at all and effected devices will work with only the IPv6 and the IPv4 won't "leak" like the IPv6 requests did when there were no IPv6 entries?

**Comment by dnmTX** [comment]
Doesn't matter is it one file or two separate,in my case i created exactly the same file like the original but instead of 0.0.0.0 was :: and dnsmasq was fetching from two files instead of one,i'm not a script guru,i was looking at the easiest possible option and it was just for testing.What matters is that now whichever the dns resolver is(dnsmasq in my case) has to cache twice the information,and if you don't have IPv6 enabled halve of that info is useless and this is probably what caused browsing to slow down a bit. Basically if you don't have IPv6 **IP** all those IPv6 domains are just info that passing trough.

**Comment by spirillen** [comment]
the easiest way i can thing of is running the updateHostsFile.py with the -p=0.0.0.0|127.0.0.1 with -o /tmp/ 
mv /tmp/hosts /tmp/hosts0.0.0.0
updateHostsFile.py -p=::1 -o /tmp/
cat /tmp/hosts0.0.0.0 >> /tmp/hosts
cat /tmp/hosts sort | uniq > /tmp/hosts1
mv /tmp/hosts1 /etc/hosts

fur unix|linux users, use sed
sed -e 's/127.0.0.1/::1/' input_file >> output_file
