### ISSUE TITLE
This hosts file blocks all internet access in h&m public WiFi

### ISSUE THREAD

**Issue by highroller** [StevenBlack/hosts#604]
H&M is a clothing store that has free public WiFi. This hosts file blocks all internet access of this free public WiFi.

**Comment by StevenBlack** [comment]
Hi @highroller, we'll need to know more about which domains, specifically, is critical to H&M WiFi.

Please note, this is likely not "Free" public wifi.  It's likely that H&M has sold-out client privacy to veiled services in order to be able to claim to have free WiFi.  If that's the case, then these hosts files are working as designed.

**Comment by highroller** [comment]
How does the hosts file block h&m WiFi?  It happened even after i temporary disabled the hosts file to pass the welcome page. It continues to block WiFi after i reenabled it again. Even if h&m has some kind of server sitting in the middle, the hosts file should not know about it.

**Comment by StevenBlack** [comment]
I'm going to close this now.  Thanks @highroller.
