### ISSUE TITLE
reddit blocked by social category

### ISSUE THREAD

**Issue by Phosphenius** [StevenBlack/hosts#611]
Hi, just found out this morning that reddit is being blocked by all lists containing the social category. Since reddit is a news aggregator and not a social media network like facebook for example, I would not expect it to be blocked by this category (or blocked at all). Of course one could argue that it can be used as a social media platform but then you'd have to put it into the porn category as well since it hosts explicit content too.

**Comment by funilrys** [comment]
Is this related to  #583 discussions ? :thinking:

**Comment by StevenBlack** [comment]
Hi Luca @Phosphenius, thank you for your input.

I agree with this change.  

You are correct, @Phosphenius : Reddit is an open news aggregator.  Behind every item, however, the comments link leads to an underlying social network where signed-in users can post and repartee.

But beyond this, I see the social media extension as an aid for people who want to focus, or enforce focus.  I think we can all agree: Reddit is a time sink with a social network bolted-on.

Therefore it belongs in the social extension.

But I'm willing to be convinced otherwise 😄

**Comment by rndusr** [comment]
I'm also dumbfounded by this change. I thought the social block list is about tracking, e.g. Facebook having their Like buttons everywhere.

In my opinion, blocking time wasting websites should be an individual responsibility. You can waste many hours on Wikipedia, TV Tropes and many other websites, but you don't block these.

If people really want a block list for time wasters, that should be done in a separate list since "wasting time without being tracked" is a reasonable need.

**Comment by StevenBlack** [comment]
Hi @rndusr, no, the social extenion isn't about "being tracked".  That's the role of the default hosts file, the one without any extensions.

The social media extension is all about blocking social media, hence its name.  Just like the porn extension is about blocking porn, and the gambling extension is all about blocking gambling.

I hope this clarifies the role of extensions here.

**Comment by rndusr** [comment]
I see. My bad. Thanks for clearing this up for me.

**Comment by dnmTX** [comment]
@StevenBlack  i think it's a good idea if there is a explanation on the main page what the extensions are meant for which will reduce the confusion and complaints drastically.Given the fact that your lists in general is design to prevent tracking and ads one would think that (for example "porn") will prevent ads and tracking on such a websites not blocking the entire site,i was one of the confused ones  so speak from experience and looks like i'm not the only one.

**Comment by StevenBlack** [comment]
@dnmTX thanks for that suggestion.  I've addressed this in commit 10e61eaed9f6ae394b662e029444c319c8b5ad76 which hopefully clarifies the goal and workings of extensions.

**Comment by StevenBlack** [comment]
Closing.
