### ISSUE TITLE
Include proxy/anonymizer services

### ISSUE THREAD

**Issue by kleo** [StevenBlack/hosts#615]
Blocking sites that are already included in the unified hosts. You can still access blocked sites using proxy/anonymizer services such as kproxy.com, hide.me, megaproxy, and etc. 

This will render the hosts file ineffective, to allow these kinds of services.

**Comment by kronflux** [comment]
Pretty vague request.. I imagine you're speaking along the lines of web proxy services such as hidemyass.com(actually already blocked, but using as an example) and hide.me?

To which I would recommend this be an optional list request, if a suitable curated list can be found.

**Comment by kbeflo** [comment]
@kronflux forgive me for not including additional details in the initial issue comment.

**Comment by kronflux** [comment]
Excellent, thanks for the clarification.
So yes, my post was correct. To add this, there needs to be a curated list of web proxy sites, which could be added as an optional addon list

**Comment by ScriptTiger** [comment]
I feel as though this and the torrent list ideas are both good, but we may need to rethink how our current extensions are organized before we start adding more so the amount of extensions and combination possibilities doesn't become difficult to work with. For instance, is there anyone that feels as though someone wanting to block porn and/or gambling would only want to block one or the other and not both? I can see how fake news might be a bit opinionated and not everyone will want to use it, but maybe we should just build a safe-for-work (SFW)/family-friendly type extension that comes standard with porn, gambling, and proxies/anonymizers, and then leave the torrent list on its own because that can also be a bit opinionated. Thoughts?

**Comment by spirillen** [comment]
@ScriptTiger I think you are on to something, but as i referrer to in a other issue it could maybe be a good idea to actually incorporate http://dsi.ut-capitole.fr/blacklists/index_en.php and separate into categories link the linked page.

But here is the real issue.. the egg or the hen. You can't do real blocking based on hosts files alone, you can only do basic blocking if you would like to keep the majority of sites working for all devices (phones, TV, radios etc.) Then you would have to add a DNS server (replacing the hosts file) AND a proxy server as Squid.
Only by combining these things you are on the right way, but still not completely done.

So My vote is to separate as much as possible into categories and then let the individual user choose for them self, each category could then have a number of sub categories that's by default are added if a user choose a higher level of category, in this way it would still be possible to auto generate a number of hosts files that can be linked to without having to many.
