### ISSUE TITLE
[for consideration] new hosts lists...please review

### ISSUE THREAD

**Issue by dnmTX** [StevenBlack/hosts#631]
Found it recently,from what i can gather it's been around,it's maintained,not sure how well though.The lists is big,around 238000 lines,there are duplicates also but i guess it's worth checking it out.I'll leave the rest to the experts,here is the link:
https://adzhosts.fr/index-en.php

CC @StevenBlack  @ScriptTiger  @funilrys  @anudeepND  @FadeMind

**Comment by StevenBlack** [comment]
As we've experienced in the past, hosts files this large come with many issues.  The user experience is  not tolerable on some mobile devices, and some Windows installations.

How the heck does anyone curate a quarter-million line hosts file?  I think I know: they mostly just cumulate, and grow larger.  Someone generates a thousand-line list of garbage, submits it, and the aggregate is  thousand lines longer.  

I'm not going there.

I'm already uneasy because we're over 50k Hosts.
