### ISSUE TITLE
Ekstra Bladet video host blocked

### ISSUE THREAD

**Issue by XelNika** [StevenBlack/hosts#635]
Ekstra Bladet (tabloid newspaper) hosts their videos at `cfvod.kaltura.com` and your list breaks them.
[Example](https://ekstrabladet.dk/kup/elektronik/teknologi/kunderne-flygter-dansk-kabel-tv-bliver-kvalt/7165253).

**Comment by StevenBlack** [comment]
Hi @XelNika unless you can convince me otherwise, this one will stay blocked.

For my ref: added by me in commit a9fb35dcc296

**Comment by XelNika** [comment]
I don't really care, I just noticed it affected a (somewhat) legitimate site. Why did you block it? I don't see any explanation.

**Comment by StevenBlack** [comment]
@XelNika see what a lot of people don't understand is too many "legitimate" sites whore themselves out to cagey third parties.

The hosts files here aren't about blocking legitimate sites.  They are about blocking unscrupulous partners.

I blocked this site 4-months ago because I came upon some dodgy content from this site, and because I can.

Closing.

**Comment by ScriptTiger** [comment]
Lol, anyone else notice Steven has been getting a bit more cheeky over the last couple months?
