### ISSUE TITLE
Trojan.Win32.Hosts2.gen detected

### ISSUE THREAD

**Issue by danewfie** [StevenBlack/hosts#643]
I haven't updated in a long time but decided to do it recently and have been scratching my head trying to figure out what is causing it. But something is now causing Kaspersky to identify the hosts file as malware now. Issue or any way to verify false positives?

**Comment by danewfie** [comment]
Due to the nature of what I do, that's not an option but I'll continue looking to see if something specific is triggering this. Like you said, could be a new specific domain which is flagging it.

**Comment by ScriptTiger** [comment]
Due to the nature of our hosts file, which contains many references to malware domains, many antivirus programs that scan the hosts file for possible hijacking are going to flag it. It's actually a good thing because it means they are agreeing with us. If you don't have the permissions needed on your system, I would definitely open a ticket with whoever does and get them to make an exception in your antivirus, or at least turn off the feature scanning your hosts file, if possible. With that being said, I would highly recommend NOT altering your hosts file to fix this issue, as it will just end up making you more vulnerable and exposed to the domains that are being flagged for hijacking.

**Comment by dnmTX** [comment]
I'm using Avast myself and when the hosts file was on my machine Avast was scanning it and removing any entries that contained "avast" in it.There were many complaints in their forum about that and all of them were ignored,or stated that Avast doesn't mess with the hosts file 👎 .Now that my hosts file is in my router Avast can honestly suck it.So..... @danewfie  asking Kaspersky to not mess with your hosts file is just a lost cause,those f***ers  want their hands on everything so they can sell your info and make some dolares 🤑

**Comment by kronflux** [comment]
Yeah, just a side note really - most Anti-virus/malware programs will almost certainly detect ANY hosts list(especially if it includes a script to replace the system hosts file) as malicious, as many types of malware will often use the hosts file to redirect user traffic for their own malicious purposes.

The reality is, if you have an advanced enough knowledge base to be using this hosts file, you should really be aware of good practices for safe web browsing and system management, and really shouldn't *need* an anti-virus/malware.
Additionally, even if you DO need to use one(for example, corporate environment where it's not optional, or where lower-level users might be using the system you're managing), you should likely be aware of how to add exceptions to your anti-virus/malware software, and therefore this wouldn't be a problem at all.

**Comment by dnmTX** [comment]
@ScriptTiger  i know they own it,never used it though 😋

**Comment by spirillen** [comment]
See this comment https://github.com/StevenBlack/hosts/issues/818#issuecomment-440448446
