### ISSUE TITLE
aboutads.info list of hosts to block

### ISSUE THREAD

**Issue by 6cUbi57z** [StevenBlack/hosts#645]
Hi,

With the introduction of GDPR in Europe, we are seeing a lot of "ad choices" popups. One of them pointed me to the site http://optout.aboutads.info/ where a few of the domains seem to be getting through.

I did a bit of investigation. The site is largely JavaScript and loads the data from a JSON file at ```http://optout.aboutads.info/naibc/resource/members/public?cacheBuster=<randomNumber>``` but I'm not sure which property is the actual tracking address (if included). It might just be that the addresses have to be added manually for now.

Thanks for the great work. The web seems so much better without adverts constantly in your face!

**Comment by StevenBlack** [comment]
Thanks Dale @dale2507 I'll have a look!

**Comment by spirillen** [comment]
Hi, I've have this record `aboutads.info.rpz.mypdns.cloud` in my rpz which completely block the privacy harvesting from `aboutads.info` cookies etc.  it's work beautifully for me as I have no intention of visiting `aboutads.info` as I consider them evil for all there data collecting, the attention to them started with the GDPR on https://dr.dk/ which is the Danish national "commercial" free tax paid TV station. They then turned out to actually sharing your data to somewhat like 50 others as i recall....
