### ISSUE TITLE
Hosts List blocking WeChat messanger

### ISSUE THREAD

**Issue by Bennibaba** [StevenBlack/hosts#655]
edit: Just checked, it wasn't the fault of your list. AdGuard Pro can't handle too many different host lists!

Hello everyone,

first of all thank you very much for the great work!
I use the "fakenews, gambling" host list on my Iphone. But as soon as I add the list (with AdGuard Pro) WeChat (the famous Chinese messaging app) isn't working anymore. It has no connection to the internet anymore.
Can anyone help me identifying which entry must be whitelisted?
Thank you very much!

**Comment by dnmTX** [comment]
@Bennibaba  according to AdGuard they stoped doing system wide filtering due to Apple decide to enforce one of their policy and it's only in the browser.As it's stated here: 
https://adguard.com/en/blog/adguard-ios-1-3-0/
Even if you somehow managed some workaround AdGuard for iOS  has filtering log (https://adguard.com/en/blog/adguard-for-ios-120/) so you can find it yourself and whitelist it.

**Comment by Bennibaba** [comment]
@dnmTX thanks for the explenation. Actually you can still filter system wide, but you have to add own lists.

I will close the issue. Thank you very much!
