### ISSUE TITLE
g.alicdn.com is used by Alibaba's websites

### ISSUE THREAD

**Issue by Crystal-RainSlide** [StevenBlack/hosts#658]
For example, https://www.aliyun.com
Block g.alicdn.com will break the site.

**Comment by Crystal-RainSlide** [comment]
and, in 
# https://securehomes.esat.kuleuven.be/~gacar/persistent/index.html

At least
```
0.0.0.0 simg.sinajs.cn
0.0.0.0 tv.sohu.com
0.0.0.0 y3.ifengimg.com
```
are hosting non-tracking scripts.etc.
I think it is better to drop all its domains and let people block them with adblockers using rules like:
```
||i.ligatus.com/script/fingerprint.min.js
```

**Comment by Crystal-RainSlide** [comment]
Yeah… code block needed.

**Comment by Skaronator** [comment]
I made a similar request in a other notracking list: https://github.com/quidsup/notrack/issues/263

**Comment by dnmTX** [comment]
Isn't disabling CANVAS and WebRTC  in Chrome(for example) have the same affect(blocking tracking domains....at least some)? I just wondering?

**Comment by ScriptTiger** [comment]
I'll trust Steven's judgment as usual and await his one-line quip to explain his feelings, but Alibaba and Tencent are  known to be the two biggest adware developers in Asia. I would recommend replacing them with a more local company that specializes in your country, which usually works out cheaper anyway and many of the local apps give you an opportunity to negotiate in your native language with the vendors, as well as they have better knowledge of your local courier services so you're less likely to have shipping issues. Installing apps or visiting anything associated with Alibaba, Tencent, etc., is a known security risk, so it's better if you just whitelist whatever domains you want so that everyone else installing mobile games, file explorers, or otherwise completely unrelated software that inexplicably contact the Alibaba domains don't have to worry about privacy concerns just so a handful of people can shop on their website.

**Comment by StevenBlack** [comment]
I'm running [Little Snitch latest](https://www.obdev.at/products/littlesnitch/index.html) and  `g.alicdn.com` doesn't actually break https://www.aliyun.com because that site is evidently broken already.  My fingertip hurts from repeatedly clicking to grant access permissions.

I'm suddenly very interested in a solution to this Alibaba rat's nest.

I'm going to remove `g.alicdn.com` until we get a comprehensive rational analysis of Alibaba.
