### ISSUE TITLE
Zacinlo malware

### ISSUE THREAD

**Issue by ScriptTiger** [StevenBlack/hosts#673]
**DO NOT RESEARCH THIS UNLESS YOU KNOW WHAT YOU'RE DOING AND ARE PROPERLY SAFEGUARDED AGAINST MALWARE!!!**

Greetings! I am curious if anyone has been affected by the Zacinlo malware, known to be obtained through installations of the fake VPN software S5Mark, although other sources are also possible? I did just a little bit of digging and none of the domains I found were on our lists. Has anyone sandboxed this, or can someone? It may not be practical to implement anything at all in our lists because from what I've read they just acquire cheap/free domains from Enom, so it may just be an infinite amount of domains that's always changing and not practical to even attempt blacklisting. But some sources I've read do have actual domains listed, so I am not sure if there are some that are always used while others always change or what.

Bitdefender report:
https://www.hackread.com/wp-content/uploads/2018/06/Bitdefender-Whitepaper-Zacinlo.pdf

Brief article:
https://www.hackread.com/zacinlo-malware-spams-windows-10-pcs-takes-screenshots/

**Comment by lightswitch05** [comment]
I added some of those to my list in this commit lightswitch05@f596a7a3636c3dccf652074e669d7a08bb51a06e

* I only added domains that obviously had something to do with tracking or ads since I didn't want to make any calls to the domains to research them
* I meant to have had a separate commit for this, but I had already added a bunch of other domains and it all got jumbled up jumbled `¯\_(ツ)_/¯`

**Comment by StevenBlack** [comment]
Closing.
