### ISSUE TITLE
Analytics/Tracking in Games

### ISSUE THREAD

**Issue by Bennibaba** [StevenBlack/hosts#678]
Hello,

first of all: thank you for your great work!

Is there any plan to extend the host file to block tracking from different games (like games on Steam, Origin, etc)?

I found a list already, unfortunately its in german:
https://www.gameindustry.de/hosts.php

Thanks for the consideration!

**Comment by ScriptTiger** [comment]
That is actually a pretty useful list to reference if you have some of the software mentioned, but I don't think it quite fits here. It's extremely software specific. And just from quickly glancing at some of the entries, it seems like most of those lists were put together with only blocking unnecessary connections made by various software in mind. However, if you were to look at the same list and think about what would happen if they were all blocked to a web browser, as well, it becomes clear that list does not take that into consideration.

**Comment by lightswitch05** [comment]
It is a cool list, but way too aggressive. It blocks updates, I also don't like the IP address blocking since those can easily change.

* Blocking Malwarebytes updates seem like a bad idea. Might as well just uninstall it if you aren't going to let it update.
* Flat out blocking `www.mint.com` and `api.quicken.com` would make a lot of people mad, including myself.
* I have really struggled with blocking adobe updates `armmf.adobe.com` since it pings that domain almost constantly, but again, I'm pro update `¯\_(ツ)_/¯`.
* Last time installed Daemon Tools it was almost like a virus, so I can get behind that block.

A good list, but needs some TLC to make it useful for general consumption
