### ISSUE TITLE
Add more website to the social list

### ISSUE THREAD

**Issue by DBtn3PUSrL7jRRRf** [StevenBlack/hosts#684]
Hello, I think you should add more websites/services to the social list.

Exemple : 
Discord
YouTube
Github (maybe ?)

I also think you should make a list that block all the "crappy" / spying sites like Google, Yahoo, Amazon, Microsoft, Mozilla (and like hundreds more) ...

**Comment by ScriptTiger** [comment]
^ Same guy. We already know what you're thinking, @StevenBlack. If you have already drank your morning coffee and are clear-headed to make a comical remark here before you kill it, please honor us with such a comment. Otherwise, there's no need to rant, we understand and are right there with you in the decision you are about to take on what to do with this issue.

**Comment by StevenBlack** [comment]
Thanks DB @DBtn3PUSrL7jRRRf I'll take that under advisement.  Thanks!
