### ISSUE TITLE
Google Ads - Google Ad Manager - Google Marketing Platform

### ISSUE THREAD

**Issue by xetorixik** [StevenBlack/hosts#691]
Google changed its advertising platform.

[On his blog](https://www.blog.google/technology/ads/new-advertising-brands/), Google explains that AdWords is now called Google Ads and that DoubleClick for Publishers and DoubleClick Ad Exchange come together in Google ad Manager. It also creates the Google marketing Platform, which is a merging of DoubleClick Digital marketing and the Google Analytics 360 Suite.

This change could lead to change in domain names, in terms of advertisements and tracking.
This could be a big and bulky job, given the fact that there are a lot of DoubleClick and Google track and ad domains. 

Perhaps we can work together: @StevenBlack @anudeepND @ScriptTiger to catch new potential track and ad domains.

**Comment by StevenBlack** [comment]
Thanks @xetorixik.  I'm going to close this because what we do is amalgamate third-party curated sources of hosts.  

Our third-party curators do a fantastic job, yeomen's service, and I don't expect they will have any problem staying on top of this.

But feel free to use this closed issue to discuss this.
