### ISSUE TITLE
Whitelist assets.adobedtm.com

### ISSUE THREAD

**Issue by jonozzz** [StevenBlack/hosts#709]
assets.adobedtm.com is needed by lowes.com

**Comment by anudeepND** [comment]
@jonozzz I was able to access `https://m.lowes.com` with `assets.adobedtm.com` blocked, what issues are you having?

**Comment by StevenBlack** [comment]
@jonozzz I just used [Little Snitch](https://www.obdev.at/products/littlesnitch/index.html) on this and I cannot see `assets.adobedtm.com` requested by lowes.com or lowes.ca.

Please clarify?

**Comment by jonozzz** [comment]
This is what I get in Chrome:

![image](https://user-images.githubusercontent.com/250343/42802298-606b7878-8957-11e8-98cf-f5b4695a91a8.png)

Try logging in. I think that's where it was dying.

**Comment by StevenBlack** [comment]
@jonozzz  the domain `assets.adobedtm.com` is flagged by two of our data sources, mvps.org and @lightswitch05.

I trust our curators.  

Daniel @@lightswitch05 will evaluate this.  As for mvps.org, please take this up with them at winhelp2002@gmail.com.  If they both agree to remove their flags, then `assets.adobedtm.com` will be unblocked.

**Comment by anudeepND** [comment]
@jonozzz Please provide some information about the issues you're having. Do you have problems with the elements like pictures etc. on `lowes.com`?

**Comment by jonozzz** [comment]
Yes, with assets.adobedtm.com pointing to 127.0.0.1, open https://m.lowes.com/, click myLowes and login using your lowe's credentials.

**Result**: page will hang indefinitely, the JS console shows the following error:
Uncaught ReferenceError: _satellite is not defined
    at i (account-small.min.js:2)
    at t (account-small.min.js:2)
    at Object.<anonymous> (account-small.min.js:2)
    at d (scaffold.min.js:4)
    at Object.fireWith [as resolveWith] (scaffold.min.js:4)
    at i (scaffold.min.js:6)
    at XMLHttpRequest.e (scaffold.min.js:6)

**Expected**: login successful and user is redirected to the account home page.

**Comment by lightswitch05** [comment]
@jonozzz I verified some weirdness with login on Lowes's website - at least on the desktop site, I did not try mobile. When I clicked 'Sign In' using my correct username and password - nothing seemed to happen. I also verified the `_satellite`error in the console. However, when I refresh the page, I'm logged in. It looks like login is successful - its just the logic that closes the popup and refreshes your login info is broken.

`assets.adobedtm.com` is a hugely popular tracker - I see it all over the internet. I'm really hesitant to remove it over this single issue. Especially since it seems like the login is working successfully after a page refresh. I did send Lowes an email about it, so perhaps they will fix it on their end.

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/598803/42858607-eddf53fe-8a3e-11e8-9edb-1d64566aef7c.png">

**Comment by lightswitch05** [comment]
Lowe's response:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/598803/42910100-c474c778-8ad5-11e8-9176-5ec77fd6de46.png">

**Comment by WillPresley** [comment]
This Adobe host is used when assets/an entire site are (somewhat incorrectly, but legitimately) exported from Adobe XD or any of their newer apps when used alongside XD. I also had to whitelist it in order for the new Chelsea FC website to function correctly (along with 'sp.auth.adobe.com'). I agree that it is poor implementation on their part, but if it's happening with some of these large corporate redesigns, I can imagine that we will only see more and more sites having the same issue.

**Comment by lightswitch05** [comment]
@WillPresley `sp.auth.adobe.com` is not currently blocked in this project.

It looks likes `assets.adobedtm.com` was whitelisted by MVPS. Its without a doubt a tracking site, but if its causing a lot of people issues I'll move it to my aggressive list, which is not in this project. If anyone doesn't mind a few broken sites, I recommend adding `assets.adobedtm.com` to your own blocklists.

**Comment by StevenBlack** [comment]
Closing...

**Comment by egold** [comment]
Closed GH issue I know, but wanted to just add that CrateAndBarrel.com also relies on JavaScript hosted on that domain in order for their product details pages to work. When blocking that domain (Privacy Badger in my case) color picker and other product details javascripts spew JS errors.

**Comment by lightswitch05** [comment]
`assets.adobedtm.com` is no longer blocked in this project

**Comment by matthewparkes** [comment]
Also thought I'd let you know that the login for `https://www.disneytravelagents.ca/`doesn't work with `assets.adobedtm.com` blocked

**Comment by StevenBlack** [comment]
Hi @matthewparkes, `assets.adobedtm.com` is blocked by a rock-solid curator, the fine folks over at [mvps.org](http://winhelp2002.mvps.org/).  Please take this up with them at email winhelp2002@gmail.com.

Thanks!

**Comment by spirillen** [comment]
> This Adobe host is used when assets/an entire site are (somewhat incorrectly, but legitimately) exported from Adobe XD or any of their newer apps when used alongside XD. I also had to whitelist it in order for the new Chelsea FC website to function correctly (along with 'sp.auth.adobe.com'). I agree that it is poor implementation on their part, but if it's happening with some of these large corporate redesigns, I can imagine that we will only see more and more sites having the same issue.

Of curse you will see more of this. Why? because you let them. If you write to them telling them they lost a user whom they could track and sell data from, and to manipulate you to spendt more of your hard earned money on there product, which I'll guess is something with a ball, then things would start changing.

The best you can do second to e-mail the soccer's... stop using there website, and by all means stop whitelisting fucked up domains.

Seriously, who is it that is messing up the websites, is it anti tracking/spying lists like these, or is it the website owners?  

I know my answer to this, what is yours answer? think about it next time you're about to do some whitelisting, and the long term consequences of it..

**Comment by sangaman** [comment]
FYI, I had to whitelist this domain to get several features on chrysler.com to work.

**Comment by erdnuesse** [comment]
FWIW: I needed to whitelist this (on one device; trial and error with 10 domains) for MSNBC and Eurosport Apps to work on Android TV
