### ISSUE TITLE
How come you're blocking everything that isn't fake news?

### ISSUE THREAD

**Issue by blackoutworm** [StevenBlack/hosts#721]
In your fakenews host file, most of these sites aren't even remotely fake news.
You're blocking sites like breitbart and drudgereport, when you should be blocking extreme left leaning agenda sites like cnn, msnbc, and snopes. Not that you should be blocking any of them in the first place. But I'm just saying. Something tells me you have a bias against right and just overall agenda-free news media.

**Comment by thunderpants** [comment]
wow ,what the hell is going on with these host files.
This is pretty shocking and very sad if it's true.
The most violent and ferocious are always the insane lefties ,it's not hard to see for oneself.
But why are we even thinking about this in regards to a blinking hosts file?

**Comment by blackoutworm** [comment]
@thunderpants yea I know, right? I just wanted to point this out because there's an extension called fakenews.
It's like they created it to troll people. Because the other two extensions make perfect sense. "Gambling" and "porn". But once you block sites for having an opinion or political views, you're going down a slippery slope. And no matter what sites you add to that blacklist, it'll always be wrong.

**Comment by funilrys** [comment]
Hello there and welcome here. 

Please report to https://github.com/marktron/fakenews/issues for all issues regarding fake news. 

Cheers,


Reference:
* https://github.com/StevenBlack/hosts/blob/master/extensions/fakenews/update.json#L6
* @marktron

**Comment by kronflux** [comment]
Riiiiiight. Let's not bring strong political views into something intended to help people by controlling sites with proven malicious intent.
I assume this entire issue was a troll, but regardless, let's keep it relevant. Opinions do not equate to facts.
The "Fake News" list is intended to block sites which regularly use clickbait titles when having nothing related to them in the actual articles, regularly "quote" people having said something they've never even discussed the subject matter of, and sites which spread just general disinformation.
This isn't a "Left" or "Right" issue, this is an issue related to information accuracy on a regular basis.
Just because a site usually posts articles which are well documented and provide accurate information, does not excuse them of their malicious articles.

As explained by @marktron in the actual fakenews list project, it is largely opinion based, and sites may be judged differently by another curator. That being said, I've yet to see a site in that list which I disagree should be included.

Keep in mind this extension to the hosts list is Optional, and the actual project, as pointed out by @funilrys is where you should report any problems in regards to it's entries. Please keep in mind, however, that the same information will likely be reiterated there as well.

**Comment by StevenBlack** [comment]
Thanks for your input, everybody.  Your views matter, and are noted.  I'm going to close this now.

**Comment by blackoutworm** [comment]
@kronflux "As explained by @marktron in the actual fakenews list project, it is largely opinion based" and that's the problem. Stop sounding like a woman.

**Comment by StevenBlack** [comment]
@kronflux I'm sorry,  Never mind this idiot.  I apologize to you for running a repo that attracts people like @blackoutworm.

Locking this thread.  @blackoutworm please don't ever come back here.
