### ISSUE TITLE
do link shorteners count or not count as blocked?

### ISSUE THREAD

**Issue by inversephase** [StevenBlack/hosts#733]
Hi, a few of my friends and fans use your list. I was recently blindsided by a few of them could not access links I shared with a shortener. Sure enough, buff.ly is on the list, however I checked for other shorteners and just one example, bit.ly is not. 

Anyway, forgive me getting to the point: what gives? Surely bitly is considered a more spammy link shortener than buffer/buffly? There are a lot of legitimate people using buffer to save time in getting their message out. I myself am an indie musician and I would waste all day online if I didn't have work to do, so I'm trying to stay out of that pit of despair.

At a cursory glance of the types of things that are blocked I'm not sure if shorteners are considered "social", I just want to understand what's going on and help improve the project with my feedback if I can.

**Comment by lightswitch05** [comment]
@inversephase in commit lightswitch05/hosts@cb7ab86d7d8fd6319242786c5011de259dadf6f3 I removed `buff.ly` from my ads-and-tracking list and moved it to my aggressive list instead - which is not part of this project. Everyone maintains their own lists as they see fit. I don't have a specific stance on link shorteners but definitely don't like breaking sites for people. I don't use social media, so sometimes it can be hard to sort the trash from useful tools, especially regarding social media since all of it can fall into ads and tracking in some way or another. I hope this answers your question, please close the ticket if so.

**Comment by StevenBlack** [comment]
Thanks @lightswitch05!

This is included in the [latest release](https://github.com/StevenBlack/hosts/releases).

Closing.

**Comment by inversephase** [comment]
thanks for the quick responses on this, sorry I was not so quick on my reply. appreciated!
