### ISSUE TITLE
Why are web browser crypto mining sites blocked?

### ISSUE THREAD

**Issue by BackToPyramidOne** [StevenBlack/hosts#784]
Most sites, like jsecoin and coinhive, have a mandatory opt in. While they do have a hidden miner as well, it is sourced from another domain.

**Comment by StevenBlack** [comment]
Thank you for your concern @BackToPyramidOne.  

I'm coming to appreciate this as a wedge issue.  I'm unsure what to think about it.  It's not cut-and-dry, as you point out.

For now I'm very comfortable letting the domain experts here make these tough calls.

Thanks folks.

Closing.

**Comment by anudeepND** [comment]
@BackToPyramidOne Personally I don't care whether it's opt-in or opt-out. Firstly, as @lightswitch05 said your ad preference will be reset after clearing cookies. 

Even ad and analytics companies give you choice to opt-out, would you stop using host files? And they do very very nasty stuff for example AdThink and OnAudience, were actively exploiting  built-in password managers on browsers. You can read more about it [here](https://thehackernews.com/2018/01/browser-password-managers.html)

Any information whether it's error logs for "improving their product" (*cough* Sentry..
 *cough*) or data used for targeted advertising,regardless of opt-put they should be blocked.

**Comment by BackToPyramidOne** [comment]
This really isnt about ads, this is about an alternative to ads that many website owners implement in order to make a little profit, unintrusively. Ad tracking is a whole 'nother issue.

**Comment by kronflux** [comment]
Another opinion never hurts.. So in general, I agree these should be blocked. While I fully understand that there are legitimate uses for these types of sites, opt-in or not, I feel uncomfortable with the concept, nor completely trusting of the idea that these will be used only as a revenue for websites.

As @StevenBlack said, I believe this is a far more in-depth issue than it seems on the surface. However, generally speaking it seems to have a bad wrap by the IT community as a whole.

**Comment by Technetium1** [comment]
If you care enough about a site to run a crypto miner for support, then it doesn't seem to be asking much for you to whitelist a domain too. After all, using a miner should be something you get a choice in... right?

**Comment by BackToPyramidOne** [comment]
@anudeepND guess how many of these viewers will actually go ahead and donate to the dev.

**Comment by BackToPyramidOne** [comment]
Alright, looks to me like these sites should remain blocked then, considering the effects on battery, etc.

**Comment by BackToPyramidOne** [comment]
@lightswitch05, just wanted to let you know, its actually implemented using a script from another domain, in the case of coinhive.

**Comment by lightswitch05** [comment]
But how would the script remember that I have opted out if it does not store a cookie? One great alternative to this is to just not ask users to opt-in if they have their browsers configured to send a 'do not track' signal. Consider the 'do not track' signal as the global opt-out. I know this use case doesn't fit in great for crypto since its not necessarily tracking, but its an option.

Without using the 'do not track' signal, it must store a cookie to remember my selection - a cookie that will be rejected by my configuration. Another option is to just ask the user every single time they visit the page - which is essentially the same thing for me since my cookies get blocked. Anyways, asking the user to opt-in to something every single time they visit the page is a very poor user experience, and depending on how its asked, could become close to harassment of the user - which I would argue is an acceptable case to block something in this list.

Anyways, I'm very unhappy with the current implementations of 'opt-out' or 'opt-in' solutions and its not directly related to crypto. One more note, for the list I manage, websites that respect my 'do not track' signal do not get added to my list, because I never see their domain popup as tracking me. So that is some incentive to not add these types of services when the browser sends the 'do not track' signal. I'll step down from my soapbox now 😆

**Comment by BackToPyramidOne** [comment]
@lightswitch05 its not a cookie
the script src= is physically pulled from another domain. No cookies are ever used.

**Comment by BackToPyramidOne** [comment]
This is done on a per website basis
The cookie is served when you click 'yes'

**Comment by BackToPyramidOne** [comment]
for a short period of time i.e a week

**Comment by lightswitch05** [comment]
ok, so the user is asked every time unless they say yes once

**Comment by BackToPyramidOne** [comment]
When they say yes, the cookie expires in a day for that particular domain
