### ISSUE TITLE
Encrypted subdomains for routing ads

### ISSUE THREAD

**Issue by mrchief** [StevenBlack/hosts#801]
Some sites have started to use encrypted subdomain names to route ads. 

E.g. 
`https://www.boston.com/culture/travel/2018/10/09/you-wont-need-an-airport-to-board-this-plane-which-will-get-you-from-boston-to-new-york-city-in-36-minutes` routes ads through `https://c-6rtwjumjzx7877x24yuhx2elttlqjx78dsinhfyntsx2ehtr.g00.boston.com/...`

Here's another: 
`https://c-6rtwjumjzx7877x24bbbx2esfstanx78twx2ent.g00.newsweek.com/...` from `https://www.newsweek.com/kavanaugh-described-himself-and-friends-loud-obnoxious-drunks-1983-letter-1150388` may have to go through [reddit link](https://www.reddit.com/r/politics/comments/9l1c4l/kavanaugh_described_himself_and_friends_as_loud/) to get this version.

Found something related that sheds more light on this `g00` crap: https://github.com/uBlockOrigin/uAssets/issues/227

I wonder if there's a way to capture these domains and add them to the list?

**Comment by mrchief** [comment]
It's InstartLogic crap it seems: https://www.theregister.co.uk/2017/08/11/ad_blocker_bypass_code/

**Comment by lightswitch05** [comment]
According to their [documentation](https://docs.instartlogic.com/ad-recovery/what-is-ad-recovery%253F/), they rely heavily on `X-Forwarded-For` headers. That might be useful for UBO to block based on, but its not much use for hosts files

**Comment by StevenBlack** [comment]
Ya Daniel @lightswitch05 this is ultimately outside the scope of hosts files.

Let's go per-case which will work, for awhile anyway.

**Comment by mrchief** [comment]
How do we efficiently figure out all those cryptic domains? I'm not familiar with current process (of collecting domains) but I was thinking if we can just scrape those sites listed in the register article and gather those domains - as a way of automating things a bit?

**Comment by funilrys** [comment]
Thanks for the input @lightswitch05 might be interesting for the `mining` option of PyFunceble :smile_cat:

**Comment by StevenBlack** [comment]
By the way, @lightswitch05 I've left this Newsweek page open for the past three hours.

Since the page was first open, it has tallied 3,855 requests, and counting.

Which is outrageous, of course.

**Comment by lightswitch05** [comment]
😱 After reading the linked Register article above, InstartLogic has gone beyond ads and tracking. The various methods they are using to avoid detection is nothing short of a Rootkit for the browser.

**Comment by mrchief** [comment]
@StevenBlack I blocked those 5 hosts but the ads still filter through. And I'm not sure how blocking them will be effective. InStart is generating these obfuscated domains on the fly and that's what the browser resolves.

However, `0.0.0.0 newsweek.com` gets rid of the root cause! 😁 I don't think those news sites produce any news that's not available elsewhere.

**Comment by mrchief** [comment]
webmd joins the list :(

![image](https://user-images.githubusercontent.com/781818/47262515-2420cb00-d4b8-11e8-9480-a8ae7f594793.png)

**Comment by mrchief** [comment]
There's nothing hostfiles can do though. These encrypted domains are generated on the fly. The only way out it seems is for some scripted ad blocker to look for patterns and block them. I hope brave browser can come up with a fix soon.

**Comment by mrchief** [comment]
uBlock origin can block these with `*.g00.*` filter but this effectively breaks the sites as they serve all content (and not just ads) via Instart crap.

**Comment by dnmTX** [comment]
AdGuard managed to block it by breaking the inline script that generates them(just FYI). Reading through the script it looks like the main domain is `assets.insnw.net` aka `ins-007.inscname.net` aka
 `a-vip01.insnw.net` .Not sure if blocking those will make any difference though but i guess it's worth the try .

**Comment by mrchief** [comment]
I blocked all 5 via hosts and it seems to work (at least on webmd). Nice work @dnmTX 

@StevenBlack not sure if you want to keep this open but for now, I think those 5 additions will do.

`0.0.0.0 assets.insnw.net ins-007.inscname.net a-vip01.insnw.net feed.engage.im s.iaudienc.com`

**Comment by dnmTX** [comment]
Just to clarify,`feed.engage.im` and `s.iaudienc.com` are not part of **InstartLogic** so lets focus on finding and blacklisting all *.insnw.net subdomains before things get out of hand.
PING @lightswitch05 (c'mon man,where you at? 😄)

**Comment by lightswitch05** [comment]
@dnmTX looks like `feed.engage.im` is already in this project per KADhosts

```
# Start KADhosts
0.0.0.0 feed.engage.im
```

Personally, I'm not seeing any `insnw.net` or `inscname.net` calls on webmd. Perhaps they disable themselves on firefox. I'm hesitant to add them without being able to test that they don't break anything first. I did add a couple other hosts I found while taking a look.

**Comment by lightswitch05** [comment]
I decided to load it in Chrome to see what was up- now I see all those `insnw.net` `inscname.net` calls. I decided to add them to the list in https://github.com/lightswitch05/hosts/commit/edfcd3a89b8e37d3d4f0268ed0792b1719ca77d5 - I'm not holding my breath that these don't break things, but it doesn't break webmd at least. This is just one of many reasons to stop using Chrome.

**Comment by dnmTX** [comment]
> @dnmTX looks like feed.engage.im is already in this project per KADhosts

I personally removing the KADhosts once the lists is loaded on my end due to the maintainer of that lists is mostly focused on Polish domains and it's just "extra weight"(i don't browse Polish websites anyway),that's why.
Thanks for adding the `*.insnw.net` and `.inscname.net` domains.I personally don't think that anything will break.Even if there is a complaint in the future,please,don't remove all of the at once.As you see their tactics are super aggressive and unfair.

**Comment by dnmTX** [comment]
Ok...i see now what you mean.In `newsweek.com` most of the pictures and not loaded and the same encrypted subdomains are present but there are no ads at least.I think we need to re-evaluate and see which of those deliver the pictures and remove them.

**Comment by lightswitch05** [comment]
@dnmTX no, `newsweek.com` broke when I added `www.sdad.guru`. The block is fine for Firefox, but stops chrome from loading the images. This has to be somehow tied in to InstartLogic since the behavior is different per browser. Anyways, I removed it in https://github.com/lightswitch05/hosts/commit/fa90b39af09d1a2cd84c67c0fe5e013c7be119c9 . Browser specific behavior is going to make this very irritating

**Comment by dnmTX** [comment]
@lightswitch05  yep,much better now.Thanks

**Comment by dnmTX** [comment]
With respect to Steven @StevenBlack  and due to recent events this is me just spreading awareness as we all here figured it out the hard way how aggressive and scrupulous Instart Logic is. So,in order to continue blocking the domains you need to load [@lightswitch05's](https://raw.githubusercontent.com/lightswitch05/hosts/master/ads-and-tracking-extended.txt) lists in addition to @StevenBlack's one.
For the more paranoid ones who are using **iptables** you can add the following rules as well,but take a note that the IP's are subject to change(...or not) but better safe then sorry:

`iptables -I FORWARD -d 192.33.31.0/24 -j REJECT
iptables -I FORWARD -d 159.180.84.0/24 -j REJECT
iptables -I FORWARD -d 159.180.64.0/24 -j REJECT
iptables -I FORWARD -d 159.180.65.0/24 -j REJECT
iptables -I FORWARD -d 192.33.0.0/16 -j REJECT
iptables -I FORWARD -d 192.33.29.0/24 -j REJECT
iptables -I FORWARD -d 159.180.0.0/16 -j REJECT
iptables -I FORWARD -d 103.243.0.0/16 -j REJECT
iptables -I FORWARD -d 103.243.13.0/24 -j REJECT`

GOOD LUCK Everyone 👍

**Comment by mrchief** [comment]
@dnmTX iptables block? Never heard of it before. You learn something new everyday!

**Comment by mrchief** [comment]
Thinking about a way to handle changing IP addresses, it should be possible to automate (cron, scheduled tasks etc.) via a script - resolve Instart hosts to IPs and add them to iptables, no?

**Comment by funilrys** [comment]
May I mention a project I started but never really ended https://github.com/funilrys/hosts2iptables ?

**Comment by dnmTX** [comment]
Well...as blocking IP ranges sounds promising i already stumbled on false positives so i'll remove the rules before more users here start getting bad experience.So far it's just one IP but couldn't figured it out how to whitelist it. 🤔
Let's stick to the domain blocking for now.

**Comment by rautamiekka** [comment]
> @dnmTX iptables block? Never heard of it before. You learn something new everyday!

Never heard of **firewalls** ?

**Comment by mrchief** [comment]
> Never heard of **firewalls** ?

LOL, yeah. But it never occurred to me that one could use the same for blocking ads.
