### ISSUE TITLE
[www.autoblog.com] embedded player not loading

### ISSUE THREAD

**Issue by dnmTX** [StevenBlack/hosts#802]
Generally the player is hosted on `cdnapisec.kaltura.com` but **`cfvod.kaltura.com`** is the one that redirects to it and it's blocked.Removing it from the lists fixed the problem.Naturally there were several tracking/telemetry domains that `cfvod.kaltura.com` brought back which were already blocked so i don't see any reason to remain blacklisted.
https://www.autoblog.com/2018/10/10/florida-man-crashes-lamborghini-video/?ncid=edlinkusauto00000021&yptr=yahoo

![autoblog](https://user-images.githubusercontent.com/34774426/46881495-5889ec80-ce11-11e8-95f5-7ef0b66d6f5e.png)

![autoblog1](https://user-images.githubusercontent.com/34774426/46881503-5c1d7380-ce11-11e8-94a0-568f7a8f0381.PNG)

**Comment by StevenBlack** [comment]
@dnmTX fixed!  This will appear in the next release.

**Comment by spirillen** [comment]
@StevenBlack I've just tried that link @dnmTX have applied, and i'm redirected straight to guce.advertising.com so I would unlist that domain.... just my two cents

**Comment by dnmTX** [comment]
That is absolute BULLSHIT !!!!! Player is **WORKING**,no advers are showing up.
@spirillen  not sure where you poped up from but **STAY AWAY** from my posts.PERIOD !!!!!!!

**Comment by spirillen** [comment]
@dnmTX your language is rather doll, what i post is what is happening, otherwise i wouldn't post is,,, **PERIOD !!!!!!!** so please be quiet when the adults talk :P So if I have seen that action of being reirected to guce.advertising.com, then that was happening, otherwise i wouldn't have posted it.

That's was is called reporting a result of a test.

Next step is to see what other reports..... not that the you start shouting like a five years old girl ...

The two things your achieving by that kind of behavior is one, you end on users blacklist, two you kill a good descent project like @StevenBlack 's

Happy new year :)

**Comment by dnmTX** [comment]
Steven @StevenBlack  you mind locking this one up? Don't really feel like arguing with some degenerate.
Thank you.

**Comment by StevenBlack** [comment]
@XelNika dude, I have no idea what you're talking about.

We are an aggregator of well-curated sources of hosts files.  We merge them, de-dupe the result, and provide optional ways to mix-and-match extensions for things like social media, porn, and gambling, and we make these products available online, refreshed every few days.

This is all in the readme if you have any questions.

**Comment by dnmTX** [comment]
I allowed cookies,disabled the adblocker, thoroughly checked the webpage code and there is no sign of anything close to `guce.advertising.com` showing up or present.I don't know what you two are **smoking** but you need to let it go. 
Steve @StevenBlack ,do me a solid and **lock** this post.Thanks.
