### ISSUE TITLE
How do I schedule this on macOS?

### ISSUE THREAD

**Issue by NightMachinary** [StevenBlack/hosts#819]
I have tried executing this script as root with launchd, but I get no output, even though I see the process running in htop:
```#!/usr/bin/env bash
export HOME=/Users/evar
source /users/evar/.bashrc
/Users/evar/anaconda/bin/python /Base/_Code/Misc/hosts/updateHostsFile.py --auto --replace --backup &> /Users/evar/log/hosts.out2
```
The `/Users/evar/log/hosts.out2` stays empty.

**Comment by StevenBlack** [comment]
Hi NM, my first guess is, `cd` into `/Base/_Code/Misc/hosts/` because `updateHostsFile.py` presumes, among other things, the presence of a subfolder named `data/` containing, well, hosts data from potentially many sources.

**Comment by NightMachinary** [comment]
No, this is not it, since everything works fine when I run this script with
sudo. The problem is with the environment launchd is using for the script.
I created this issue more to see what other people are using, so I can just
copy theirs.

**Comment by rautamiekka** [comment]
Well, for one, the line `source /users/evar/.bashrc` has an error: `/users`

**Comment by pradorocchi** [comment]
Hi, 
here is a full working setup for MacOS Daemon, updating hosts file every 2 hours, running as a [root] daemon by launchd (does not depend on any user logged in, and updates in background automatically)

This setup is valid/tested/ currently running on MacOS 10.14 Mojave and the recent macOS 10.15 Catalina (I have not tested it on older versions, but it may work)

I will write a full-tutorial below and put content of the needed files to be created [my daemon script and a bash execution script] (use or modify them for your needs):

1. **Download Steven Black tools** and scripts:
    https://github.com/StevenBlack/hosts/archive/master.zip

 

2.  **Install Python3**, get it from https://www.python.org/downloads/mac-osx/ 
    Current release is 3.7.4:
    Direct download link:
    https://www.python.org/ftp/python/3.7.4/python-3.7.4-macosx10.9.pkg

![Screen Shot 2019-08-04 at 07 08 47](https://user-images.githubusercontent.com/16503639/62422306-bc262480-b686-11e9-894c-f26c14abee29.png)

use the installation defaults until finished.

![Screen Shot 2019-08-04 at 07 12 32](https://user-images.githubusercontent.com/16503639/62422340-600fd000-b687-11e9-9135-866681c41f50.png)

- Important: From this Python version we need to install the updated SSL certificates on MacOS to be able to download files from HTTPS URLs (see above message about it) because it uses a newer updated SSL version than the one shipped on MacOS [which is old and have security issues]. Any aditional information about it can be found by clicking on the message when you finish the Python3 installation, and is also available via Finder on /Applications/Python folder that was created by the install program above. 

 
____
**_Everything below here is done via Terminal, open a new terminal window and proceed._**
____

3. **Install the SSL certificates** for Python3:

        `sudo -H /Applications/Python\ 3.7/Install\ Certificates.command`
 
        ![Screen Shot 2019-08-04 at 09 56 46](https://user-images.githubusercontent.com/16503639/62423948-3b732280-b69e-11e9-93c6-02368d3ee75c.png)


4. **Create a directory** for the job, owned by root, on the proper location for a system daemon [which is outside any user's directory]. Lets call it _hosts-Blacklister_ :

        `sudo mkdir /Library/hosts-Blacklister`
        `sudo chmod 755 /Library/hosts-Blacklister`

        Verify it with `ls -ld /Library/hosts-Blacklister` (the directory permission must be like): 
        `drwxr-xr-x  35 root  wheel  - 1120 Aug  4 06:55 /Library/hosts-Blacklister/`

        ![Screen Shot 2019-08-04 at 07 18 58](https://user-images.githubusercontent.com/16503639/62422390-4458f980-b688-11e9-8f48-2ae4c9f45ffc.png)

- Note: The default directory permissions on MacOS for new directories already is 755. But I enforce the use of the chmod command because on some systems you may have a different system default permissions for new files/directories [adjusted by the system UMASK parameter], so the chmod command here ensures we will have the needed directory permissions for this case. 

 

4. **Extract the zip** file and put the files on the right place:

        `sudo unzip ~/Downloads/hosts-master.zip -d /Library/hosts-Blacklister/`
        `cd /Library/hosts-Blacklister/`
        `sudo mv hosts-master/* .`

 
    At this point, all the files are on the right place. Let's complete the setup requirements:
    
        > Check python installation by executing: 
            `python3 --version`
                must return: **Python 3.7.4**

        > Install the requirements for StevenBlack's scripts:  
          `sudo -H pip3 install -r requirements.txt`

        If everything runs OK you will see this result:

        ![Screen Shot 2019-08-04 at 09 59 30](https://user-images.githubusercontent.com/16503639/62423981-afadc600-b69e-11e9-92f7-bf0a1b75f5b5.png)

 
____
**The SETUP phase is complete! Next phases:** 

- Manually test the execution and hosts creation
- Create the Daemon for auto-update
- Install the Daemon
____

 

5. Let's **manually execute** the main Steven Black's python script to update the sources and create the new and updated **hosts** file. 

        `sudo -H python3 ./updateHostsFile.py --auto`

        ![Screen Shot 2019-08-04 at 10 08 19](https://user-images.githubusercontent.com/16503639/62424052-d28caa00-b69f-11e9-8a3e-e2e89c413c2a.png)

 

Everything above is fine, you can check that a hosts file was created inside the current directory. This means all StevenBlacks routines did run fine and we are **ready** to create our Daemon. The daemon will execute the command we manually executed above and will copy the created/updated hosts file to /etc/hosts.

 

6. We need to **create a .plist file** on** /Library/LaunchDaemons** so MacOS will load it on boot time as a system service. 

`sudo vim /Library/LaunchDaemons/local.updateHosts.plist`

copy and paste this XML code inside the plist file:


```

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>local.updateHosts</string>
        <key>ProgramArguments</key>
        <array>
                <string>/Library/hosts-Blacklister/local.updateHosts.sh</string>
        </array>

        <key>EnvironmentVariables</key>
        <dict>
            <key>PATH</key>
            <string>/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Apple/bin</string>
        </dict>
        <key>StandardOutPath</key>
        <string>/Library/hosts-Blacklister/hostupdate-exec.out.log</string>
        <key>StandardErrorPath</key>
        <string>/Library/hosts-Blacklister/hostupdate-exec.err.log</string>
        <key>StartInterval</key>
        <integer>7200</integer>
    </dict>
</plist>


```

The content above is the right way to create a daemon on MacOS. There are other documented features for other specific cases, but for what we need this is it. The XML above is telling to:
- Create a new daemon called "local.updateHosts"  [key **label** is the daemon name]
- Pointing it to a shell script to be executed (we will create it below) [key **ProgramArguments** is the executable]
- Passing a basic PATH to the daemon environment session, so our executable shell script can be executed correctly.
- Redirecting sdtErr and stdOut to 2 files, this will allow us to see if any error is happening or if everything is running fine. Otherwise it would be impossible for us to see the output of both our shell script and the StevenBlack's python scripts.
- Setting the execution interval to 7200 seconds [60 * 60 * 2] which is 2 hours. 

**You can change the interval to what is better for you.** This interval is measured since the computer boots. It is not every 2 hours on the watch clock [like linux cron does]. 
Eg: If you boot your computer at 08h25, it will be executed on boot time, then at 10h25, 12h25... every 2 hours after the initial [or last] time it was executed.

 
7. Create the shell script to be executed:

`sudo vim /Library/hosts-Blacklister/local.updateHosts.sh`

```
#/bin/bash

# We need to 'cd' to our correct directory. We are called from the outside
# by the daemon, so we need get inside here to execute the scripts that
# live here and for their directory references be OK for execution.
#
cd /Library/hosts-Blacklister/

# The 2 lines below are used to clean the log files on each run, this
# way it will only contain the results of the last execution. This is
# to keep the log files small, because we don't need to check older
# logs on it. If any problem is happenin the most recent messages are
# enouth for troubleshooting. And also we don't want a big or huge log
# filling up space on the disk. Considering it is very difficult for
# the update script to have problems, if we do not clean the log files
# it for sure would be forgotten here growing and growing forever..
#
# If you want to keep it growing, comment those 2 lines below.
#
# PS: we cannot delete these log files here inside this script and
# recreate them here, because doing it will prevent the redirected
# outputs to be put inside them by the daemon.
# They MUST be created only by the daemon plist, but we can erase them
# by using the echo command below.
#
echo starting > hostupdate-exec.out.log
echo starting > hostupdate-exec.err.log

# Why not check everytime for the requirements? If our python install
# were changed or requirements were remove from the outside by some
# admin user, we install it again. Keep the hosts file updated and
# secured is a priority. So check on every execution to keep sure.
pip3 install -r requirements.txt


# Lets call the update python script to update.
# here I am using the --auto flag to prevent any execution questions.
# also I am using the --replace flag for it to copy hosts file to /etc/hosts
# I am also adding some extension to extend the file to have fakenes
# and gambling lists. Other complementary lists can be added following
# documentation rules on https://github.com/StevenBlack/hosts
#
python3 ./updateHostsFile.py --auto --replace --extensions fakenews gambling


# commands below are not currently working, they are 3 variables that
# stores the size of the error log, the size of the execution log and
# how many unique entries the hosts file contains.
# The 3 variables are being filled correctly.
#
#
# But this is what does not work: if the size of the error log is
# greate than zero (remember we cleared the log on each run) than
# some error happened, if this was the situation than a message via
# osacript on the Notification Desktop area should appear. But we
# are running as a root deamon, and the GUI logged user is no root,
# so the message never appears. I need to fix it so the message goes
# to the logged user desktop.
#
# The logic below is correct and working, it is just the message that
# is not appearing. If you run this shell script using sudo you will see 
# a Notification message on your desktop via MacOS notification center.
# TODO: need to fix it to show when running as daemon.

# Variables to hold log filenames
#
file_err=hostupdate-exec.err.log
file_log=hostupdate-exec.out.log

# variable to hold quantity of host entries created
#
qtdBloqueios=$(wc -l <"hosts")

# minimum size for alert (remember we put some content on it, which
# is the word 'starting' and it contains 8 characters, the file will be
# 9 bytes in size, so notify only if greater than 10 bytes.
#
minimumsize=10

# variables to hold the size in bytes for the logfiles
#
tamanhoLog=$(wc -c <"$file_log")
tamanhoErr=$(wc -c <"$file_err")
qtdBloqueios=$(wc -l <"hosts")

# condition check and alert on Notification Center
#
if [ $tamanhoErr -gt $minimumsize ]; then
    osascript -e 'display notification "Error updating hosts Blacklist /etc/hosts" with title "Erro"'
fi


```

8. Make our script executable:

    `sudo chmod +x /Library/hosts-Blacklister/local.updateHosts.sh`

 

9. **Tell launchd** we have a new daemon to load on every boot (we are now installing our daemon)

    `sudo launchctl load /Library/LaunchDaemons/local.updateHosts.plist` 

 

10. Check if our daemon is installed:

    `sudo launchctl print system |grep local` 

    This command must return: `0      - 	local.updateHosts`

 
11. Enable it: 

    `sudo launchctl enable system/local.updateHosts`

 

11. **Start and Run it** for the first time without having to reboot now.

    `sudo launchctl kickstart -p system/local.updateHosts`

    This command is to force service execution, and it will print the service PID. Wait a few seconds and you will see the 2 logfiles created on `/Library/hosts-Blacklister` and after some seconds the hosts file will be updated (check its date), see the contents of the logfiles, and execute `ls -l /etc/hosts` and check its size, date, and updated content. 
 
    From now on, every 2 hours it will updated the hosts file. 
    After every reboot it will be loaded, because we installed it on item 9 and will run every 2 hours automatically. 

____
**This is it, now you have a true MacOS daemon doing this job for you.**
____
 

PS: if you need to disable it: `sudo launchctl disable system/local.updateHosts` and it will not start on boot. 

 
If you need any additional information or have any problem, feel free to contact me here on Github.

Rafael Prado

**Comment by pradorocchi** [comment]
I forgot to mention the author @NightMachinary and @StevenBlack

**Comment by NightMachinary** [comment]
Thanks! I actually decided not to use this on my mac; I use it on my VPN
server. This way I can easily disable it. It also works for all of my
devices.
And I haven’t updated the hosts file on that server in ages, too. Seems
like ads aren’t that fast to adapt? :))
