### ISSUE TITLE
block more adult sites

### ISSUE THREAD

**Issue by betzalel102** [StevenBlack/hosts#830]
0.0.0.0 www.sexmagic.co.il
0.0.0.0 www.zesex.co.il
0.0.0.0 www.afarsex.co.il
0.0.0.0 www.tuta.co.il
0.0.0.0 www.shovavon.co.il
0.0.0.0 www.sexmovies-free.com
0.0.0.0 www.bsex.co.il
0.0.0.0 www.sexhinam.co.il
0.0.0.0 www.hdfuckporn.com
0.0.0.0 xnxxfree.icu
0.0.0.0 www.kamasex.co.il
0.0.0.0 www.exhilawriting.com
0.0.0.0 www.yousex.co.il
0.0.0.0 www.newcam18.com
0.0.0.0 sex69.co.il
0.0.0.0 hotcams.co.il
0.0.0.0 www.sexmania.co.il
0.0.0.0 www.russiansex.co.il
0.0.0.0 www.zbeng.co.il
0.0.0.0 www.monika.co.il
0.0.0.0 sexxes.co.il
0.0.0.0 www.shovavon.co.il
0.0.0.0 agaslive.wordpress.com
0.0.0.0 www.sexooops.com
0.0.0.0 www.sexil.co.il
0.0.0.0 www.sexatraf.com
0.0.0.0 www.xnxxfreeporno.com
0.0.0.0 www.partyporn.co.il
0.0.0.0 www.globalsex.co.il
0.0.0.0 hugesex.tv
0.0.0.0 www.fapvid.com
0.0.0.0 porn-ok.com
0.0.0.0 ooo-sex.com
0.0.0.0 yo-sex.com
0.0.0.0 www.bigporn.com
0.0.0.0 ziunim-hinam.blogspot.com
0.0.0.0 www.seex.co.il
0.0.0.0 www.badabing.co.il
0.0.0.0 www.arabtube.co.il
0.0.0.0 www.missx.co.il

**Comment by StevenBlack** [comment]
Ping @sinfonietta

**Comment by spirillen** [comment]
Why not implement the list from [Blacklists UT1](http://dsi.ut-capitole.fr/blacklists/index_en.php) and use the adult tar is have 2019660 entries

Yes this would require a rewrite to the python files, but it's rather up to date...

But that's maybe just me, but why block porn? as a European I never understood this American way of doing things..... 
Why not just be teaching in the bee and flowers?....

**Comment by StevenBlack** [comment]
@spirillen because I'm absolutely not interested in a hosts file that's 2 million entries long.  

Most users of legacy MS Windows would immediately loose internet access.  Many mobile devices would slow to a crawl or cease functioning.  Host-file-aware routers would slow to a crawl, and some would stop working altogether.

At one point we added a data source with 300,000 entries and had to drop it within hours.

Using active, curated sources is the best way forward, and nobody can curate a 300,000 entry list, nevermind 2 million.

**Comment by Sinfonietta** [comment]
@StevenBlack this is done in commit https://github.com/Sinfonietta/hostfiles/commit/249e5a9fc56a0132657afbd20923c33c8ff24c47

**Comment by StevenBlack** [comment]
Thanks @Sinfonietta!  Closing.
