### ISSUE TITLE
Do you know Adzhosts ?

### ISSUE THREAD

**Issue by pierrocknroll** [StevenBlack/hosts#84]
I could be great to include it !

**Comment by lmorg** [comment]
I'm not the project maintainer, but from a personal perspective I'd rather not as Adzhosts is hosted on SourceForge (oh the irony).

This repo does include quite a number of excellent lists already as well as a few originals as well. And these lists are large enough that there's already quite a number of duplicates. So I'm not convinced Adzhosts offers much that might be missing.

However I'm not the project maintainer, so that's just my 2c worth :)

**Comment by Laicure** [comment]
I tried merging it (Adzhosts' _0.0.0.0_ in their zip file) with @StevenBlack's list and...:
File Size: 3.37MB
Unique Entries: 112,614

**Comment by StevenBlack** [comment]
Ya, I agree with @lmorg, not from SorceForge.   :-)
