### ISSUE TITLE
Block YouTube Ads

### ISSUE THREAD

**Issue by csib** [StevenBlack/hosts#850]
Hi,

I read the older issues about blocking YouTube ads, but they are really old, not relevant for now. In my tests this solutin doesn't block YouTube ads. Is is possible to add this in a future version?

Thanks!

**Comment by anudeepND** [comment]
@csib Currently it's not possible to block YouTube ads via host file method, because YouTube serve both ads and content from the same domain. If you use Pi-hole on your network, check this out: https://www.reddit.com/r/pihole/comments/9w5swx/i_think_ive_managed_to_block_youtube_ads_with/
But there is not guarantee that this method block YT ads.

**Comment by kronflux** [comment]
It's also worth noting that using a web browser with uBlock Origin, or Adblock Plus with "block unintrusive ads" checked will also block ads on YouTube. Unfortunately this method only works on a PC with a compatible browser.
Currently this is your best bet.
Cheers!
