### ISSUE TITLE
Domains which breaks apps functionality.

### ISSUE THREAD

**Issue by asaddon** [StevenBlack/hosts#880]
Hey, all of these domains breaks some kind of functionality in the apps and should be removed ( I've only tested on iOS since I only have access to that )

**h-sdk.online-metrix.net**

This breaks the **TouchID** function on the **Skrill** iOS app.

**graph.accountkit.com**

This breaks Facebook's One time Password authentication ( Apps are not able to send the code )

**s.youtube.com**

This breaks YouTube's Watch history function.

**zee.cws.conviva.com
pings.conviva.com
cws.conviva.com**

These domains breaks the video playback on **ZEE5** iOS app.

**Comment by lightswitch05** [comment]
> **h-sdk.online-metrix.net**
> This breaks the **TouchID** function on the **Skrill** iOS app.

I would be very concerned if I were you if blocking an advertising and tracking company broke your TouchID functionality. Besides that, this is a very prolific online tracker, and I would not be convinced to remove it from my list just because a single app can't properly do error handling.

> **s.youtube.com**
> This breaks YouTube's Watch history function.

This block has already been discussed in #861 

> **pings.conviva.com**

This block comes from the 'MVPS hosts file' list. The README has winhelp2002@gmail.com as the support contact for that list.

> **graph.accountkit.com**
> **zee.cws.conviva.com**
> **cws.conviva.com**

Those are all blocked directly by this list, and I'm sure others can discuss the pros/cons of those blockes.

**Comment by StevenBlack** [comment]
@anudeepND some of these `conviva` domains were introduced 9-months ago by commit bbe349083b7b0a50ca2c72f1998.   Any comment on origins, that you can recall?  

ZEE is a Video on demand company in India...  It's [rather new](https://en.wikipedia.org/wiki/ZEE5).
