### ISSUE TITLE
id.google.com

### ISSUE THREAD

**Issue by kafukala** [StevenBlack/hosts#890]
I have no idea what this is: id.google.com
I think we dont need this. But 1 problem, id.google.xx have many domain extensions. As you use google.nl, than you have id.google.nl as you use google.be, then you have id.google.be

Who can tell me more about this? Is it possible to block this?

**Comment by spirillen** [comment]
Well id.google.{tld} all seems to resolves to id.l.google.com so by blocking `id.l.google.com` this is a way to resolve this... but as said, what is the usage of `id.google.{tld}`

As now the `id.l.google.com` is added to our RPZ as `id.google.com` already is there, and haven't cursed any issues, so to prevent any further issues of privacy violating behavior from google, I suggest we
  1. Dig deeper into what's the usage of this domain
  1. Test if it is coursing any issues to users of Google

**Comment by kowith337** [comment]
I remembered from uBlock0 log, it's go to `id.google.com/verify?` with something too long behind and seems to be encrypted.

**Comment by GraphixMedia** [comment]
Hi all, id.google.com 

> I have no idea what this is: id.google.com
> I think we dont need this. But 1 problem, id.google.xx have many domain extensions. As you use google.nl, than you have id.google.nl as you use google.be, then you have id.google.be
> 
> Who can tell me more about this? Is it possible to block this?

It has something to do with ADS. You can block this. ;)

**Comment by lightswitch05** [comment]
Alright, I know this is an old and closed ticket, but it caught my attention. Searching my [Blocklist Tools](https://blocklist-tools.developerdan.com/entries/search?q=id.google.com) website shows a number of lists blocking `id.google.com`. The oldest record I have is the [Bjornstar: Hosts](https://github.com/bjornstar/hosts/blob/master/hosts) project which has had the domain blocked since at least [2013-08-28T15:57:44.000Z](https://raw.githubusercontent.com/bjornstar/hosts/e4cbe0f1650ba777f00e316f724112301df816a1/hosts) - which is the oldest version I'm aware of. ANYWAYS, what caught my eye is that `id.google.com` was blocked in the unified list for a single day [Mar 23 2018](https://github.com/StevenBlack/hosts/commit/ba10e05a8eb79dbc327cec1ffc8cfd949b699072#) -> [Mar 24 2018](https://github.com/StevenBlack/hosts/commit/753ffb17f93a36bb53f33e452d8403858aae121c#). What is even more interesting is that the dates didn't line up with any of the other included lists. After reviewing the commits, I discovered that the Bjornstar list was actually included in the unified project for a single day.

Added: https://github.com/StevenBlack/hosts/issues/543
Removed: https://github.com/StevenBlack/hosts/issues/548

Fascinating (at least to me 😆)

Back on topic. If you are determined to block `id.google.com` but do not want to make the entry yourself, there are a number of other lists that you can easily include in your clone of this repo:

* [Bjornstar: Hosts](https://github.com/bjornstar/hosts)
* [Jerryn70: GoodbyeAds](https://github.com/jerryn70/GoodbyeAds)
* [Llacb47 mischosts: Blacklist](https://github.com/llacb47/mischosts)

**Comment by StevenBlack** [comment]
Thanks Dan @lightswitch05 I find this interesting too 😄
