### ISSUE TITLE
always minimizing/compressing

### ISSUE THREAD

**Issue by evannnc** [StevenBlack/hosts#898]
my host file is always being compressed despite never specifying --compress. all of the spaces are being removed no matter how i build it. I would like an easily readable file, but it is all one big line.  I'm running windows 10, python 3.7

**Comment by evannnc** [comment]
well i did some more googling and it looks like this is just a defect of windows notepad.

**Comment by StevenBlack** [comment]
Hi Evan @evannnc, it's not really a "defect" of Notepad.  It's by design.  It's a brain-dead design 😄 

Years ago, in the earliest days of Windows, the numbnuts at Microsoft decided that they would do line endings differently than everybody else.  That's still in Notepad.exe, several decades later.

You should download and try Notepad++, a lightweight third party text editor.  Or better still, [Visual Studio Code](https://code.visualstudio.com/).  It's 2019, after all, use a dynamite text editor.

**Comment by evannnc** [comment]
Thanks for the info and tips. I'm a long time user of Notepad++, but I've never heard of Visual Studio Code. I just downloaded it and it looks pretty awesome. It even has support for my native language zOS Assembler!

**Comment by StevenBlack** [comment]
VS Code has support for lots of things.  A tremendous ecosystem of addons and helpers.  It's cross-platform too.  I think VS Code is really something.

**Comment by dnmTX** [comment]
[unix2dos](https://waterlan.home.xs4all.nl/dos2unix/dos2unix-7.4.0-win64.zip) is also another simple alternative.
