### ISSUE TITLE
Reduce filesize by grouping multiple hosts per line

### ISSUE THREAD

**Issue by mrchief** [StevenBlack/hosts#911]
Sorry if this has been discussed before, my searches came out empty regarding this matter.

Currently, hosts are listed one per line. This increases file size and affects performance in some cases even.

Will it be a good idea to group multiple hosts per line? No special logic in the grouping, just have 8-10 hosts per line which can significantly reduce file size and improve load times.

Tools like HostsMan on Windows provide such a feature (to rearrange host file) but other OSes don't have such tools. Regardless of tools, I think it'd be good idea to do this at the source itself.

Thoughts?

**Comment by StevenBlack** [comment]
Hi Hrusikesh @mrchief, we've disscussed this in some depth already, notably in Issue #49 ***Use nine hostnames per line instead of one*** wherein we test hypothesis that this makes any difference.  Turns out, it doesn't.

That said, check out the `--compress` and `--minimize` flags which do what you suggest.

**Comment by OmlineEditor** [comment]
> That said, check out the `--compress` and `--minimize` flags which do what you suggest.

Tell me more where to find these settings?
