### ISSUE TITLE
Pi-Hole Format - Request

### ISSUE THREAD

**Issue by sea-wa** [StevenBlack/hosts#943]
@StevenBlack thank you very much for your efforts.

Would you please consider creating a clean PI-Hole formatted hosts file (only host names) without comments, spaces, or empty lines? Kinda similar to what's done here under Packs:
https://github.com/AdroitAdorKhan/Energized

**Comment by ione2121** [comment]
Give me hosts pubg mobile please

Pada tanggal Min, 31 Mar 2019 12.26, welcome[bot] <notifications@github.com>
menulis:

**Comment by ScriptTiger** [comment]
@sea-wa, check out the FQDN format here:
https://scripttiger.github.io/alts/

The reason why I provide all these formats separately is to alleviate such requests from this repository because the volume of information and the frequency with which the contents change causes the git history to become quite unmanageable after extended periods of time. This repository's primary focus is the Python script, which can be cloned and run locally. @StevenBlack, however, does provide the most common hosts file format as a kindness. My repo has a focus on pre-generated formats and I clean up the git history accordingly with every single commit, something which should be heavily avoided with this repo since tracking the development of the Python script is paramount, while tracking the changes of its output is not.

Also, these files cannot be provided pre-generated without the comments due to licensing obligations. If you want @StevenBlack's Python script to include a new switch to output as FQDN without comments, that's a different feature request and something you will have to run locally, as it cannot legally be distributed as such but only generated locally for personal use.

@ione2121, dari mana? Apa PUBG legal untuk Anda?

**Comment by ScriptTiger** [comment]
@sea-wa, as a follow-up to what I stated above, I would also recommend you address the comment/licensing issues in your repository:
https://github.com/sea-wa/pi-hole

You are currently violating GitHub's terms of use and could be penalized (i.e. have your account removed or suspended, or at least that repository, and/or given a stiff warning from the GitHub folks). I am sure @StevenBlack appreciates you giving him credit there, but he by no means produced the contents of that file alone. If you are just storing that there for personal use, I would recommend at least switching it to a private repository, although I am still not sure if that would technically be enough, depending on how many people have access to that private repository to qualify it as distribution. You can think of it as being similar to drug users that carry X metric of drugs and thus qualify to be held accountable as having the "intent to distribute," even if they only used it themselves. It may seem silly to some, but even if you strip out all the comments and credits, the remaining contents are still subject to licensure, as anyone dealing with geo data from Google, MaxMind, etc., knows all too well. If the contents' origin can still be traced within reasonable means, you are still within violation.

**Comment by StevenBlack** [comment]
Related: this new  [License issues](https://github.com/AdroitAdorKhan/Energized/issues/46) issue opened at https://github.com/AdroitAdorKhan/Energized/.

**Comment by StevenBlack** [comment]
@sea-wa Pi-Hole already includes this repo by default.

Closing.
