### ISSUE TITLE
Awesome Project, Please Expand?

### ISSUE THREAD

**Issue by Austin-Src** [StevenBlack/hosts#957]
I first want to say I REALLY appreciate this list, it has been super helpful! Would it be possible to add a section focused on blocking proxy sites as well? Currently many of them totally bypass the hosts filter :(

**Comment by StevenBlack** [comment]
Hey thanks for the kind words Austin @Austin-Src.

This has come up before, notably here:

* Issue #615 – ***Include proxy/anonymizer services***
* Issue #754 – ***blacklist porn proxy sites*** wherein [I make this comment](https://github.com/StevenBlack/hosts/issues/754#issuecomment-412405077):

![Aug2018](https://user-images.githubusercontent.com/80144/56326377-cb1eb080-6143-11e9-998e-ce11c2ce25ef.png)

We decided to make a separate extension for this, but that hasn't happened yet.

Closing because this is a duplicate.  But thanks for the input, and thanks for the reminder.
