### ISSUE TITLE
Hosts are fetched via HTTP

### ISSUE THREAD

**Issue by asvc** [StevenBlack/hosts#97]
<pre>> python updateHostsFile.py -a -r
Updating source yoyo.org from <b>http</b>://pgl.yoyo.org/...</pre>

Should we switch to HTTPS-only?

**Comment by FadeMind** [comment]
See: https://github.com/StevenBlack/hosts/pull/59
BUT IDK how yoyo.org SSL looking here...

**Comment by Laicure** [comment]
I think this topic solely depends on the sources if they use https, ftp, or whatever protocol as long as they provide the list so I think no issues here at all.

**Comment by StevenBlack** [comment]
@asvc thank you!

@FadeMind @Laicure with b1f2c3e I just made yoyo.org use https as this appears to work for me on OS X El Capitan.  

Do either of you get certificate warnings for yoyo now?

Something in me wants to do the Simplest Thing That Could Possibly Work and that would be http.  Because certs expire, and many other ways that cert issues can arise.

**Comment by FadeMind** [comment]
@StevenBlack yoyo.org via HTTPS working fine.

**Comment by Laicure** [comment]
Oh I see... /hmm
So I think no data source cert/etc issues here on my side (Windows user).
Thanks ;)

**Comment by skwerlman** [comment]
yoyo.org failing to download over https (can see it in browser)

on win10

**Comment by StevenBlack** [comment]
Works fine here:  https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0

**Comment by benlowry** [comment]
@StevenBlack even though http is more likely to work it trivializes someone injecting a list of servers to block in aide of an attack....  I think the default block lists should be HTTPS only.

**Comment by StevenBlack** [comment]
Thanks for your input on this Ben @benlowry.

Considering the extensibility of the hosts amalgamation, it's probably not realistic to force HTTPS without dealing with the opposite problem: people asking why force HTTPS when this or that particular source is great but is only available with HTTP.

But I totally understand what you're saying.

If someone cares to make a PR with a flag to force HTTPS, which we could make the default, and deal with both HTTP and HTTPS cases including error handling and documentation updates, well, I'd certainly entertain it.

**Comment by benlowry** [comment]
It should be `force-http` because that is where the danger lies.   This matters a lot more for a DNS server than a browser extension, using `force-https` means by default every device on every network using pi-hole continues to be at risk. 

This might be solvable by contacting the last defaults (I think only 2 exc. malwarebytes that I saw the other day has HTTPS) and asking if they'd provide a HTTPS version.  I wrote the someonewhocares.org email address on Monday to suggest some free options they might use  - https://letsencrypt.org/ for free SSL, https://www.cloudflare.com/ over their website, a github repo/gist etc.  I'll dig into the other one and see if I can contact someone there too.

It's probably possible to replicate the lists in a git repo too and automatically keep them in sync as well.  That would start with a potentially compromised list but every change would be traceable and people downloading that copy could be sure they are not receiving something that has been tampered with since.

**Comment by benlowry** [comment]
BTW @StevenBlack you might like how I have used your project - I used it to supplement a DNS server called [Pi-hole](https://github.com/pi-hole/pi-hole) that blocks ads and includes an admin interface and browser extensions, and I added the ability to use custom domains on your network.  
This lets the blocking occur network-wide - 

https://github.com/benlowry/pihole-extended-hosts

**Comment by StevenBlack** [comment]
Hey Ben @benlowry that's excellent!

Keep up the good fight!  :-)

**Comment by benlowry** [comment]
The 'someonewhocares.org' person wrote me back and said he will look into providing a HTTPS version.

**Comment by StevenBlack** [comment]
This is great Brn @benlowry.  Thanks!
