### ISSUE TITLE
Safari attempts to query with "www." prepended causing some blocks to fail

### ISSUE THREAD

**Issue by mys721tx** [StevenBlack/hosts#982]
Some points after Mountain Lion, Safari will attempt to query again with `www.` prepended after the first query failed. ([related question on superuser](https://apple.stackexchange.com/q/92710/37956)) For example, when the following is added:

```
0.0.0.0 example.com
```

Although query to `eample.com` will fail, the query to `www.example.com` does not. Safari is still able to connect to `example.com`. "Show full website address" option is turned on for the screenshots.

```ShellSession
$ dns-sd -G v4 example.com
DATE: ---Thu 23 May 2019---
 2:24:34.094  ...STARTING...
Timestamp     A/R    Flags if Hostname                               Address                                      TTL
 2:24:34.095  Add        2 -1 example.com.                           0.0.0.0                                      1
$ dns-sd -G v4 www.example.com
DATE: ---Thu 23 May 2019---
 2:25:48.835  ...STARTING...
Timestamp     A/R    Flags if Hostname                               Address                                      TTL
 2:25:48.852  Add        2  0 www.example.com.                       93.184.216.34                                3968
```
![image](https://user-images.githubusercontent.com/561975/58230468-64705200-7d02-11e9-9fe0-d1c8ec36de8a.png)
![image](https://user-images.githubusercontent.com/561975/58230489-7d790300-7d02-11e9-9cbf-8210ae94be67.png)

This caused some entries on the block list to fail. Perhaps when generate hosts on macOS, an entry with `www.` should be added to prevent this.

**Comment by mys721tx** [comment]
Additionally, IPv6 may also require blocking. To completely block `example.com`, the following entries are needed in `/etc/hosts`:

```
0.0.0.0 example.com
:: example.com
0.0.0.0 www.example.com
:: www.example.com
```

**Comment by ScriptTiger** [comment]
Personally every time I submit a PR here I always check for WWW domains and make sure they are included, along with any other malicious domains that can be enumerated within reason, and I know several others do the same. Since hosts files are not dynamic and can't use wild cards or REGEX, etc., everything must be explicitly stated.

Now I am not belittling your comments at all, on the contrary I agree that this is indeed a huge issue for those that may be affected by it. However, the solution to this problem would still be PR any WWWs that are leaking through to either the appropriate upstream sources, this being the preferable method, or to the `hosts/data/StevenBlack/hosts` file if for some reason these entries cannot  be appended to upstream sources.

So while this is undeniably a huge issue, the real call to action here is simple a notice to affected Safari users to stay vigilant and actively contribute any malicious domains that are still leaking through. This project depends immeasurably on contributions from fans such as yourself.

As for the IPv6 issue, this has already been discussed at great lengths several times and a number of solutions have already been posed for those that need it. I have to admit though that something about this should be added to the `readme_template.md` to prevent further references to this from popping up in the future, as it is justifiably of serious concern for many. Maybe everyone could just look through our issues and vote on the best solutions or give suggestions or something. Please refer to our issue database for more info:
https://github.com/StevenBlack/hosts/issues?q=IPv6

**Comment by StevenBlack** [comment]
Thanks everybody.  I expect source curators will get this, eventually.

Closing.
