### ISSUE TITLE
cdn.crowdtwist line blocks the Borderlands Insider Program pages images from loading

### ISSUE THREAD

**Issue by AkiraJkr** [StevenBlack/hosts#995]
Title tells it all, you can see it for yourself.

https://borderlands.com/en-US/vip-rewards/

**Comment by dnmTX** [comment]
@AkiraJkr  the domain in question is a tracker and that is why it's blocked:
`script.src = '//cdn.crowdtwist.com/trck/prod/2/'`
On my end(chromium browser) nothing showing up when trying to open it and there are bunch of errors in  dev tools so.Most likely there is a problem with the website and the `cdn.crowdtwist` is not the culprit here.

**Comment by StevenBlack** [comment]
Thanks Dan @dnmTX.

Closing.
